future_deck = {
    "the fool": {
        "title": "It might sound bad from the name, but The Fool tarot card is not a negative card at all! In fact, it’s associated with the number zero – the number of infinite potential. In the Major Arcana, The Fool represents you, the main character,  journeying through life. So, when The Fool shows up in your reading, get ready for major change and transformation! The Fool tarot card is all about living in the present moment and enjoying your life without worry. Just look at how happy the man in the card is in spite of his treacherous surroundings. Sometimes we need to take a little risk, even if we aren’t sure how things will turn out, because, if we never try, we will never know what could have been! The Fool reminds you to stay true to your heart and follow your dreams.",
        "normal": "It’s looking like a new adventure might be just around the corner! Whether the love of your life is about to cross your path or your dream job is about to pop up, The Fool in the future position is really exciting! Keep your eyes open for new opportunities and try not to let worries or fears stand in your way. Enjoy what the universe is bringing you and just say “Yes, I can!”",
        "reversed": "Beware of reckless tendencies in the upcoming days and weeks. The Fool in reverse can be a bit of a loose cannon, and when he presents in the future position, you’re being put on notice not to avoid all responsibility. Alternately, if you’re blocking your inner child, this card might also pop up in reverse. Try to find balance."
    },
    "the magician": {
        "title": "You’ve got what it takes to make it happen! That’s the general message of The Magician tarot card. With diligence and focus, you can create anything you desire, but you have to be deliberate in your actions and choices. Use your willpower and don’t underestimate your own abilities. Sometimes we don’t realize everything we have available to us. The Magician encourages us to have confidence and to be resourceful.",
        "normal": "The Magician in the future position is telling you to keep going – you are almost there! You’ve been putting in the hard work and following the proper course of action to achieve your goals. Keep at it and continue honing all of your skills. You are about to have everything you need at your disposal to bring your vision to life.",
        "reversed": "Be careful of tricksers or manipulators in your future. There is a situation approaching that might involve someone charming that doesn’t have your best interests at heart. It might also indicate that a project or situation may not turn out as you have been hoping. The reversed Magician is putting you on the lookout for any situation that involves illusion and deceit."
    },

    "the high priestess": {
        "title": "The High Priestess is a powerful card to receive in any tarot reading. She urges you to avoid conflict and listen to your inner knowing. Are you facing a tough decision? Maybe there are so many options available to you that you’re not sure which one to choose? This is a time when sitting in stillness and listening to your heart is in order. You already know which option feels right, and The High Priestess encourages you to remain true to that inner knowing.",
        "normal": "There may be a big decision on the horizon where things may not be as they seem. Be careful not to take the situation at face value. Listen to your intuition and read between the lines as challenges come up. Answers to your questions might be revealed to you in your dreams or sudden moments of insight. Trust your heart and move forward with patience and calm.",
        "reversed": "Be sure to stay connected to your gut feeling about any conflict that may arise in the coming weeks or months. Someone may be being dishonest with you and The High Priestess in reverse is putting you on notice to watch for signs and listen to your intuition."
    },

    "the empress": {
        "title": "It’s time for you to stop and smell the roses! The Empress takes the time to enjoy and appreciate all of the finer things in life, and she’s appearing in your reading to remind you to do the same. She is Venus, the ruler of love, art, and beauty, and represents fertility of all kinds. Whether your reading is about romantic relationships or your career, the message of The Empress is to bring your creative ideas and pursuits into the physical world. But, if she’s showing up in the reverse, it might be that you’ve gone too far into luxury and enjoyment! A reversed card always means that the qualities of that archetype are too extreme. In reverse, The Empress suggests that too much of a good thing can lead to laziness and co-dependence.",
        "normal": "You definitely have some pleasures coming your way with The Empress in the future position! You are about to manifest your desires and you have good fortune coming your way. The Empress of the Major Arcana represents abundance of all kinds, so whether you’re looking for romance or a boost to your financial situation, things are about to get good.",
        "reversed": "Have you been feeling the urge to be creative and start a meaningful project, but you can’t seem to get into the groove? The Empress in reverse can leave you feeling disconnected and dissatisfied, so be on the lookout for any of these tendencies. Make sure you’re not shirking your responsibilities or spending money you don’t have! And by the same token, don’t run yourself ragged either. Be sure to take time for yourself for rest and relaxation when you need it!"
    },

    "the emperor": {
        "title": "The Emperor uses power and organization to accomplish his goals. He is wise and powerful in his ways, and in the upright, can act as a protector. This card in your reading can represent your current energy, or can also represent a boss, father figure, spouse, or system of authority that is prominent in your life. When he appears in the reverse, The Emperor is tyrannical. He is overly rigid, lacks empathy, and won’t think twice about using force to get what he wants, even at the expense of others. The energies of this Major Arcana card are a powerful influence for good or for bad.",
        "normal": "Brace yourself for a big change! You’re going to have to adapt to a new set of rules and regulations in the near future that could throw you for a loop. But if you face these challenges boldly, this new system will provide you with extra security and you’ll wind up feeling like you have more control over your life.",
        "reversed": "The Emperor in the reverse is never pleasant, and if he’s turning up in your near future, you’re headed for some conflict and confrontations. You are likely to find yourself in a struggle with someone in a position of authority. Or you might have to deal with a bad boss, lots of bureaucracy, or someone who is lacking focus. Whether The Emperor expresses in excess or lack, always look to regain balance."
    },

    "the hierophant": {
        "title": "Sometimes The Hierophant is referred to as The Pope of the priest of the Major Arcana. The Hierophant mirrors The High Priestess in the same way that The Emperor mirrors The Empress. This Major Arcana card is a masculine card representing structure and tradition but is focused on the spiritual realm. He is a card of religious doctrine, which values faithful devotion to traditional religious practices as a means of reaching spiritual fulfillment.",
        "normal": "It looks like you will be developing a relationship with a spiritual guide or mentor in the near future. This wise teacher will support you in your personal spiritual evolution, and you will be able to join a cause that’s greater than yourself.",
        "reversed": "If this tarot card is reversed, be on the lookout for someone who wants to use religious doctrine or dogma to influence or control you. Stay connected to your core values and beliefs and you won’t be led astray."
    },

    "the lovers": {
        "title": "The Lovers card has landed in your tarot card spread to signify a beautiful relationship in your life! There is clear communication and an ability to be vulnerable with one another. This card often signifies a sexual relationship, though it doesn’t have to be. This Major Arcana card also represents choices. It seems that an important decision will be coming up in your life, so the surrounding cards of the reading will be very important!",
        "normal": "Get ready for something new and exciting coming your way in the field of romance and passion! The Lovers in the future position indicates that you are in a place energetically to receive love and that you will shortly attract it into your life. Take this time to contemplate what you truly desire in a relationship so that you can manifest a harmonious partnership.",
        "reversed": "A break up might be in store for you if The Lovers presents in the reverse. Make an effort to engage in open and honest conversations and take responsibility for your choices. Sometimes we hang onto things in life that aren’t good for us because of fears or negative beliefs about ourselves and others. Have the courage to do the right thing so that you have a real shot at true happiness in the future."
    },

    "the chariot": {
        "title": "The Chariot represents overcoming obstacles after a long journey or hard-won battle. Depending on where this tarot card appears in your reading, the message is one of maintaining focus and confidence in the pursuit of your goals. The Chariot card suggests that your strength and commitment is being tested by the universe, so don’t give up or look for shortcuts. Are you pushing yourself ahead at break-neck speed to the point of obsession? This might be why The Chariot is showing up in the reversed position in your tarot card reading. If the pursuit of victory is becoming excessive, you might actually be standing in your own way. If you’re lacking direction and feel yourself floating aimlessly, a reversed Chariot card will also appear in your reading. Whether your willpower and focus is excessive or lacking, the goal is the same: bring these energies into a healthy state of balance.",
        "normal": "Whatever you are going through right now, The Chariot in the future position ensures your ultimate success! This Major Arcana card is at its most powerful in the future position and indicates that your plans are being supported by the universe.",
        "reversed": "In the reverse, The Chariot reminds you not to give up if things get tough! You might be facing some challenges in the near future that will require you to keep your nose to the grindstone. Tap into your competitive nature and think of these obstacles as a workout at the gym – the harder you train, the stronger you will be in the end."
    },
    "the justice": {
        "title": "You can expect a fair outcome to a challenging situation in your life! If you have acted with integrity toward others but you have been wronged or hurt, the Justice card assures you that karma will be brought back into balance. However, if you have made decisions that harmed others, the Justice card comes as a warning. Justice demands truth and honesty, so a reversed Justice card indicates gossip, misinformation, and lies. You may have behaved in ways that were morally questionable and you are failing to take responsibility for your choices. Be fair in your choices and be sure to seek out the facts before making any judgements or assumptions about others, and make an effort to right the wrongs you committed before Justice does it for you.",
        "normal": "Stay balanced and listen to both sides of the story when a major decision comes your way in the near future. Make the effort to really understand the facts and weigh all options carefully. Everything you have been working toward is about to come to head, and if you have been acting in good faith, Lady Justice is going to reward you.",
        "reversed": "Are you in denial? Are you avoiding taking responsibility for your actions? Justice in the reverse warns you that if you continue on your current path, you will be getting some karmic payback in the near future and it won’t be good. In the end, the scales of justice are always put back into balance. So, if you have the opportunity to do that yourself, now is the time."
    },
    "the hermit": {
        "title": "The Hermit is the soul searcher and is here to encourage you to reflect on your deepest feelings and needs. The appearance of this Major Arcana card in your tarot card reading heralds a time for pause. There is often a major turning point around the corner. A new path may be opening to you that you have been unable to see because of the noise and distractions in the outside world. Sometimes life forces us into retreat and sometimes it’s by choice, but either way, it is from the darkness that we find the light. When the energies of The Hermit are out of balance, he will present in your reading in the reversed position. This can indicate escapism rather than self-reflection, or a resistance to looking within for answers.",
        "normal": "It looks like you’re going to be spending some time doing some deep soul searching in the near future. You might be choosing to remove yourself from a toxic situation that requires you to disconnect from your life as you know it. Or perhaps you will realize that your current life path is not fulfilling you on a soul level. You may need to retreat to plan and strategize a way forward. The Hermit in the future position portends the ending of a chapter in your life and the beginning of something new. You’ll be guided by your inner wisdom to problem-solve effectively and come out with a newfound sense of freedom and purpose.",
        "reversed": "Have you been in a long period of introspection and contemplation? The Hermit in reverse in the future placement indicates that this time may finally be coming to an end. This can also indicate relief from a difficult situation, where you find the peace and solitude you need self-healing."
    },

    "the wheel of fortune": {
        "title": "Fate and destiny are about to kick in so get ready for some major changes. This can apply to your romantic relationships, career, health, or any other subject you are delving into with your tarot card reading. Our lives are made up of a series of cycles, and The Wheel of Fortune makes an appearance when one cycle is about to end so that another one can begin. One thing we know for sure is that things always change. The Wheel of Fortune is generally associated with good luck, but if it appears in the reverse, it’s suggesting that you’re resisting change. Or maybe you’ve got yourself stuck in an endless cycle of repeating patterns. Sometimes even “bad luck” leads to positive change, we just can’t see it until afterward.",
        "normal": "Your life is about to get exciting! The Wheel of Fortune is in your future position, which means that big changes are underfoot. Depending on the focus of your tarot card reading, whatever intentions you have set in motion and have been working toward are about to manifest in a positive way. We can’t predict how things will unfold, but as long as you remain flexible your outcome is likely to be very positive.",
        "reversed": "In the reversed position, The Wheel of Fortune doesn’t necessarily indicate bad luck. The card is advising you that there will be an opportunity for change in the future, and if you do not seize it, you may be doomed to repeat the same cycles endlessly. Don’t resist the change when it comes your way. On the other hand, if you have been in what seems like endless change and transition, a reversed Wheel of Fortune may be suggesting that this will finally be coming to an end."
    },

    "the strength": {
        "title": "The Strength card follows The Chariot in the Major Arcana series. After we learn to use our strengths externally to overcome the stumbling blocks on your path, we must also learn more compassionate and refined ways of achieving our goals. The lesson of the Strength card is that we do not need to control others in order to succeed. We can rely on stamina, patience, and understanding to maintain harmony and balance in our lives.",
        "normal": "You might have been struggling to maintain your composure lately, so The Strength card showing up in the future position is a welcome sign that you are about to get your emotions under control. The more you work on releasing the ego’s need for attachment and control, the more easily you will let painful events roll right off of your shoulders. As you grow your inner power, you will feel less inclined to need to control others or allow them to control you.",
        "reversed": "When a situation arises that requires you to be courageous and stand for what you believe in, remember that you catch more flies with honey. Forcing your will lead to conflict and negative outcomes. Try to tap into your powers of persuasion instead."
    },

    "the hanged man": {
        "title": "Are you trying to control things, but you’re not getting the results you want? It’s time to take the advice of The Hanged Man. This tarot card tells you to take a pause so you can gain a new perspective on your situation. This card is all about choosing to surrender to the flow of the universe. You received this card in your tarot card reading because there is some situation in your life that you need to respond to in a new way.",
        "normal": "There’s a storm brewing in your future, so be sure not to become wrapped up in it. Take care to make sure you don’t get painted as the aggressor. Choose the path of least resistance and walk away from conflict. When people really want to fight with you, sometimes the best thing we can do is withhold the conflict itself by refusing to engage in it.",
        "reversed": "If you’re feeling trapped by circumstances outside of your control, The Hanged Man in the reverse in your future can be a good omen. Depending on the surrounding cards, things may finally start moving again. However, if you find yourself embroiled in conflict, take this as a warning and do not engage."
    },

    "the death card": {
        "title": "The Death card of the Major Arcana is symbolic of endings, allowing a chapter of your life to “die” so that a new one can begin. It’s not always easy to let things go. Accepting endings can be painful. But it is important to remember that what is in store for you is likely to be even better than what you are leaving behind. Everything in the world works in cycles, so embrace the endings so you can look forward to the new.",
        "normal": "You are going to have a major change or loss in your future, but it is nothing that you can’t withstand! When The Death card comes to bring an end to something in our lives it also brings lessons. The journey of The Fool through the Major Arcana is all about growing spiritually. Every challenge and obstacle we overcome makes us stronger and wiser. As we overcome and release, we learn our own strengths, and we also make room for beautiful new opportunities.",
        "reversed": "In the reverse, The Death card is warning you not to resist the change that will be coming your way. You might need to undergo a major emotional purging. It’s a good idea to pull some clarifying cards to reveal the deeper meaning of this card in this position."
    },
    "the temperance": {
        "title": "On The Fool’s journey through the Major Arcana, The Temperance card comes up after the Death card. It’s often the painful things in life that become our greatest teachers. When life asks us to let go of something that is very important to us, we begin to learn non-attachment. Temperance has discovered that adaptability, trust in the universe, and moderation brings us the greatest peace. When we surrender to the flow of the universe, we can begin to live an enlightened existence.",
        "normal": "Whatever you’re going through right now, you have peace and tranquility on the horizon! With Temperance in your future you just need to hang in there a little bit longer – your troubles are about to come to an end. Look forward to wellness and balance in your life, whether in relationships, career, or any other aspect of your life.",
        "reversed": "When Temperance appears in the reverse in the future position she is advising you that there will be challenges ahead that you must approach with grace and calm. Be careful not to respond to difficult situations in an extreme way, whether it’s avoidance, reckless behavior, confrontation, or any other imbalance kind of response."
    },

    "the devil card": {
        "title": "It’s easy to lose sight of the fact that nobody else is responsible for our happiness and that no matter how hard we try, we can’t find happiness in the external world. This is how addictions and attachments develop. The Devil card exposes our tendency to shift responsibility, whether it’s by adopting the victim mentality or by numbing ourselves with carnal pleasures. Until we learn to generate happiness from within, we choose to remain chained, so to speak.",
        "normal": "You’re headed down a dangerous path if you don’t stop and examine what is driving you. Are you getting swept up in a toxic environment? Are you pursuing a course of action that you know will be detrimental to you in the long run? The Devil card in the future is warning you to look at your motivations and choices honestly. There may be someone alluring in your future that you know will lead you into a world of pain. Make the effort to tame your passions when you find yourself tempted to walk down a path of self-destructive behavior.",
        "reversed": "If you’re currently in a toxic relationship, The Devil in the reverse appearing in the future position can indicate that you will soon be breaking free from your destructive situation. By taking responsibility for your actions, you will find control and walk away from codependency. You may be overcoming an addiction or a victim mentality."
    },
    "the tower": {
        "title": "In its essence, The Tower represents a groundbreaking change. It doesn’t always foretell chaos and destruction, though by the look of the card you might think so! Lighting strikes a stone tower and people are jumping from the windows to escape the flames. This card follows The Devil card in the Major Arcana, and the message is clear: do not resist change or the universe will force it upon you.",
        "normal": "There’s no easy way to say it. In the future position, The Tower card indicates that you are in for some major upheaval and life-altering change. It’s true that these shocking events can shake us to the core, but they also force us to grow spiritually. Like the baby bird that gets kicked out of the nest so that it can learn to fly, a tower moment will have you feeling like the world is out of control. Stay calm and remember that these lessons are training grounds, and you will emerge the better for it.",
        "reversed": "The Tower in the reverse can indicate a transformation on an internal or spiritual level. You may be releasing long-held beliefs or traditions or experiencing a spiritual awakening. In the reverse, the Tower can also indicate a resistance to change."
    },
    "the star": {
        "title": "You’re wishing upon a star when this Major Arcana card makes an appearance in your tarot card reading, and the good news is that your wishes are about to come true! Will it be new love, or taking your relationship to the next level? The energies of hope and faith surround you and are supporting you in a brand new path or direction. You have a lot to be optimistic about because the universe is blessing you at this time.",
        "normal": "No matter what is going on in your life right now, and no matter how difficult it might be, don’t give up hope! The Star in your future is here to tell you that you will have a chance at beginning something brand new and beautiful in the very near future! You will find peace and rejuvenation and you will heal from whatever painful event you went through.",
        "reversed": "It’s time to reevaluate your plans, because your current path won’t end up the way you’re hoping it will. Don’t despair though! The Star card in reverse is just a little messenger giving you a heads up to be practical instead of naive. Be careful of people who bring you down or promise you the moon."
    },
    "the moon": {
        "title": "When times are uncertain, we often begin to feel afraid or anxious. The Moon card represents a time of the unknown where we might feel out of control. But rather than hiding or running from the shadows, take the time to listen to your intuition. Whatever is revealed to you will only serve you in the end. When we discover things that are hidden beneath the surface, we can take action to better our environment.",
        "normal": "A time of creativity and feminine inspiration is approaching. Do you have some emotions dwelling in your subconscious that you want to express? With the Moon card in the future it will be a good time to get involved in an artistic project. But remember that the Moon also brings illusion and can lead us into our shadow side.",
        "reversed": "Someone may be trying to lead you astray in the near future, so remain on guard. The Moon card in the reversed position indicates the negative energies of this card and can portend a spiritual awakening or dark night of the soul. As you move forward, bear in mind that the situation may not be what it seems, and be sure to listen to any warning signs."
    },
    "the sun": {
        "title": "Positive energy is all around you sending warmth and confidence to all that you do. Just like the sun in our sky makes the plants grow and gives us light and warmth, The Sun card of the tarot is also representative of the source. It comes toward the end of the Major Arcana after The Fool has made his journey through many obstacles and challenges. All of these trials have made the querent a better person because he now knows how to live in the light.",
        "normal": "Whatever you are dealing with right now you are guaranteed an excellent outcome! The Sun in the future position of your tarot card reading is telling you that everything is going to work out in your favor! If you’re having some trouble in your love life or some problems at work, don’t fret. You will be happy with the end result soon enough.",
        "reversed": "Don’t forget to stay positive! With The Sun in reverse in the future, you might feel the urge to fall into sadness or you might begin to question yourself. Maintain your confidence and positive outlook! On the other hand, if your tendency is to get a little full of yourself, make the effort to keep your self-confidence in check in the near future, so you don’t mess up a good thing."
    },
    "the judgement": {
        "title": "When we undergo a spiritual awakening we realize that the answers are always within us. Others who judge us are merely projecting their own fears and insecurities on us and the same is true when we judge other people. Judgements come from a place of fear and we erroneously think that if we reject what makes us feel uncomfortable we will somehow be safe from it. The Judgement card asks us to look within ourselves instead, so that we may be freed from past beliefs and choices and live our lives with grace.",
        "normal": "You are about to be presented with an opportunity to remake your life with honesty and integrity. The Judgement card in the future position indicates that a big change is coming and your choice will offer you the opportunity to live a new life in freedom and grace. If things have felt cloudy and confusing, clarity is around the corner. The choice may be a difficult one, but if you use your intellect and intuition for the greatest good, you will find liberation.",
        "reversed": "Don’t resist the call when it comes – it won’t go away. Take this opportunity to release any self-doubt, shame, guilt, or blame that you are carrying from past wounds. Practice self-forgiveness and self-love and take pride in all of the beautiful things you have accomplished in your life. When the time comes make the bold choice from your heart and leave the old, negative patterns and cycles of behavior behind you for good."
    },
    "the world": {
        "title": "You feel like you’re on cloud nine right now because your life is in perfect alignment with your innermost dreams and desires. You successfully completed your journey through the 22 cards of the Major Arcana, each one of them carrying a profound lesson with accompanying challenges. All of these obstacles were your training ground and the final card, The World, marks your arrival! You learned to trust the universe as well as yourself, and you learned to surrender when needed. You learned to use your intuition and control your passions.",
        "normal": "You are on the right track, just keep going! The World card is in your future position to encourage you to keep doing what you’re doing. It is leading you to the fulfillment of your dreams. Trust yourself and move forward with confidence because you are almost there!",
        "reversed": "Do ask yourself if you’re endlessly chasing dreams without ever finding satisfaction in your accomplishments. The World card in the reverse in the future position can suggest you might be taking your pursuits too far, all the while missing what you already have. It’s a good time to pause and make sure that you are taking the time to appreciate your accomplishments."
    },
    "ace of cups": {
        "title": "The Ace of Cups is the first card in the suit of Cups. A largely positive card, you should expect good things to happen when you see it. Cups represent emotions, and so the Ace of Cups tarot card can represent a beginning of emotions, think new relationships, friendships and connections. Cups represent our feelings, over our logical thoughts.",
        "normal": "The Ace of Cups tarot in the future position suggests a future struggle that you will overcome. Imagine yourself climbing a mountain, there is a struggle but so long as you continue upwards you will reach the reward. People often say it as a joke, but you only fail if you give up. Persistence is key. As emotions are tied into this, there is a chance you will have to deal with something which will take a toll on how you feel in day to day life. Good and bad, you will grow and be a better person if you don’t give up.",
    },
    "two of cups": {
        "title": "The Two of Cups is the second tarot card in the Cups suit. The Two of Cups shows a man and woman staring into each other’s eyes, gaze fixed over two large cups. The duality symbolism is clear; male and female on opposite ends of the card. The winged staff of the caduceus represents a mythic chimera; possibly something is amiss or unknown, although this does not signify deceit or lies.",
        "normal": "The Two of Cups tarot card in the future position suggests that you should look to your existing friendships and relationships for inspiration in the future. You know these people well, and nobody gets anywhere alone. The Two of Cups in Future can suggest a strong, happy healthy relationship. A great card to draw in this position if you are worried about who you will end up with, as the worry should be over.",
    },
    "three of cups": {
        "title": "The Three of Cups is the third tarot card in the Cups suit. The card shows three people meeting, celebrating with cups held to the sky. A bounty of fruit and vegetables are by their feet. The scene is representative of a harvest festival ritual celebration, and gives off a good feeling. The Three of Cups is a good card to draw in almost any position.",
        "normal": "The Three of Cups in the future position gives you something to look forward to. We’re always doing projects and working hard. There is always something new. The cycle of work and rest is a balance we will continue to experience. It’s possible you’ll run into some old friends. Maybe you even have a reunion coming up. You should always try to connect with those from your past, you never know where these connections will lead.",
    },
    "four of cups": {
        "title": "The Four of Cups is the fourth tarot card in the Cups suit. The image shows a man sitting under a tree, intently looking at three cups. An arm protruding from a cloud is offering him a fourth card, which he is either ignoring on purpose or just cannot see. Not a wholly positive card, but not bad either, the Four of Cups can represent a mind that is sometimes so focused that it misses the bigger picture.",
        "normal": "The Four of Cups in the future position can mean that there will be a period in the future that you’re going to have to stop, sit down and think about. Not necessarily a tough decision, but just something that you’re going to need to contemplate to understand. Consider your choices in the near future, which ones are better or worse for you? Are you going with your heart or your head? It can take some time to get on the right path.",
    },
    "five of cups": {
        "title": "The Five of Cups is the fifth tarot card of the Cups suit. Taking a darker outlook, the Five of Cups is one of the negative tarot cards. The central character, clad in black faces three overturned cups, representing failure. Behind him are two upright ones. There is a certain positive aspect, not all is lost, but right now he is failing to see it.",
        "normal": "The Five of Cups in the future position suggests a period of time in the future when you’re going to regret what has happened. Are you currently consciously doing something wrong? You will regret it. Are you unsure about an upcoming decision? Think about it more and get some more opinions.",
    },
    "six of cups": {
        "title": "The Six of Cups is the sixth card in the Cups suit. The children suggest it’s a look back to childhood. The cups are not being used for their intended purpose, but inventively being used as a vase for flowers. A pleasant positive card which brings back warm memories of the past.",
        "normal": "The Six of Cups in the future position means you should use your good memories of the past to set an example for your future. In ten years, do you still want to be looking back on those memories, or newer, fresher better ones that you’ve made since? Some of us fear change, but we look back and understand that it was for the best. Again, the six of cups reminds you to not focus on the good things you have done, do not treat them as good enough. You could live a wonderful, envious life by constantly pushing and challenging yourself. Think back to what you wanted to do as a child, the six of cups urges you to fuel for your future dreams.",
    },
    "seven of cups": {
        "title": "The Seven of Cups is the seventh tarot card in the suit of Cups. The card is all about choices. The character is having a vision of 7 cups offering 7 different gifts and is having trouble deciding. One of the choices is different from the others; an objected veiled in a cloth. We can interpret this as viewing the future and the clouded choices that we make based on appearance and assumption instead of fact.",
        "normal": "The Seven of Cups tarot card in the future position suggests an upcoming touch choice. You might have trouble deciding and it’s going to be a big drain on you. Right now you’re leading up to it, so if you know what it is, prepare now. Rule out what you don’t want. Consider anything upcoming, what are the best paths you could take? It might be that one aspect of your life will be worse off after any choice, so look again to what you might have to give up.",
    },
    "eight of cups": {
        "title": "The Eight of Cups is the eighth card in the Cups suit. The illustration shows a man walking away from a river, on the other bank are some cups stacked irregularly, leaving a large visible gap. Heading away, the man is abandoning his cups, the structure they created left unfinished.",
        "normal": "The Eight of Cups in the future position suggests that a future aspect of your life might not go to plan. Consider if you’re on the right path, to begin with. Are you doing what you want with your life? On the upside, however, it may lead you to new things. You really have to just go with the flow. Think about your life now. Bad things are going to happen in the future, you can guarantee it, it’s simply a fact of life. prepare if you can, but more often than not, something bad will come out of nowhere.",
    },
    "nine of cups": {
        "title": "The Nine of Cups is the ninth tarot card in the Cups suit. A positive card generally, the illustration shows a character sitting in front of a collection of nine cups, proudly on display. His big grin and folded arms give us a sense of completion; he has achieved.",
        "normal": "The Nine of Cups tarot in the future position shows you in the future. You might just be starting off on a project or course of study and having cold feet. Go with it and dedicate yourself. The best advice anybody can give you is to start. Start your project, ambition, hobby. Just begin. There is no reason for anything you make to be good at the start, it is only by constantly working on something that you will improve.",
    },
    "ten of cups": {
        "title": "The Ten of Cups is the tenth tarot card in the Cups suit and is an extremely positive card. The illustration shows ten cups suspended in a rainbow with a couple, likely married, looking at it. Children play in the foreground and an idyllic village lays in the background. The Ten of Cups is all about happiness and being positive.",
        "normal": "The Ten of Cups in the future position reminds you of that idyllic image of your ideal life. You have to work hard to get there, but when you do, you’ll think nothing of the struggle. Things like mastery in your field, and people looking up to you for whichever reason will be common. We all have people we look up to because they have achieved what they set out to do. If you continue working as hard as you are now, you’ll get there too.",
    },
    "page of cups": {
        "title": "The Page of Cups is the eleventh tarot card in the Cups suit. The illustration shows a young man dressed in blue, holding a cup in his right hand. A fish is looking out of the cup at the man, and he is looking back. The card shows the innocence and curiosity of our inner child, as well as large imaginations unrestricted by logic or experience. Like many cards in the Cups suit, it’s a positive one. Fish emerging from water could be a symbol of knowledge being imparted, much like Oannes of Sumerian mythology",
        "normal": "The Page of Cups in the future position can mean that you’re currently not grasping 100% what you’re doing, but for whatever reason, you’re doing okay at it. Don’t worry, in the future, you’ll understand. It might signify a period of relaxing and leisure in the near future, an upcoming holiday or break period. There is a chance that a mentor will appear out of nowhere to give you advice, so be open to all possibilities.",
    },
    "knight of cups": {
        "title": "The Knight of Cups tarot card is the twelfth card in the Cups suit. The Cups are a positive suit, and the Knight of Cups is no different. With slight romantic undertones (think of the traditional Knight saving the Princess), the Knight of Cups is all about good news, and positive change.",
        "normal": "The Knight of Cups tarot card in the future position reminds you to stay focused. To truly succeed in anything, you initially need passion and a clear goal at the start. As you move on, you need willpower and mental strength. Expect yourself to grow emotionally over the coming months.",
    },
    "queen of cups": {
        "title": "The Queen of Cups is the thirteenth card in the Cups suit. Thirteen isn’t really an unlucky number when it comes to The Queen of Cups, like most other cards in the Cups suit, The Queen of Cups is a positive one. It also has many possible interpretations, from the straight obvious meaning of a female influence in your life to interpretations of maturity and intuition.",
        "normal": "The Queen of Cups tarot card in the future position can mean that in the near future, you’re going to go through a period where you’re going to have to be much more mature than you usually are. It could be in a caring situation, but the point to stress is that you’ll have to be patient and understanding. It might be tough for you. You’ll have to put on a brave face when things take a downturn. In effect, you will be the rock for other people. Emotions might be flying high, so be prepared to listen to others and help them deal with their problems instead of working on yourself.",
    },
    "king of cups": {
        "title": "The King of Cups is the fourteenth card in the Cups suit. Initially, as a King, you’d think the King of Cups is a mainly masculine card, but overall as Cups deal with emotions, it is quite a balanced tarot card. The King sits in a throne surrounded by water, holding a cup and a scepter in his hands.",
        "normal": "The King of Cups in the future position suggests you should actively look for somebody to help you along the way. A business partner or a friend to help with studying or general life issues. Look for someone older than you, especially if you’re currently in a rut. In the long term, the King of Cups can also mean a happily balanced life, full of intelligence and stimulation.",
    },
    "ace of wands": {
        "title": "The Ace of Wands is the first tarot card in the suit of Wands. It’s a positive card, if you’re in any sort of creative field then take it as an extremely good sign. As it’s an Ace, expect new beginnings, especially relating to creativity and that first spark of inspiration to set an idea in motion.",
        "normal": "The Ace of Wands tarot card in the future position can suggest a strong potential outcome, a life you are happy with if you’re willing to work for it. It isn’t about earning money, it’s about reaching your potential especially in a creative field. You have to give it your all, through a mixture of passion, applied talent and effort. If you have a goal in mind, you must start today. In a few years, you might be a completely different person. If you’re unsure of your current path, stop worrying. The beginnings of any venture are always tricky and you should at least see through the initial hardship before thinking about giving up. This can apply to all parts of life; careers, hobbies, relationships.",
    },
    "two of wands": {
        "title": "The Two of Wands is the second tarot card in the suit of Wands. Two is an important number in western esotericism, and regularly represents the duality of life. The Two of Wands refers to the potential of everybody for widening their own worldview, and that many limits are only self-imposed.",
        "normal": "The Two of Wands in the future position can suggest a strong, happy future life. You’ll feel as if you’ve got it ‘all worked out’. Remember to keep looking to the past to avoid mistakes. It’ll be helpful to work out what your past choices have done for you, and how to steer good choices back into your life and shun away bad ones.",
    },
    "three of wands": {
        "title": "The Three of Wands is the third card in the suit of Wands. A great card to see in a reading if there’s something you’re aiming for. The Three of Wands usually means you will attain your goals, through prior preparation and good foresight.",
        "normal": "The Three of Wands in the future position can suggest a strong potential outcome, a life you are happy with if you’re willing to work for it. It isn’t about earning money, it’s about reaching your potential. Be creative now, and you’ll open more doors for yourself in the future.",
    },
    "four of wands": {
        "title": "The Four of Wands is the fourth tarot card in the suit of Wands. A largely positive card, you should expect good things to happen when you see it, especially when relating to work and career or that project that you’re working on. It’s going to be a time to celebrate achievements, and relax now that the hard work is over.",
        "normal": "The Four of Wands card in the future position can have a few meanings. there might be a bit event coming up that you’re going to be a part of. If you follow the rules, everything will turn out fine, so you should stop worrying.  If you’re at work, you might have done something well enough to warrant a celebration.",
    },
    "five of wands": {
        "title": "The Five of Wands is the fifth card of the Wands suit. The Five of Wands is not a pleasant card and deals with conflict and sometimes aggression. The illustration shows five men fighting with wands, the victor, main aggressor or victim are all unclear.",
        "normal": "The Five of Wands in the future position suggests a period of time in the future when you’re going to regret what has happened. It can also suggest future conflict, sometimes unavoidable. What could possibly happen in future that could lead to conflict? Think about it now to prepare for the future. There is always going to be conflict and disagreement in our lives, no matter how relaxed and peaceful we are.",
    },
    "six of wands": {
        "title": "The Six of Wands is the sixth tarot card in the Wands suit. The card resonates success and is a positive omen.",
        "normal": "The Six of Wands tarot card in the future position means you should use your good memories of the past to set an example for your future. In ten years, do you still want to be looking back on those memories, or newer, fresher better ones that you’ve made since? If you see obstacles in your way, work methodically to eradicate them. There is nothing truly blocking you. The Six of Wands can represent a successful future. Visualise where you want to be in ten years and work towards it.",
    },
    "seven of wands": {
        "title": "The Seven of Wands is the seventh card in the suit of Wands. A positive card in some respects; especially relating to contests or competitions. The Seven of Wands is closely related to your willpower, and meanings will change based on how determined you are in life.",
        "normal": "The Seven of Wands in the future position suggests a long path of continued growth. Have you just started something new? Expect it to be an ever growing part of your life. This could be any aspect; a new job, relationship, hobby, friendship. Don’t feel as though the odds are stacked against you. If you’re overwhelmed, don’t get discouraged. Stop and try again.",
    },
    "eight of wands": {
        "title": "The Eight of Wands is the eighth tarot card in the suit of Wands. A completely enigmatic illustration for the Eight of Wands lends little initial help into even a sensible guess at its meaning.",
        "normal": " The Eight of Wands in the future position suggests a successful career or creation of something great and positive. It might be a case that you felt like you were just given a choice one day, out of the blue, and took it. It’s best never to make rash decisions, but it’s also just as bad to take too long to decide.  Acting quickly and acting on impulse are two different things. When you are presented with a choice in future, just spend a short time thinking. Weigh up your choices; how do they affect me, my friends, my family? Don’t overthink, consider the outcomes and go with your gut.",
    },
    "nine of wands": {
        "title": "The Nine of Wands is the ninth tarot card in the suit of Wands. The previous cards in the wands suit have been mainly positive with exceptions, but the Nine of Wands is where the meanings start to take a more cautious approach.",
        "normal": "The Nine of Wands tarot card in the future position can represent a fear of the future. We’re always afraid of what we don’t know, because we can’t accurately predict what it’ll do or how things will go. It’s just an aspect of life that we all have to deal with. Be careful not to live your life in a comfy bubble.",
    },
    "ten of wands": {
        "title": "The Ten of Wands is the tenth tarot card in the suit of Wands. As seen in the Nine of Wands, it isn’t as positive as early cards in the suit. The illustration shows a man burdened by the weight of ten wands. he can see his destination but has a long way to travel.",
        "normal": "The Ten of Wands in the future position is a bad omen Be sure you aren’t putting all your eggs in one basket, or setting up your life in a way that if one part of it fails, it all fails. Always have more than one backup just in case. Don’t think the near future is going to get easy through a quick fix. Work towards something you are passionate about, and set yourself goals to achieve. Hard work will feel even much worse if you feel like there is no escape.",
    },
    "page of wands": {
        "title": "The Page of Wands is the eleventh card in the suit of Wands and the first face card. As it is a face card, it could represent a real-life person, even someone that you know; likely a younger male influence in your life. The illustration on the Rider-Waite deck shows the Page inspecting a wand, well dressed and standing in front of a barren desert landscape.",
        "normal": "he Page of Wands tarot in the future position can suggest a new leaf, a completely new paradigm for your life. Don’t worry if you’re currently enjoying your life, it’s only going to get better. Expect an open, free future, where only your choices determine your actions. If you are particularly afraid of something, make a point to address this in a long term goal. A rewarding way to live life is to analyse your fears, and then adapt these into goals. The more you confront a fear, the more you will change the feeling of fear into the feeling of opportunity.",
    },
    "knight of wands": {
        "title": "The Knight of Wands is the eleventh card in the suit of Wands. The Knight of Wands, much like the Page of Wands, exists in a barren desert. He even dresses similarly, with a salamander motif, though unlike the Page, he is moving at speed. The Knight has decided his goal and is on his way.",
        "normal": "The Knight of Wands in the future position can suggest a life you are happy with if you’re willing to work for it. It isn’t about earning money, it’s about reaching your potential. You have to give it your all, through a mixture of passion, applied talent and effort. If you have a goal in mind, you must start today. You need to start taking more chances, start saying ‘Yes’ to things which are offered. If you’re not a people person, you’re really going to have to come out of your shell in order to succeed. Don’t rush this, it should come naturally as long as you try a little.",
    },
    "queen of wands": {
        "title": "The Queen of Wands is the thirteenth tarot card in the Wands tarot suit. It’s likely to signify a positive, mature female influence in your life; especially someone with a good career, who is independent and honest. Without even reading the meanings, you might already have an idea of who it may be. She should be the sort of person to whom you could go for advice on any number of topics in life. The black cat is a sign of luck.",
        "normal": "The Queen of Wands in the future can mean a cosy life in the future. Being open to the suggestions of others and not treating anything objective as ‘precious’ will lead you to work on and create great collaborations. If you haven’t already, work on setting a long term goal for your life, something you personally wish to achieve. It’s likely that this goal will have something to do with helping others with their problems; you might already have a solution to a problem and it just hasn’t occurred to you yet that this will greatly help others.",
    },
    "king of wands": {
        "title": "The King of Wands tarot card is the final card in the suit of Wands. The King of Wands embodies much of the meaning of the entire suit and should be taken seriously when seen. Much like the Queen of Wands, The King can represent a strong male influence in your life, somebody who has succeeded and lived their dream. You might find them quite inspiring. This could also represent you, having achieved your goals, meaning you are ready to help others with theirs.",
        "normal": "The King of Wands tarot card in the future position can suggest a strong potential outcome in your career. You’ll be happy with what you’re doing, especially if you’re concerned with, or work with money. You’ll need to take risks, but weigh them up and think about your past. Be prepared to help others as they come to you, but remember that you achieving your goals will help everybody in the long run. Prioritise the health and well being of yourself and others, but never lose sight of what you’ve always wanted to achieve in life.",
    },
    "ace of swords": {
        "title": "The Ace of Swords is the first card in the suit of Swords. All aces can mean a new start. Like a sword, the actions that bring forth this new change can act quickly and without warning. Aces regularly represent a new beginning, coupled with Swords, this suggests a new personal goal or worldview. You may see yourself coming out of your shell soon.",
        "normal": "The Ace of Swords in the future position can suggest a strong potential outcome, a life you are happy with if you’re willing to work for it. It isn’t about earning money, it’s about reaching your potential, especially in a creative field. Don’t rush into any schemes, but read about them. Learn as much as you can and act upon the information. The Ace of Swords regarding the future can represent a fun, active lifestyle, especially one where you’re constantly challenging and pushing yourself with new experiences.",
    },
    "two of swords": {
        "title": "The Two of Swords is the second tarot card in the suit of Swords. Two is a common number in esoteric study and understanding; balance, two halves of one whole, male and female, good and bad. This is a balanced card; not wholly about action itself, but more focusing on what to do with the information you have.",
        "normal": "The Two of Swords tarot card in the future position reminds you of your current state of mind and personality towards tough decisions. Its something you need to tackle soon or it’ll take over your life. You can spend forever thinking about the routes your life can take, but you don’t want to. All the time you spend thinking means you’re still at the crossroads and not on the journey.",
    },
    "three of swords": {
        "title": "The Three of Swords is the third tarot card in the suit of Swords. As you may have deduced from the illustration, the Three Swords is not a wholly positive card, especially when it comes to love.",
        "normal": "The Three of Swords tarot card in the future position can mean that your life is currently on a downward curve. You don’t need to keep doing what you’re doing, even if it feels impossible. Even if you think you’re at rock bottom, you have it within yourself to change your life. What were you worrying about 5, 10 15 years ago? Do you still worry about those things?",
    },
    "four of swords": {
        "title": "The Four of Swords is the fourth tarot card in the suit of Swords. The illustration shows the tomb of a knight in prayer, three swords adorn the wall and one is engraved on his tomb.",
        "normal": "The Four of Swords in the future position can mean that you’re going to have to do a lot of thinking in the future. You might be working towards something now, but soon you’ll need to consider what it is that you actually want, and start devising plans to achieve this. The opinions of others are always valuable, but you can’t keep getting told to do things, you need to interpret and think about things yourself. If you’re working hard now, then expect a well earned rest coming!",
    },
    "five of swords": {
        "title": "he Five of Swords is the fifth card in the suit of Swords. When you see the Five of Swords, you should prepare for some conflict to come into your life. It might not be something to be scared of, but life is about to get at least a little bit more difficult. Don’t worry, you can always see it through.",
        "normal": "The Five of Swords tarot card in the future position would initially seem like a bad thing, a conflict in future. Now that you know, you can prepare yourself for it. Analyse where potential conflicts could arise and stop them before they start. Think days in advance and try to understand the patterns that cause your life to go in the wrong direction. Is it when you talk about a certain topic with somebody or go somewhere at the wrong time?",
    },
    "six of swords": {
        "title": "The Six of Swords is the sixth tarot card in the suit of Swords. A more positive card than the most recent cards in the Swords suit; the worst is likely over and you’re ready for some change and growth in life.",
        "normal": " The Six of Swords tarot in the future position is extremely reassuring. It shows that no matter what, you will overcome future problems. This is a given, you might think, you’re still here despite facing many issues The six of swords in the future position should give you reassurance – no matter what happens you will persevere.",
    },
    "seven of swords": {
        "title": "The Seven of Swords is the seventh tarot card in the suit of Swords. The illustration is particularly apt here; your first thought is likely a good insight into what the card means. The cards usually symbolise the person receiving the reading, but in this case, it’s sensible to consider all possibilities. The important thing isn’t to jump to conclusions when you read the meanings below.",
        "normal": "The Seven of Swords tarot card in the future position suggests that the path you’re currently on will irk and bother some people. This doesn’t mean it’s the wrong decision by any means. If you understand how your plans may annoy others, look into tweaking them to make things easier for everyone, yourself included. There may be other ways to proceed in future which you haven’t considered yet. Don’t rush into something knowing that somebody will get hurt.",
    },
    "eight of swords": {
        "title": "The Eight of Swords is the eighth tarot card in the suit of Swords. The illustration is somewhat frightening; a blindfolded woman surrounded by swords. She doesn’t know what to do, but inaction also isn’t a good choice. There is a way out, but more likely than not it will be painful.",
        "normal": "The  Eight of Swords tarot card ask you to understand that life is just a series of trials. It’ extremely rare that a life is peaceful and without negative influence. You will always have to deal with things you’d rather avoid, but you can make each ordeal easier by keeping it relative and in proportion. You’re never alone, even if you think you are; the woman is blindfolded but not gagged.",
    },
    "nine of swords": {
        "title": "The Nine of Swords is the ninth tarot card in the suit of Swords. A largely negative card, the illustration shows a man awakening from a nightmare, filled with grief. Nine swords are suspended on the wall at his bedside. His blanket is a patchwork quilt of red roses and zodiacal symbols. The Nine of Swords is widely regarded as a ‘bad’ card to draw, but take your whole reading into account when you interpret it.",
        "normal": "The Nine of Swords tarot card in the future position suggests a life of worry and anguish if you continue down your current path. Try to identify aspects of your life which may be holding you back or making your life seem more negative. Nobody wants to be unhappy. If you’re doing something right now that you’re not enjoying, don’t hesitate to give your life a bit of thought. Is this a good idea, will it really pay off?",
    },
    "ten of swords": {
        "title": "The Ten of Swords is the tenth tarot card in the suit of Swords. Running with the recent trend of the suit of swords; the Ten of Swords is not overly positive. The illustration somewhat backs this up; a man lying motionless on the ground with ten swords in his back. The Ten of Swords is regarded as the most destructive and grim card in the deck, but consider your entire reading when you interpret meanings.",
        "normal": "The Ten of Swords tarot card in the future position suggests that the current path you’re taking in life will lead to your destruction. You may have to re-evaluate where you’re headed and drastically change your lifestyle if you want to achieve your goals. This may not affect only you, but others close to you. Consider if their lives are worth it too. You can always turn your life around if you don’t like where you are headed.",
    },
    "page of swords": {
        "title": "The Page of Swords tarot card is the eleventh card in the suit of Swords, and the first ‘face’ card. Just coming from the Ten of Swords, the Page of Swords is a step up in terms of positive energy. Face cards can stand for a real person in our lives, in this case possibly someone younger than the receiver of the reading but could as well be the person receiving the reading.",
        "normal": "The Page of Swords card in the future position can mean that you currently feel locked down and restrained.  We all want to be free. Sometimes, more often than not, you have to work for it. Don’t expect the benefits of changing your life to come without the related hardships. Acting quickly, and alone, might be in your best interest here, as you’ll be able to express your thoughts without them being clouded by others.",
    },
    "knight of swords": {
        "title": "The Knight of Swords is the 12th tarot card in the suit of Swords. A slightly more positive card, especially relative to the other cards in the swords suit so far. You should expect better things to happen when you see it, especially any news regarding a younger male you might know. Expect to receive good ideas if you’re stuck, or other good unexpected news.",
        "normal": "The Knight of Swords tarot card in the future position suggests that the near future will be structured and methodical. If this is what you want, stick to the plans you’ve set out. Sometimes, people can ask things of us that disrupt what we want to do, but it’s usually better to help others over yourself first. Plans should be changeable too, you can plan your life but you can’t control it.",
    },
    "queen of swords": {
        "title": "The Queen of Swords is in the Minor Arcana and is the 13th tarot card in the suit of Swords. Usually, the queen will represent somebody in your life, most likely a mature woman who is quick to anger. Without even reading the meanings, you might already have an idea of who it may be.",
        "normal": "The Queen of Swords in the future can represent what you are going to become. Wise, but not without empathy. You’ll have influence, but be approachable. This does bode well if you are entering work or another area of life where you’ll be a minority. Be prepared to stand out.",
    },
    "king of swords": {
        "title": "The King of Swords is the final card in the suit of Swords. The King of Swords embodies much of the meaning of the entire suit and should be taken seriously when seen. Much like the Queen of Swords, The King can represent a strong male influence in your life, someone with authority and power.",
        "normal": "The King of Swords in the future position symbolises the path you’re currently on; a life you are happy with if you’re willing to work for it. It isn’t about earning money, it’s about reaching your potential; somebody who is in control of their thoughts, able to make serious decisions and with a basis in honestly. You have the ability, determination and drive to reach your goals, this tarot card assures you that.",
    },
    "ace of pentacles": {
        "title": "The Ace of Pentacles is the first tarot card in the suit of Pentacles. A largely positive card, you should expect good things to happen when you see it. Pentacles represent material possessions and wealth. Pentacles in tarot are also sometimes called Coins. The pentacle itself is a well-known symbol with many meanings and interpretations in many faiths, notably Wicca. The Ace of Pentacles is well regarded as a favourable card to receive in a reading.",
        "normal": "The Ace of Pentacles tarot in the future position represents a material goal that will be achieved. A new house, car or similar. Imagine yourself climbing a mountain, there is a struggle but so long as you continue upwards you will reach the reward. People often say it as a joke, but you only fail if you give up. Persistence is key. The Ace of Pentacles is a great card to receive in a future position; as it resonates such happiness, you know that one day you will somehow ‘make it’ and feel fulfilled and achieved.",
    },
    "two of pentacles": {
        "title": "The Two of Pentacles is the second tarot card in the suit of Pentacles. Two is a common number in esoteric study and understanding; balance, two halves of one whole, male and female, ups and downs, good and bad. Generally, a positive card, the Two of Pentacles can remind us to respect the balance that our lives require.",
        "normal": "The Two of Pentacles in the future position represents a wholesome balanced life if you continue positively. You need to address your current problems for future growth. Imagine yourself in five, and ten years. How are you? Are you living the life you expected? Rarely do we actually live to follow our plans in life, but know that if you dedicate yourself, then you can at least live a happy, balanced future.",
    },
    "three of pentacles": {
        "title": "The Three of Pentacles is the third tarot card in the suit of Pentacles. A largely positive card, you should expect good things to happen when you see it, especially when relating to work and career.",
        "normal": "The Three of Pentacles in the future position can have a few meanings. You might create a good piece of work that will be much use to others and used as an example in your field. For example, you may be studying. Your current piece of work will be used as a good example. If you’re at work, you might redefine how things happen and come up with a more efficient way of doing things. Others will applaud you for this. In a professional sense, this is good news but also look to improve yourself personally. How can you become a better person? How can you become a person that people want to be? these are the sorts of qualities you should be aiming for, there is no reason to settle for anything less.",
    },
    "four of pentacles": {
        "title": "The Four of Pentacles is the fourth tarot card in the suit of Pentacles. A somewhat positive card, you should expect some good things to happen when you see it. Watch out though, it has specific meanings that you might want to be careful with.",
        "normal": "The Four of Pentacles tarot in the future position suggests a sense of security in the form of material goods and finances. On the earthly plane, you will be catered for. It’s time to look into what you really want to spend your time on this world doing. Look at the illustration on the card. The central character is standing on the Pentacles as well as holding one, and having one on top of his head. Financial wealth is his foundation, wealth is his property and wealth is in his thoughts. Do you want to be like this?",
    },
    "five of pentacles": {
        "title": "The Five of Pentacles is the fifth tarot card in the suit of Pentacles. A quick look at the illustration gives a quick overview of the card depicts two men in walking in front of stained glass window, both look seem to be facing adversity and it is not a wholly positive card. When it comes up in a reading, prepare yourself for news you hadn’t hoped for.",
        "normal": "The Five of Pentacles in the future position suggests a future struggle that you will overcome. If you continue your life how you’re currently living it, it may be worse off in the long run. Are you taking advantage of something that is helping you out now? It won’t last forever. Try not to bring others with you if you have any destructive habits.",
    },
    "six of pentacles": {
        "title": "The Six of Pentacles is the sixth tarot card in the suit of Pentacles. A more positive card than the most recent cards in the Pentacles suit; things are starting to look much more positive and also mature now. Expect to see things how they really are, and to understand how much of a positive change you can make in the world.",
        "normal": "The Six of Pentacles tarot card in the future position suggests that you’ll eventually reach the path you’re currently on. You might be focusing too hard on this goal and experiencing tunnel vision. If you want to, take a step back and think about if this is what you really want. It can suggest a future where you have achieved your own goals and are looking to help others. This is especially a good card if you’re looking for a career in this field; teacher, lecturer, researcher, etc",
    },
    "seven of pentacles": {
        "title": "The Seven of Pentacles is the seventh tarot card in the suit of Pentacles. A positive card from the minor arcana, you should expect good things to happen when you see it. The illustration shows a man growing crops (crops of Pentacles) and peacefully watching over them. He has put in the effort to nurture them to grow and is about to reap the reward of his prior hard work.",
        "normal": "The Seven of Pentacles tarot card in the future position suggests a long path of continued growth. Have you just started something new? Expect it to be an ever growing part of your life. This could be any aspect; a new job, relationship, hobby, friendship. Whatever it is, you should expect good things if you continue to dedicate yourself.",
    },
    "eight of pentacles": {
        "title": "The Eight of Pentacles is the eighth tarot card in the suit of Pentacles. A positive card, you should expect good things to happen when you see it; especially aspects relating to a creative industry, or a project or part of your life that you have worked extremely hard on and dedicated yourself to. A good card to draw if you are intent on learning a skill or trade which you have a lot of passion for.",
        "normal": " The Eight of Pentacles tarot in the future position suggests a successful career or creation of something great and positive. For example, you may create something that will change how people live for the better, or a new way of doing something that eliminates all the negative consequences. This is a great sign if you’re already working on something similar sounding. If you aren’t, then definitely look into how what you do currently can help others.",
    },
    "nine of pentacles": {
        "title": "The Nine of Pentacles is the ninth tarot card in the suit of Pentacles. Similar in appearance to The Seven of Pentacles with the plant imagery, but with stark differences. The illustration in the Seven of Pentacles shows a man resting after work and enjoying what he started a while ago, whereas the Nine of Pentacles shows a woman casually enjoying a garden, with no signs of labour, though a Falcon rests on her left hand.",
        "normal": "The Nine of Pentacles in the future position suggests a fairy tale ending. It’s a good card to see in the future position and should give you a sense of hope that everything will eventually work out. Think about that for a while though; do you think you’ll attain your goals and be happy, or later in life simply prioritise your goals? You don’t know where you’ll be in a few years time, but drawing the Nine of Pentacles suggests that your future will be bright, positive and fulfilling.",
    },
    "ten of pentacles": {
        "title": "The Ten of Pentacles is the tenth tarot card in the suit of Pentacles. It is a positive card in terms of material retention, don’t expect to be needy or in want of something you desire.",
        "normal": "The Ten of Pentacles tarot card in the future position suggests a future struggle that you will overcome, especially regarding finances. This is a good placement, especially regarding business, charity or general finance. Don’t expect things to go smooth, but expect a good outcome eventually.",
    },
    "page of pentacles": {
        "title": "The Page of Pentacles is the eleventh card in the suit of Pentacles, and the first ‘face’ or ‘court’ card. A largely positive card, you should expect good things to happen when you see it, especially in any areas concerning long term goals or progression. The Page of Pentacles in tarot readings grounds us in the ‘real world’, so that we can manifest our dreams as tangible goals to achieve.",
        "normal": "The Page of Pentacles in the future position suggests a struggle that you will overcome. It could be that you’re in a tough position right now, but be mindful of the gains that you’ll receive if you just keep up what you’re doing.",
    },
    "knight of pentacles": {
        "title": "The Knight of Pentacles is the 12th tarot card in the suit of Pentacles. A  positive card, you should expect good things to happen when you see it, especially any news regarding a younger male you might know. As you may expect, the card embodies some knightly qualities; things many of us would do well to aspire to.",
        "normal": "The Knight of Pentacles in the future position suggests that the near future will be structured and methodical. if you’re aiming for a goal, stick to the plans you’ve set out. Sometimes, people can ask things of us that disrupt what we want to do, but it’s usually better to help others over yourself first.",
    },
    "queen of pentacles": {
        "title": "The Queen of Pentacles is the 13th tarot card in the suit of Pentacles. Usually, the queen will represent somebody in your life, an older woman, who has a very comfortable life. Without even reading the meanings, you might already have an idea of who it may be. Many draw parallels between The Queen of Pentacles and the concept of Mother Earth; a nurturing feminine spirit that takes care of us if we take care of her.",
        "normal": "The Queen of Pentacles tarot in the future can mean a comfortable life in the future. You’ll achieve everything you want and spend your time enjoying yourself on smaller pursuits and with helping others. if you continue on your current path, you’ll likely be in a place mentally where you feel a lot of satisfaction and gratification by helping others. You aren’t going to worry about your current problems, in fact, they’re going to seem minuscule in the grand scheme of things. Expect others to look up to you, whether this is because you have achieved something great in life, or simply because you have a generous personality and attractive qualities.",
    },
    "king of pentacles": {
        "title": "The King of Pentacles is the final tarot card in the suit of Pentacles. The King of Pentacles embodies much of the meaning of the entire suit and should be taken seriously when seen. Much like the Queen of Pentacles, The King can represent a strong male influence in your life; likely somebody who is well off in a material sense.",
        "normal": "The King of Pentacles tarot card in the future position can suggest a strong potential outcome, a life you are happy with if you’re willing to work for it. It isn’t about earning money, it’s about reaching your potential. You have to give it your all, through a mixture of passion, applied talent, and effort. If you have a goal in mind, you must start today. Expect good things if you are looking to start a business.",
    },
}
