love_deck = {
    "the fool": {
        "title": "It might sound bad from the name, but The Fool tarot card is not a negative card at all! In fact, it’s associated with the number zero – the number of infinite potential. In the Major Arcana, The Fool represents you, the main character,  journeying through life. So, when The Fool shows up in your reading, get ready for major change and transformation! The Fool tarot card is all about living in the present moment and enjoying your life without worry. Just look at how happy the man in the card is in spite of his treacherous surroundings. Sometimes we need to take a little risk, even if we aren’t sure how things will turn out, because, if we never try, we will never know what could have been! The Fool reminds you to stay true to your heart and follow your dreams.",
        "normal": "The Fool tarot card has appeared in your tarot reading to tell you to be spontaneous, take a risk, and follow your heart in love! If you’re single, this card is a sign of a new beginning, so stay open to possibilities! You may be crossing paths with your soulmate at any moment. If you’re in a committed relationship, your love will probably be going to the next level or undergoing a necessary change. Don’t let fears stop you. Go ahead and plan that romantic getaway or put yourself out there so you can find that perfect relationship. The Fool is telling you that the time is right!",
        "reversed": "Put yourself out there if you’re looking for love! The reversed Fool reminds you that you can’t find your soulmate sitting at home. Approach your love life with childlike optimism and fun!"
    },
    "the magician": {
        "title": "You’ve got what it takes to make it happen! That’s the general message of The Magician tarot card. With diligence and focus, you can create anything you desire, but you have to be deliberate in your actions and choices. Use your willpower and don’t underestimate your own abilities. Sometimes we don’t realize everything we have available to us. The Magician encourages us to have confidence and to be resourceful.",
        "normal": "Whether you’re looking for love or wanting to bring your relationship to the next level, The Magician is urging you to have faith in yourself and your dreams. You can create the relationship you want by being honest with yourself about your needs and staying true to your heart’s desire. Remember what you are bringing to the table in your relationship. With emotion, creativity, intellect, and abundance, you have the magic ingredients for the kind of true passion and commitment you deserve.",
        "reversed": "Are you in a new relationship? Things may not be as they seem. The reversed Magician represents manipulation and deceit. Be sure to pay attention to any red flags and make sure that actions match words. On the other hand, it might be that you’re not utilizing everything you have at your disposal to manifest love in your life."
    },
    "the high priestess": {
        "title": "The High Priestess is the guardian of your intuition, indicating that it can be a powerful indicator that you will need to trust your feelings when it comes to love and romance. Difficulties can develop when you ignore your intuition and follow only your conscious mind",
        "normal": "If you are currently single, you might be surprised to discover some things happening behind the scenes. The High Priestess is a card of mystery and intense emotion and in Pagan tradition, The High Priestess herself is a symbol of fertility, sexuality, and the union of the physical and spiritual. You may discover hidden passions or surprising connections. Follow your heart rather than your mind if a conflict arises, and opt for listening rather than confrontation.",
        "reversed": "Are you hiding your true self from your partner? Are you hiding your true desires from yourself? The High Priestess in reverse represents hidden information in your romantic relationship. Whether they are your true feelings or those of your partner, take time to listen to your inner voice, and let it guide you."
    },
    "the empress": {
        "title": "It’s time for you to stop and smell the roses! The Empress takes the time to enjoy and appreciate all of the finer things in life, and she’s appearing in your reading to remind you to do the same. She is Venus, the ruler of love, art, and beauty, and represents fertility of all kinds. Whether your reading is about romantic relationships or your career, the message of The Empress is to bring your creative ideas and pursuits into the physical world. But, if she’s showing up in the reverse, it might be that you’ve gone too far into luxury and enjoyment! A reversed card always means that the qualities of that archetype are too extreme. In reverse, The Empress suggests that too much of a good thing can lead to laziness and co-dependence.",
        "normal": "Get ready for something serious! The Empress is a nurturing and loving archetype, who is associated with fertility and pregnancy. If you’re in a committed relationship, things are probably going to rise to the next level! Children and family are indicated with this card, and this major arcana card represents a partner who is stable, caring, and beautiful, and loves the finer things in life. If you’re single, it’s likely that you’re going to be meeting someone new, perhaps even from work. The two of you will share creative passion and enjoy some luxurious moments together.",
        "reversed": "It looks like your romantic relationships have gotten out of balance. Either you’re with a partner who is too smothering and clingy, or they’ve become detached and superficial. A reversed Empress advises you to check in with your partnerships. Are you over-giving? Or maybe you’re taking your relationship for granted? It’s a good opportunity to spend some quality time with your partner and communicate with each other. Go the extra mile to bring balance back into your relationship!"
    },
    "the emperor": {
        "title": "The Emperor uses power and organization to accomplish his goals. He is wise and powerful in his ways, and in the upright, can act as a protector. This card in your reading can represent your current energy, or can also represent a boss, father figure, spouse, or system of authority that is prominent in your life. When he appears in the reverse, The Emperor is tyrannical. He is overly rigid, lacks empathy, and won’t think twice about using force to get what he wants, even at the expense of others. The energies of this Major Arcana card are a powerful influence for good or for bad.",
        "normal": "The Emperor isn’t the most romantic of cards to get in a love reading, but he does bring a sense of stability and common sense. It’s a relationship led more by the mind than the heart, so romance won’t be at the top of the agenda. However, The Emperor is long term and traditional.",
        "reversed": "You might be in for some power struggles in your romantic life. The Emperor in reverse is stubborn and rigid and can lack empathy. If you’re in a new relationship, be careful that it doesn’t develop into something that is domineering and controlling. This archetype can symbolize a person that is driven by their ego who tends to bully others."
    },
    "the hierophant": {
        "title": "Sometimes The Hierophant is referred to as The Pope of the priest of the Major Arcana. The Hierophant mirrors The High Priestess in the same way that The Emperor mirrors The Empress. This Major Arcana card is a masculine card representing structure and tradition but is focused on the spiritual realm. He is a card of religious doctrine, which values faithful devotion to traditional religious practices as a means of reaching spiritual fulfillment.",
        "normal": "You’re on a path toward spiritual love when this Major Arcana card pops up in your tarot reading. You will be attracting a traditional relationship that is stable and spiritually guided. The Hierophant can also indicate marriage, so if you’re in a committed relationship you might just be taking it to the next level!",
        "reversed": "A reversed Hierophant card indicated that your relationship has become stagnant and maybe your values don’t really align. With different world views and beliefs, it can be challenging to make a relationship flourish. Not all of the love advice that you receive right now will be helpful. Tune into your own heart and intuition for answers."
    },
    "the lovers": {
        "title": "The Lovers card has landed in your tarot card spread to signify a beautiful relationship in your life! There is clear communication and an ability to be vulnerable with one another. This card often signifies a sexual relationship, though it doesn’t have to be. This Major Arcana card also represents choices. It seems that an important decision will be coming up in your life, so the surrounding cards of the reading will be very important!",
        "normal": "When it comes to romance, The Lovers card is like hitting the jackpot. Unity, passion, and love await you and a soulmate connection might really be at hand. But just like with all important decisions, the choice you make will impact your life in a big way. Be honest and clear with yourself and others about your needs and expectations. This kind of trust and vulnerability is the foundation of any lasting union.",
        "reversed": "If you’re single and this Major Arcana card presents in the reverse, you should take a moment to see if you’re standing in your own way when it comes to love. Sometimes unconscious programming leads us to self-sabotage without us even realizing it! If you’re in a relationship, be sure to assess your real happiness. Do you truly feel loved and connected?"
    },
    "the chariot": {
        "title": "The Chariot represents overcoming obstacles after a long journey or hard-won battle. Depending on where this tarot card appears in your reading, the message is one of maintaining focus and confidence in the pursuit of your goals. The Chariot card suggests that your strength and commitment is being tested by the universe, so don’t give up or look for shortcuts. Are you pushing yourself ahead at break-neck speed to the point of obsession? This might be why The Chariot is showing up in the reversed position in your tarot card reading. If the pursuit of victory is becoming excessive, you might actually be standing in your own way. If you’re lacking direction and feel yourself floating aimlessly, a reversed Chariot card will also appear in your reading. Whether your willpower and focus is excessive or lacking, the goal is the same: bring these energies into a healthy state of balance.",
        "normal": "You’re taking your love life into your own hands! With passion and confidence, you are moving toward what you want in love. When you are clear about your goals and desires, you can take concrete action toward manifesting what you want in a relationship. Remember though, that The Chariot represents duality and the need to rein in opposing forces. But with a little juggling and balancing, you will succeed.",
        "reversed": "If you’re being too pushy or forceful in love, you’ll wind up self-sabotaging your relationships. The energies of the Chariot in excess don’t bode well for a harmonious relationship. Instead of trying to control everything, practice surrender. Find balance in your life in terms of your career and friendships and let love come to you."
    },
    "the justice": {
        "title": "You can expect a fair outcome to a challenging situation in your life! If you have acted with integrity toward others but you have been wronged or hurt, the Justice card assures you that karma will be brought back into balance. However, if you have made decisions that harmed others, the Justice card comes as a warning. Justice demands truth and honesty, so a reversed Justice card indicates gossip, misinformation, and lies. You may have behaved in ways that were morally questionable and you are failing to take responsibility for your choices. Be fair in your choices and be sure to seek out the facts before making any judgements or assumptions about others, and make an effort to right the wrongs you committed before Justice does it for you.",
        "normal": "Justice is bringing balance to your love life!  If you’ve been creating good karma through honest and fair actions, then you will be attracting the same to you. Your love relationships will be like your mirror. If you are single, it’s likely that a new relationship is coming your way.  If you’re already in a committed relationship, balance is about to be restored.",
        "reversed": "Unfairness seems to be a theme in your relationship right now.  Are your expectations fair and reasonable? Are your partner’s? Do the facts of the situation really warrant any negative feelings either of you might have?  Or maybe one of you is making unfair judgements that are unwarranted. Whatever the details of your situation, it’s time to take responsibility before karma does it for you."
    },
    "the hermit": {
        "title": "The Hermit is the soul searcher and is here to encourage you to reflect on your deepest feelings and needs. The appearance of this Major Arcana card in your tarot card reading heralds a time for pause. There is often a major turning point around the corner. A new path may be opening to you that you have been unable to see because of the noise and distractions in the outside world. Sometimes life forces us into retreat and sometimes it’s by choice, but either way, it is from the darkness that we find the light. When the energies of The Hermit are out of balance, he will present in your reading in the reversed position. This can indicate escapism rather than self-reflection, or a resistance to looking within for answers.",
        "normal": "You seem to be growing apart in your relationship, and in spite of your efforts, or the efforts of your partner, the distance between you only grows. This might be causing you some loneliness and sadness, but The Hermit invites you to focus on yourself and your own needs and desires. Reassess what qualities are important to you in a relationship so that you can build a strong foundation for a loving relationship in the future.",
        "reversed": "If you are single, The Hermit indicates that you need to spend more time developing your own sense of self before you can fully commit to a romantic partnership. Take the time to work on your self-love and determine clearly what your needs and expectations are."
    },
    "the wheel of fortune": {
        "title": "Fate and destiny are about to kick in so get ready for some major changes. This can apply to your romantic relationships, career, health, or any other subject you are delving into with your tarot card reading. Our lives are made up of a series of cycles, and The Wheel of Fortune makes an appearance when one cycle is about to end so that another one can begin. One thing we know for sure is that things always change. The Wheel of Fortune is generally associated with good luck, but if it appears in the reverse, it’s suggesting that you’re resisting change. Or maybe you’ve got yourself stuck in an endless cycle of repeating patterns. Sometimes even “bad luck” leads to positive change, we just can’t see it until afterward.",
        "normal": "Are you single right now and looking for love? Well, the Wheel of Fortune is about to bring a big transformation into your life. An old karmic cycle is ending and a new cycle is beginning, so if you have been solitary, you might just meet that someone special in the near future. If you’re already committed, your relationship will be put to the test. This can be a great opportunity to strengthen your bond as you face challenges together. Change brings realizations and opportunities, so look for new doors opening.",
        "reversed": "Your love life might be feeling like it’s spinning out of control when The Wheel of Fortune presents in your tarot card reading. There are external events that are affecting your relationship and there is no point in trying to control it. Rather, remain flexible and look for opportunities in change."
    },
    "the strength": {
        "title": "The Strength card follows The Chariot in the Major Arcana series. After we learn to use our strengths externally to overcome the stumbling blocks on your path, we must also learn more compassionate and refined ways of achieving our goals. The lesson of the Strength card is that we do not need to control others in order to succeed. We can rely on stamina, patience, and understanding to maintain harmony and balance in our lives.",
        "normal": "Your love life forecast is full of passion and fiery romance! The Strength card in romance indicates a strong partnership that has a solid foundation in empathy and compassion. This allows you to really understand each other’s needs and vulnerabilities. A really close and deep bond can evolve from this energy.",
        "reversed": "But wherever there is intense passion there is a risk of explosive emotion! A reversed Strength card warns you to be on the lookout for fits of jealousy or anger. There could be a power imbalance where one partner becomes domineering and the other submissive. Be careful not to play into a codependent relationship. Be sure that both parties are coming from a place of empathy and compassion, and try to approach conflicts with patience and understanding."
    },
    "the hanged man": {
        "title": "Are you trying to control things, but you’re not getting the results you want? It’s time to take the advice of The Hanged Man. This tarot card tells you to take a pause so you can gain a new perspective on your situation. This card is all about choosing to surrender to the flow of the universe. You received this card in your tarot card reading because there is some situation in your life that you need to respond to in a new way.",
        "normal": "It might seem like your relationship is stuck or things aren’t moving forward the way that you want right now. Receiving this tarot card in your love reading means you need to embrace this pause to find the good in it. It’s natural for us to want things when we want them, but we need to recognize that the universe has a bigger plan. Trust that this slow down is for the best, and try to learn as much as you can about yourself during this time. Use this time to work on yourself. We attract and reflect our inner shadows in our relationships. Are there other areas of your life where you might be causing a block?",
        "reversed": "It’s time to take action in your love life because the waiting period is finally over! You already know what you need to do. If there is a decision or action you’ve been stalling on, it’s time to move forward."
    },
    "the death card": {
        "title": "The Death card of the Major Arcana is symbolic of endings, allowing a chapter of your life to “die” so that a new one can begin. It’s not always easy to let things go. Accepting endings can be painful. But it is important to remember that what is in store for you is likely to be even better than what you are leaving behind. Everything in the world works in cycles, so embrace the endings so you can look forward to the new.",
        "normal": "Your current relationship is about to go through a major change and maybe even an ending. If you are being honest with yourself you probably already know that your relationship isn’t balanced or fulfilling. Why are you remaining attached to something that isn’t flourishing? Be willing to release codependent tendencies and have the courage to walk away from unhealthy dynamics. The change will open the door to true happiness. If you have been single for a long time, you may be finding that coming to an end.",
        "reversed": "In reverse, you’re being advised not to resist the change! Don’t stay in unhealthy relationships out of a fear of being single, and don’t stay single out of a fear of love! Change is coming and the best possible thing you can do is remain open to what comes your way."
    },
    "the temperance": {
        "title": "On The Fool’s journey through the Major Arcana, The Temperance card comes up after the Death card. It’s often the painful things in life that become our greatest teachers. When life asks us to let go of something that is very important to us, we begin to learn non-attachment. Temperance has discovered that adaptability, trust in the universe, and moderation brings us the greatest peace. When we surrender to the flow of the universe, we can begin to live an enlightened existence.",
        "normal": "In romance, the Temperance card represents the energies of harmony, balance, understanding, and patience in your relationship. Are there ways in which you can approach your relationship with more calm and generosity? Or maybe you aren’t speaking up enough? Either way, the Temperance card counsels finding the middle road. If you’re currently single, Temperance advises not jumping into new relationships too fast. Be patient and allow things to grow.",
        "reversed": "Are your standards too extreme for a healthy partnership? Maybe you’re in an all or nothing situation? The Temperance card in reverse advises you to take a step back to evaluate your relationship. Make sure that you and your partner are in an equal give and take situation, and if not, take concrete steps toward that."
    },
    "the devil card": {
        "title": "It’s easy to lose sight of the fact that nobody else is responsible for our happiness and that no matter how hard we try, we can’t find happiness in the external world. This is how addictions and attachments develop. The Devil card exposes our tendency to shift responsibility, whether it’s by adopting the victim mentality or by numbing ourselves with carnal pleasures. Until we learn to generate happiness from within, we choose to remain chained, so to speak.",
        "normal": "The Devil is not a favorable card to have in a love reading. It indicates energies of self-gratification, lust, disregard for a partner’s feelings, and possibly even obsession. Basically, this Major Arcana card is the hallmark of a toxic relationship. On a more superficial level, a relationship that is simply based on sex is not a bad thing, as long as both parties are in agreement. But when these energies become more extreme, it doesn’t bode well for an intimate union.",
        "reversed": "You may be feeling like you’re finally gaining a sense of control over your place in your relationship. The Devil in reverse indicates walking away from unhealthy love relationships. It’s a breaking away from the chains and opting for healthy self-reliance."
    },
    "the tower": {
        "title": "In its essence, The Tower represents a groundbreaking change. It doesn’t always foretell chaos and destruction, though by the look of the card you might think so! Lighting strikes a stone tower and people are jumping from the windows to escape the flames. This card follows The Devil card in the Major Arcana, and the message is clear: do not resist change or the universe will force it upon you.",
        "normal": "In romantic relationships, The Tower comes along to give you the extra push you need to take a difficult leap forward. If your relationship is built on a weak or rocky foundation, expect that your commitment is likely to be swept away in favor of something better that will come along in the near future. If you are currently single, you will be undergoing a profound transformation regarding your perspective on love.",
        "reversed": "The reversed Tower is advising you to deal with any foundational issues in your relationship now before the problem gets worse. If you can see a complete change in direction as an opportunity instead of resisting inevitable change, then the energy of The Tower card won’t be quite as challenging as it could be."
    },
    "the star": {
        "title": "You’re wishing upon a star when this Major Arcana card makes an appearance in your tarot card reading, and the good news is that your wishes are about to come true! Will it be new love, or taking your relationship to the next level? The energies of hope and faith surround you and are supporting you in a brand new path or direction. You have a lot to be optimistic about because the universe is blessing you at this time.",
        "normal": "The romance of your dreams is before you and The Star card asks you to allow yourself to heal completely by letting go of any past hurts. Only then can the universe will bless you by fulfilling your dreams. If you are single, your radiant optimism is making you magnetic, and you will attract someone equally charismatic. If you are in a relationship, this will be a time of healing past wounds and rejuvenating your partnership.",
        "reversed": "Are you swept off of your feet by something? Are you ignoring the signs? Do you have that little voice in the back of your mind telling you to be careful of something, but you don’t want to listen because you are caught up in the moment? The Star in the future is warning you that if you allow yourself to get caught up in dreamland, you might be in for despair and hopelessness in the future, when things turn out differently than they seemed they would. Do you feel like you’re in a rut? If you’re single and feeling really down on your luck, like you’ll never find your soulmate, remember that you attract what you embody! Tune into your innermost wishes and reconnect to your hope. Your optimism and positivity will bring love into your life. If divine love is what you’re dreaming of, you need to bring yourself up to that level. Only then can you attract someone with that energy!"
    },
    "the moon": {
        "title": "When times are uncertain, we often begin to feel afraid or anxious. The Moon card represents a time of the unknown where we might feel out of control. But rather than hiding or running from the shadows, take the time to listen to your intuition. Whatever is revealed to you will only serve you in the end. When we discover things that are hidden beneath the surface, we can take action to better our environment.",
        "normal": "Your love life may be a little emotional and confusing right now. The Moon card indicates that there are emotions welling up to the surface that may not be fully understood or communicated properly at this time. Don’t take everything at face value right now. Listen to your intuition and let things take their course. The moon will illuminate everything in due time.",
        "reversed": "Be sure not to confuse intense emotions for true love right now! If you’re newly involved with someone, The Moon in reverse is putting you on guard that your person may not be what they seem. Is someone is presenting themselves as your true love or soulmate? But do you feel deep down that it may not be genuine? Wait to see if their actions match their words. If you feel confused and unsure, be sure to wait for reliable information. On the other hand, don’t let paranoia and anxiety poison your situation. Take a deep breath and go with the flow at this time. Allow for the hidden to be revealed to you in its own time."
    },
    "the sun": {
        "title": "Positive energy is all around you sending warmth and confidence to all that you do. Just like the sun in our sky makes the plants grow and gives us light and warmth, The Sun card of the tarot is also representative of the source. It comes toward the end of the Major Arcana after The Fool has made his journey through many obstacles and challenges. All of these trials have made the querent a better person because he now knows how to live in the light.",
        "normal": "Your love life is on fire! If you’re currently single, it’s time to step out there and let yourself shine. You’re magnetic to those around you and your energy is definitely going to draw attention. Because The Sun card also represents harmony and joy, you are likely to attract someone warm and well-suited. If you’re currently in a relationship, your partnership is going to blossom. You are growing closer to one another and are both feeling fulfilled and happy.",
        "reversed": "A reversed Sun card reminds you to stay positive and joyful when it comes to love and romance. You won’t meet your soulmate sulking at home! Step out with a positive attitude and have confidence in yourself! Don’t pretend to be something you’re not and don’t hide away either. With optimism and vitality, you are destined to attract that perfect relationship into your life."
    },
    "the judgement": {
        "title": "When we undergo a spiritual awakening we realize that the answers are always within us. Others who judge us are merely projecting their own fears and insecurities on us and the same is true when we judge other people. Judgements come from a place of fear and we erroneously think that if we reject what makes us feel uncomfortable we will somehow be safe from it. The Judgement card asks us to look within ourselves instead, so that we may be freed from past beliefs and choices and live our lives with grace.",
        "normal": "A renewal of love may be in store for you if you are in a relationship right now. However, you must have the courage to address issues between you and your person with compassion and honesty. If you’re single, it’s time to honestly reflect on your past choices and what was motivating them. Allow this time to usher in the changes that will prime you for a beautiful soul connection with the love of your life. If you’re in a partnership, The Judgement card indicates that your relationship will be faced with a very important choice that will have long-lasting effects. make the effort to work together and communicate clearly and honestly. Then your relationship will blossom. If you are single right now, The Judgement card is asking you to do the same for yourself through acts of self-love and self-respect. You will attract true love into your life when the new chapter begins.",
        "reversed": "Your relationship may be on the rocks when The Judgment card presents in the reverse in your love reading. Are you still carrying baggage from past relationships? Are there lessons you failed to learn? There is still time to make changes! But you must be honest with yourself and accept responsibility where it is yours and forgive yourself where you are still holding onto regret. You must release these negative energies to find a true love connection."
    },
    "the world": {
        "title": "You feel like you’re on cloud nine right now because your life is in perfect alignment with your innermost dreams and desires. You successfully completed your journey through the 22 cards of the Major Arcana, each one of them carrying a profound lesson with accompanying challenges. All of these obstacles were your training ground and the final card, The World, marks your arrival! You learned to trust the universe as well as yourself, and you learned to surrender when needed. You learned to use your intuition and control your passions.",
        "normal": "When it comes to your love life you have arrived at a place of joy and fulfillment. Everything that you have been hoping for and working towards is now at your fingertips. If you are in a relationship, you have built a stable bond that is fulfilling and harmonious. This accomplishment is also opening the door to a new chapter in your life, which could involve taking your romance to the next level. This could mean marriage or children, or whatever it may be that you have been dreaming of. If you’re currently single but looking for your soulmate, you’re about to find the one. You have done the work of bringing yourself to a healthy place of self-reliance, trust, and balance, and you will attract someone equally harmonious into your life.",
        "reversed": "In the reverse, The World card is telling you that you just have one last thing to figure out! Dig deep to find out what that hiccup is so that you can move forward with this new chapter in your life. You are almost there, but it feels like something is still missing. Are you missing something wonderful that your partner has to offer? Or is there some old baggage that is still holding you back? Take a moment to reflect and let go of anything that is holding you back so that you can enjoy your new life"
    },
    "ace of cups": {
        "title": "The Ace of Cups is the first card in the suit of Cups. A largely positive card, you should expect good things to happen when you see it. Cups represent emotions, and so the Ace of Cups tarot card can represent a beginning of emotions, think new relationships, friendships and connections. Cups represent our feelings, over our logical thoughts.",
        "normal": "The Ace of Cups tarot card in romance is a very good sign. Things will feel ‘new’ again. Do you want to be single? Do you want a new level of relationship, or a new relationship altogether? Any choice is possible. Many things that happen in new relationships seem like a big deal at the time, but when you really think over it, it’s nothing. Don’t blow things out of proportion. If you’re in a committed relationship, there may be a change for the better, you might find a new side to your partner, or they might find something out about you. as a couple, this will make you grow stronger together. Don’t be shy, share with those close to you.",
    },
    "two of cups": {
        "title": "The Two of Cups is the second tarot card in the Cups suit. The Two of Cups shows a man and woman staring into each other’s eyes, gaze fixed over two large cups. The duality symbolism is clear; male and female on opposite ends of the card. The winged staff of the caduceus represents a mythic chimera; possibly something is amiss or unknown, although this does not signify deceit or lies.",
        "normal": "The Two of Cups tarot in romance is a good sign if you’re already in a romantic relationship. You should be in a plateau; just relax and be yourself. Don’t force anything, this is the good part; you are both happy and content with each other, try to make this last as long as you can. If you are single, then simply look to strengthen your existing relationships. Share your emotions in both cases, the joy of a relationship is that you share an experience, it can mean so much more than going through life alone.",
    },
    "three of cups": {
        "title": "The Three of Cups is the third tarot card in the Cups suit. The card shows three people meeting, celebrating with cups held to the sky. A bounty of fruit and vegetables are by their feet. The scene is representative of a harvest festival ritual celebration, and gives off a good feeling. The Three of Cups is a good card to draw in almost any position.",
        "normal": "The Three of Cups in romance is a good sign generally. Be wary that this card can also signify a birth. Are you trying for a baby? If so, it’s good news for you! It’s possible you might reconnect with an old romance during the near future. It can be that you’ve both grown since you last knew each other, and circumstance could be that you’re right for each other again.",
    },
    "four of cups": {
        "title": "The Four of Cups is the fourth tarot card in the Cups suit. The image shows a man sitting under a tree, intently looking at three cups. An arm protruding from a cloud is offering him a fourth card, which he is either ignoring on purpose or just cannot see. Not a wholly positive card, but not bad either, the Four of Cups can represent a mind that is sometimes so focused that it misses the bigger picture.",
        "normal": "The Four of Cups tarot in romance can mean a few things. Make sure nothing is hidden. Has something happened recently that you’re thinking about? You might not be seeing the full picture, there could be a key thing missing. If you’re single and looking for someone; it could mean that there’s just one little thing wrong about how you’re presenting yourself. Ask others for advice, try not to cut anyone out, and contemplate from all angles.",
    },
    "five of cups": {
        "title": "The Five of Cups is the fifth tarot card of the Cups suit. Taking a darker outlook, the Five of Cups is one of the negative tarot cards. The central character, clad in black faces three overturned cups, representing failure. Behind him are two upright ones. There is a certain positive aspect, not all is lost, but right now he is failing to see it.",
        "normal": "The Five of Cups tarot card in romance is a not a good sign. Things are taking a downward turn. You need to give yourself time to analyse the situation fully. Are you at fault? You can’t do worse than telling the truth. Is it your partner? You might need to think about the relationship as a whole and see if it can continue further. Remember that saints need sinners. Good implies bad.",
    },
    "six of cups": {
        "title": "The Six of Cups is the sixth card in the Cups suit. The children suggest it’s a look back to childhood. The cups are not being used for their intended purpose, but inventively being used as a vase for flowers. A pleasant positive card which brings back warm memories of the past.",
        "normal": "The Six of Cups in romance is a mixed blessing. You might have gone through the honeymoon period of a relationship and things are starting to calm down. Focus on the future and where things are going, using the past as a foundation. If you’re single and looking, look to your past. There might be somebody there who is right for you. Try to keep things simple for now. The love of a child is simple. Meet new people, have fun with them.",
    },
    "seven of cups": {
        "title": "The Seven of Cups is the seventh tarot card in the suit of Cups. The card is all about choices. The character is having a vision of 7 cups offering 7 different gifts and is having trouble deciding. One of the choices is different from the others; an objected veiled in a cloth. We can interpret this as viewing the future and the clouded choices that we make based on appearance and assumption instead of fact.",
        "normal": "The Seven of Cups in romance suggests there might be more than one romantic choice for you in terms of partners. Again, weigh up the options. The card is all about making a choice. What someone is presenting to you might not be how they actually are. Whichever choice, take it slowly. If you’re in a relationship, you might have the choice of something to further deepen it, or a new experience to share. Again don’t rush it, make sure all the details are worked out.",
    },
    "eight of cups": {
        "title": "The Eight of Cups is the eighth card in the Cups suit. The illustration shows a man walking away from a river, on the other bank are some cups stacked irregularly, leaving a large visible gap. Heading away, the man is abandoning his cups, the structure they created left unfinished.",
        "normal": "The Eight of Cups in romance is a sign that your current relationship status might come to an end. Whether you’re single or committed, consider the opposite. Like the other points, is this really you? Do you really want this type of relationship? You might not feel like it’s right. Is this relationship good for you, or your partner? If you’re having fight after fight, then it might be best for both of you to leave it. This might not be a permanent break, notice how in the illustration, the man leaving the cups has not ruined them. It could be that he is off on a search for a solution.",
    },
    "nine of cups": {
        "title": "The Nine of Cups is the ninth tarot card in the Cups suit. A positive card generally, the illustration shows a character sitting in front of a collection of nine cups, proudly on display. His big grin and folded arms give us a sense of completion; he has achieved.",
        "normal": "The Nine of Cups tarot card in romance shows now is a good time to meet a prospective partner. Your confidence is going to be high and you’ll have much to talk about. Don’t be overly smug about it. Achievements are good conversation starters but don’t hang on to them for too long. Delve deeper, you could have a relationship to be proud of if you can put the effort in with the right person.",
    },
    "ten of cups": {
        "title": "The Ten of Cups is the tenth tarot card in the Cups suit and is an extremely positive card. The illustration shows ten cups suspended in a rainbow with a couple, likely married, looking at it. Children play in the foreground and an idyllic village lays in the background. The Ten of Cups is all about happiness and being positive.",
        "normal": "The Ten of Cups in romance is a good sign if you’re in a committed relationship. Expect marriage, or at the very least a growing commitment. If things are going well, then they should continue to. Relax and enjoy the moments, that is what this card is all about. If you’re single, see your next relationship as a potential serious long term one.",
    },
    "page of cups": {
        "title": "The Page of Cups is the eleventh tarot card in the Cups suit. The illustration shows a young man dressed in blue, holding a cup in his right hand. A fish is looking out of the cup at the man, and he is looking back. The card shows the innocence and curiosity of our inner child, as well as large imaginations unrestricted by logic or experience. Like many cards in the Cups suit, it’s a positive one. Fish emerging from water could be a symbol of knowledge being imparted, much like Oannes of Sumerian mythology",
        "normal": "The Page of Cups in romance can mean that you should look for someone younger than you if you’re single. Is your current partner younger than you? Someone might come along soon that you become completely enamoured with. Expect surprises or a certain change if things have been stagnant for a while, whether single or currently taken. It might be time for you to express your emotions, especially if you’ve been holding back. This could mean confessing to a crush, or telling your partner how you feel if something has been bothering you. There could be somebody from your childhood, or younger years, who is now very suitable for you which is good news!",
    },
    "knight of cups": {
        "title": "The Knight of Cups tarot card is the twelfth card in the Cups suit. The Cups are a positive suit, and the Knight of Cups is no different. With slight romantic undertones (think of the traditional Knight saving the Princess), the Knight of Cups is all about good news, and positive change.",
        "normal": "The Knight of Cups tarot card in romance is a good sign if you’re about to propose, or waiting for a proposal. Expect the outcome you want. Not much more can be said. Think about the nice aspects of your partner. If a proposal isn’t on the cards, then expect a deeper one than the current level of commitment, even if this is just a good deep conversation with your partner. If you’re single, then it’s up to you to embody the Knight of Cups and let your prospective partner know how you feel. You may feel regret if you propose something and you are rejected, but you will soon recover. The real regret comes when you do not put anything forth. Any decision you think about for too long will simply be made for you.",
    },
    "queen of cups": {
        "title": "The Queen of Cups is the thirteenth card in the Cups suit. Thirteen isn’t really an unlucky number when it comes to The Queen of Cups, like most other cards in the Cups suit, The Queen of Cups is a positive one. It also has many possible interpretations, from the straight obvious meaning of a female influence in your life to interpretations of maturity and intuition.",
        "normal": "The Queen of Cups in romance is a good sign regardless of your current relationship status. If you’re looking for a female partner, consider someone older. If you have your eyes on someone younger, they may be much more mature and intelligent than you previously thought. Don’t rush into things, try to know the true person beforehand.",
    },
    "king of cups": {
        "title": "The King of Cups is the fourteenth card in the Cups suit. Initially, as a King, you’d think the King of Cups is a mainly masculine card, but overall as Cups deal with emotions, it is quite a balanced tarot card. The King sits in a throne surrounded by water, holding a cup and a scepter in his hands.",
        "normal": "The King of Cups in romance is a good sign in regards to love. If you’re looking for someone new, expect to meet a very mature and intelligent prospective partner. You’ll look up to them in a few ways, and they’ll be very decisive. If you’re in a relationship, it could mean that the card is representing you. Are you making good decisions or any decisions? Don’t start putting off making a choice. Act.",
    },
    "ace of wands": {
        "title": "The Ace of Wands is the first tarot card in the suit of Wands. It’s a positive card, if you’re in any sort of creative field then take it as an extremely good sign. As it’s an Ace, expect new beginnings, especially relating to creativity and that first spark of inspiration to set an idea in motion.",
        "normal": "The Ace of Wands card in romance is a very good sign, especially if you’re single. The whole card is about new beginnings, so expect a change in this aspect of your life. If you’re in a relationship, you might need to do something new together to spice it up.",
    },
    "two of wands": {
        "title": "The Two of Wands is the second tarot card in the suit of Wands. Two is an important number in western esotericism, and regularly represents the duality of life. The Two of Wands refers to the potential of everybody for widening their own worldview, and that many limits are only self-imposed.",
        "normal": "The Two of Wands in romance in love and romance can be a good sign, as the card has balancing qualities. If you feel the relationship has been one-sided for a while, it’ll start to even out. This will work out in your favour whether you’ve been putting in more effort or not, a balanced relationship is a healthier one. To erase past anxiety, it might be a good idea to have a long talk with your partner.",
    },
    "three of wands": {
        "title": "The Three of Wands is the third card in the suit of Wands. A great card to see in a reading if there’s something you’re aiming for. The Three of Wands usually means you will attain your goals, through prior preparation and good foresight.",
        "normal": "The Three of Wands in romance can mean that you’re going to look to the future regarding your current situation. Can it last forever? Don’t make any rash decisions, but be mindful of your current status and if you want it to change. Make sure your life is balanced generally, and that if you are in a relationship, that neither of you are becoming overbearing or demanding towards the other. Even in the most loving relationships, each partner needs time alone to grow as an individual Too much time spent with each other can cloud our dreams and personalities and change us.",
    },
    "four of wands": {
        "title": "The Four of Wands is the fourth tarot card in the suit of Wands. A largely positive card, you should expect good things to happen when you see it, especially when relating to work and career or that project that you’re working on. It’s going to be a time to celebrate achievements, and relax now that the hard work is over.",
        "normal": "The Four of Wands tarot card in romance is a good sign in romance. It may mean that things are going to get a little more serious; meeting the family, or possibly an engagement, if that seems sensible at this time. If you’re looking to meet someone, it’s good to just keep doing what you’re doing now, even if that means doing nothing! There might be some sort of anniversary coming up soon. If there is, then try to go the extra mile this year, the other person involved will really love the extra effort you’ve put in for them.",
    },
    "five of wands": {
        "title": "The Five of Wands is the fifth card of the Wands suit. The Five of Wands is not a pleasant card and deals with conflict and sometimes aggression. The illustration shows five men fighting with wands, the victor, main aggressor or victim are all unclear.",
        "normal": "The Five of Wands in romance is a not a good sign. Things are taking a downward turn. You need to give yourself time to analyse the situation fully. Are you at fault? You can’t do worse than telling the truth. Is it your partner? You might need to think about the relationship as a whole and see if it can continue further. Remember that saints need sinners. Good implies bad.",
    },
    "six of wands": {
        "title": "The Six of Wands is the sixth tarot card in the Wands suit. The card resonates success and is a positive omen.",
        "normal": "The Six of Wands in romance is a good blessing. Focus on the future and where things are going, using the past as a foundation. If you’re single and looking, look to your past. There might be somebody there who is right for you, or some lessons to be learned. It’s likely, if you’re searching, that you’ll find somebody so attractive that you’ll want to show them off. if you’re in a relationship, then there may be a period coming where you’ll be extremely proud of your partners achievements. Generally, the Six of Wands in love and romance is a positive sign; there should be no big problems to worry about.",
    },
    "seven of wands": {
        "title": "The Seven of Wands is the seventh card in the suit of Wands. A positive card in some respects; especially relating to contests or competitions. The Seven of Wands is closely related to your willpower, and meanings will change based on how determined you are in life.",
        "normal": "The Seven of Wands in romance means that you are invested in some sort of strong relationship. This could be an established one, or even something like a long-term crush or possibly an obsession. It’s a big part of your life either way and its up to you what to do with it. In any circumstance, you should relax. The problems of today pale in the future, enough that we can even come to laugh about even the worst things. If you’re single and looking, it might be a good time to lay off the ‘hunt’, and put some more time into yourself. The more developed as a person you are, the more attractive you are to others.",
    },
    "eight of wands": {
        "title": "The Eight of Wands is the eighth tarot card in the suit of Wands. A completely enigmatic illustration for the Eight of Wands lends little initial help into even a sensible guess at its meaning.",
        "normal": "The Eight of Wands tarot card in romance is a mixed sign. A current relationship will feel steady, but potentially boring. You might have to go out of your way to introduce a new element to keep things exciting and new. If you’re single and looking, you may have to work hard to understand why you are single, and what you really want. Making quick decisions here could be potentially hazardous. You want to end up with the right person, not settle for the first person you see.",
    },
    "nine of wands": {
        "title": "The Nine of Wands is the ninth tarot card in the suit of Wands. The previous cards in the wands suit have been mainly positive with exceptions, but the Nine of Wands is where the meanings start to take a more cautious approach.",
        "normal": "The Nine of Wands tarot in romance isn’t a good sign. If you’re committed, do you want to be single?  Don’t blow things out of proportion if you’re having fights. You might just need some space and time apart for a few days, especially if it’s been heated up to now. Don’t throw away a relationship because of a few smaller things, but you don’t want to stay in a relationship with one large issue hanging over your head. You should have a few days to consider the right choice for both of you.",
    },
    "ten of wands": {
        "title": "The Ten of Wands is the tenth tarot card in the suit of Wands. As seen in the Nine of Wands, it isn’t as positive as early cards in the suit. The illustration shows a man burdened by the weight of ten wands. he can see his destination but has a long way to travel.",
        "normal": "The Ten of Wands in romance is a mixed sign. You might have already accomplished your romantic goals. Maybe you’re married? There’s likely a problem in the relationship that needs addressing; something you both know about but hide whenever it comes up. It’s time to tackle it head on and just get it done with. Don’t let something potentially trivial get in the way of a good relationship.",
    },
    "page of wands": {
        "title": "The Page of Wands is the eleventh card in the suit of Wands and the first face card. As it is a face card, it could represent a real-life person, even someone that you know; likely a younger male influence in your life. The illustration on the Rider-Waite deck shows the Page inspecting a wand, well dressed and standing in front of a barren desert landscape.",
        "normal": "The Page of Wands in romance is a very good sign. Expect a new level of deep connection in any existing relationships. The Page of Wands is an especially good sign when it comes to finding love. If you’re available and looking, expect to find somebody who you’ll fall head over heels for. They’ll just seem ‘right’ for you. All in all, The Page of Wands is a great sign for finding love. Expect a new type of relationship, spontaneous and exciting.",
    },
    "knight of wands": {
        "title": "The Knight of Wands is the eleventh card in the suit of Wands. The Knight of Wands, much like the Page of Wands, exists in a barren desert. He even dresses similarly, with a salamander motif, though unlike the Page, he is moving at speed. The Knight has decided his goal and is on his way.",
        "normal": "The Knight of Wands in romance is a very good sign. Expect a new level of deep connection in any existing relationships, but also the introduction of a new, adventurous side of your partner. The Knight of Wands is an especially good sign when it comes to finding love if you’re currently single. If you’re available and looking, expect to find somebody in your workplace, or a workplace that is related to yours. You don’t have to look far sometimes, and this person will accompany you to the ends of the Earth.",
    },
    "queen of wands": {
        "title": "The Queen of Wands is the thirteenth tarot card in the Wands tarot suit. It’s likely to signify a positive, mature female influence in your life; especially someone with a good career, who is independent and honest. Without even reading the meanings, you might already have an idea of who it may be. She should be the sort of person to whom you could go for advice on any number of topics in life. The black cat is a sign of luck.",
        "normal": "The Queen of Wands in romance is a very good sign. The strong feminine energy can represent someone (either you, your partner or someone you’re after) that enjoys spending time at work. If you’re single; you might be receiving hints from someone, so if there are offers around or you’re getting subtle hints, take the initiative; it’ll help you grow as a person. The Queen of Wands is also quite well known to signify fertility.",
    },
    "king of wands": {
        "title": "The King of Wands tarot card is the final card in the suit of Wands. The King of Wands embodies much of the meaning of the entire suit and should be taken seriously when seen. Much like the Queen of Wands, The King can represent a strong male influence in your life, somebody who has succeeded and lived their dream. You might find them quite inspiring. This could also represent you, having achieved your goals, meaning you are ready to help others with theirs.",
        "normal": "The King of Wands tarot card in romance is a very good sign and suggests a mutual feeling between two people. Expect a new level of maturity in any existing relationships as you learn previously unknown connections. If you’re available and looking, expect to find somebody who you work with, or who knows a lot about you. They’ll just seem ‘right’ for you. All in all, The King of Wands is a good sign for finding love.",
    },
    "ace of swords": {
        "title": "The Ace of Swords is the first card in the suit of Swords. All aces can mean a new start. Like a sword, the actions that bring forth this new change can act quickly and without warning. Aces regularly represent a new beginning, coupled with Swords, this suggests a new personal goal or worldview. You may see yourself coming out of your shell soon.",
        "normal": "The Ace of Swords in romance is a very good sign, especially if you are single. The whole card is about new beginnings, so expect a change in this aspect of your life. For a partner, you might run into somebody spontaneous, who is adventurous and a lot of fun to be around. If you’re in a relationship, you might be feeling the need to spice things up. It can be exciting to introduce a new aspect to your relationship, though make sure all involved are comfortable with the additions. The Ace represents beginnings, if you wish to share deeper feelings with your partner, now might be the time. You’ll develop your relationship into another level as a result.",
    },
    "two of swords": {
        "title": "The Two of Swords is the second tarot card in the suit of Swords. Two is a common number in esoteric study and understanding; balance, two halves of one whole, male and female, good and bad. This is a balanced card; not wholly about action itself, but more focusing on what to do with the information you have.",
        "normal": "If you’re already in a relationship, the Two of Swords in romance highlights the balanced aspects of the card; leading to a more fulfilling partnership. If you’re single; instead of weighing up decisions, you may be weighing up partners. If you have a choice, that is a good thing. Inside yourself, you probably know the correct choice, but you’re just playing with yourself at the moment and having fun with what could happen.",
    },
    "three of swords": {
        "title": "The Three of Swords is the third tarot card in the suit of Swords. As you may have deduced from the illustration, the Three Swords is not a wholly positive card, especially when it comes to love.",
        "normal": " As you may expect from the illustration, the Three of Swords in romance is a bad sign. It’s going to be a trying period for you, and you will likely experience loss and grief. This may not only affect you but others close to you. You may need to support your partner even when he or she hates you. Remember that relationships can withstand immense pressure, and so long as something hasn’t offended you deeply, consider working on fixing things. If you’re single and looking, cool it off, for now; it just isn’t the right time. Work on yourself; make sure you are stable in both mind and body before you seek out somebody else.",
    },
    "four of swords": {
        "title": "The Four of Swords is the fourth tarot card in the suit of Swords. The illustration shows the tomb of a knight in prayer, three swords adorn the wall and one is engraved on his tomb.",
        "normal": "The Four of Swords in romance means that now isn’t the time to go looking for love. Focus on yourself, try not to think about it for a while. If you must, work on your own hobbies and interests. These will make you more interesting to other people anyway. If you’re already in a relationship, then some time apart isn’t a bad idea. Get away from each other for a few days, when you see each other again you’ll both feel a lot better.",
    },
    "five of swords": {
        "title": "he Five of Swords is the fifth card in the suit of Swords. When you see the Five of Swords, you should prepare for some conflict to come into your life. It might not be something to be scared of, but life is about to get at least a little bit more difficult. Don’t worry, you can always see it through.",
        "normal": "The Five of Swords in romance initially isn’t a good sign. If you’re in love with your partner, expect some conflicts to come up. You need to brace yourself for the cause of it, as there may be somebody else involved too. When the conflict is over, you may need to spend a bit of time thinking about the future and where the relationship is heading. Time alone would be good when you get to that stage. If you’re currently single, then this could represent some inner conflict you’re feeling. Do you want to be in a relationship? If you’re not in one, don’t let it get to you. Make sure it isn’t a case of ‘grass is greener’ syndrome.",
    },
    "six of swords": {
        "title": "The Six of Swords is the sixth tarot card in the suit of Swords. A more positive card than the most recent cards in the Swords suit; the worst is likely over and you’re ready for some change and growth in life.",
        "normal": " The Six of Swords tarot card in romance can mean that your current relationship is naturally coming to an end. Talk to your partner and see if there is still a spark. You know inside yourself if it is right for you. Tarot should always exist to give you a second opinion of your current situation, so take all viewpoints into account. Don’t act rashly, be gentle and understanding. It could also mean that your partner feels the same way. Either way, there may be something you can solve, or it may be in your mutual interests to stop.",
    },
    "seven of swords": {
        "title": "The Seven of Swords is the seventh tarot card in the suit of Swords. The illustration is particularly apt here; your first thought is likely a good insight into what the card means. The cards usually symbolise the person receiving the reading, but in this case, it’s sensible to consider all possibilities. The important thing isn’t to jump to conclusions when you read the meanings below.",
        "normal": "The Seven of Swords tarot card in love is a mixed blessing. You have to trust each other right now. Things may start getting rocky. Keeping secrets from each other is never healthy, no matter how big. You can’t live on a lie at all. You’ve got to talk about your relationship, not in a serious tone, but make sure to spend time with each other; no distractions, just time together. If you are keeping secrets or possibly some hidden personal history, then expect your partner to find out soon. If you’re single, then remember that Soyuz need to present yourself as who you are if you want to find the right partner. You can’t put on a facade every day.",
    },
    "eight of swords": {
        "title": "The Eight of Swords is the eighth tarot card in the suit of Swords. The illustration is somewhat frightening; a blindfolded woman surrounded by swords. She doesn’t know what to do, but inaction also isn’t a good choice. There is a way out, but more likely than not it will be painful.",
        "normal": "The Eight of Swords card in love can mean that things aren’t going too well. Are you, or your partner currently happy? As harsh as this sounds; it might be worth considering breaking up, especially if you, or your partner, are bad influences for each other. Some people just aren’t meant to be together. If you’re single, are you happy? Maybe it’s time to dedicate yourself to actively looking for a relationship. You might feel like this is impossible, so ask for help, it’s not something you have to do alone.",
    },
    "nine of swords": {
        "title": "The Nine of Swords is the ninth tarot card in the suit of Swords. A largely negative card, the illustration shows a man awakening from a nightmare, filled with grief. Nine swords are suspended on the wall at his bedside. His blanket is a patchwork quilt of red roses and zodiacal symbols. The Nine of Swords is widely regarded as a ‘bad’ card to draw, but take your whole reading into account when you interpret it.",
        "normal": "Don’t suffer in silence if something is bothering you in a relationship. It might just be nothing, but through miscommunication, it has been blown out of proportion. Recent infatuations may have happened, but don’t be rash and act on them as soon as you can; give it some time. If you are single, then don’t worry about being single forever. This is a common worry for some, but you should find reassurance that this period will come to an end.",
    },
    "ten of swords": {
        "title": "The Ten of Swords is the tenth tarot card in the suit of Swords. Running with the recent trend of the suit of swords; the Ten of Swords is not overly positive. The illustration somewhat backs this up; a man lying motionless on the ground with ten swords in his back. The Ten of Swords is regarded as the most destructive and grim card in the deck, but consider your entire reading when you interpret meanings.",
        "normal": "The Ten of Swords tarot in romance can mean that your current situation is going to come to an end. The Ten of Swords for love is just plainly not a good sign. Take solace that this is how it is meant to be. If your relationship isn’t working then why continue? If you’re single, then don’t expect to get into a relationship if you’re looking, and if you do, don’t rush into it; it might not be what you want after all.",
    },
    "page of swords": {
        "title": "The Page of Swords tarot card is the eleventh card in the suit of Swords, and the first ‘face’ card. Just coming from the Ten of Swords, the Page of Swords is a step up in terms of positive energy. Face cards can stand for a real person in our lives, in this case possibly someone younger than the receiver of the reading but could as well be the person receiving the reading.",
        "normal": "The Page of Swords tarot card in romance isn’t a great sign, but it isn’t a wholly negative one either. Try to balance things out, your partner is a person too. Try to give them some time and go out of your way to do something special. It’s important that you’re both happy around each other, so give each other space, especially if things have been difficult recently. There might be some conflict, so when it starts don’t revert back to your old ways and try to win the argument. Try to settle the argument fairly. If you’re single,",
    },
    "knight of swords": {
        "title": "The Knight of Swords is the 12th tarot card in the suit of Swords. A slightly more positive card, especially relative to the other cards in the swords suit so far. You should expect better things to happen when you see it, especially any news regarding a younger male you might know. Expect to receive good ideas if you’re stuck, or other good unexpected news.",
        "normal": "The Knight of Swords tarot card in romance is mixed; love is an emotion, but the Knight of Swords is a methodical card. You can apply this to an existing relationship; work out what your partner wants and take steps to achieve this, if you have the same mindset. Don’t fake emotion if prompted, sometimes we just need to switch off for a while and concentrate on things outside a relationship. Knights are an especially good sign if you’re single and looking.",
    },
    "queen of swords": {
        "title": "The Queen of Swords is in the Minor Arcana and is the 13th tarot card in the suit of Swords. Usually, the queen will represent somebody in your life, most likely a mature woman who is quick to anger. Without even reading the meanings, you might already have an idea of who it may be.",
        "normal": "The Queen of Swords in romance is a good sign, the strong feminine energy can represent someone (either you, your partner or someone you’re after) that enjoys being their own person; a free spirit with knowledge or skills that others desire. It’s incredibly important not to force your will on anybody, likely a partner with the intent to change them. If you feel something is wrong in your relationship, an informal chat can do wonders. If you’re single and looking, you should hope for a tarot card like this, look for possibly an artist, writer or another creative type. They’ll likely be mature and quick to act, but not reckless.",
    },
    "king of swords": {
        "title": "The King of Swords is the final card in the suit of Swords. The King of Swords embodies much of the meaning of the entire suit and should be taken seriously when seen. Much like the Queen of Swords, The King can represent a strong male influence in your life, someone with authority and power.",
        "normal": "The King of Swords tarot card in romance is a very good sign. Expect a new level of maturity in any existing relationships. The King of Swords is an especially good sign when it comes to finding love, especially when masculine energy is needed. If you’re male, then work on what you think masculinity is. If you’re female, then look for defined male traits in a prospective partner.",
    },
    "ace of pentacles": {
        "title": "The Ace of Pentacles is the first tarot card in the suit of Pentacles. A largely positive card, you should expect good things to happen when you see it. Pentacles represent material possessions and wealth. Pentacles in tarot are also sometimes called Coins. The pentacle itself is a well-known symbol with many meanings and interpretations in many faiths, notably Wicca. The Ace of Pentacles is well regarded as a favourable card to receive in a reading.",
        "normal": "The Ace of Pentacles tarot card in romance is a very good sign.  Many things that happen in a relationship seem like a big deal at the time, but when you really think over it, it’s nothing to be concerned about. Don’t blow things out of proportion. If you’ve been saving up, it might be time to cash in the potentiality of that money for a real-world experience. Money in the bank is just a number, but it can be so much more. Surprise your partner with a romantic gesture, possibly a short trip away. If you are single, the Ace suggests a new start, so keep your eyes open for any future love interests, especially if you have started a new workplace.",
    },
    "two of pentacles": {
        "title": "The Two of Pentacles is the second tarot card in the suit of Pentacles. Two is a common number in esoteric study and understanding; balance, two halves of one whole, male and female, ups and downs, good and bad. Generally, a positive card, the Two of Pentacles can remind us to respect the balance that our lives require.",
        "normal": "The Two of Pentacles in romance can mean that your relationship or lack of it needs to be a higher priority for you. Are you spending enough time with each other? Are you growing closer or apart? You can think about it a lot, but usually, your instinct is correct. If you’re single, do you really want a partner right now? You have to work out what you want and how, if it’s possible, how it is going to fit into your current life. Negative feelings of past relationships can affect our future choices, but remember that not everybody is the same. The love you had for somebody in the past will affect how you feel now, but try not to project personalities from previous partners onto new ones. Meet new people, see more.",
    },
    "three of pentacles": {
        "title": "The Three of Pentacles is the third tarot card in the suit of Pentacles. A largely positive card, you should expect good things to happen when you see it, especially when relating to work and career.",
        "normal": "The Three of Pentacles in romance is a mixed sign in romance It may mean that you’re going to have to look to past relationships to work out issues with your current one. If you’re looking to meet someone, it’s good to just keep doing what you’re doing now, even if that means doing nothing!",
    },
    "four of pentacles": {
        "title": "The Four of Pentacles is the fourth tarot card in the suit of Pentacles. A somewhat positive card, you should expect some good things to happen when you see it. Watch out though, it has specific meanings that you might want to be careful with.",
        "normal": "The Four of Pentacles tarot in romance can mean that you’re clinging on to something that isn’t good for you. This can be either a current relationship or lack of relationship. You might have your own little happy bubble that you live in, but you’re going to need to go outside of it to experience real romance and love. Comfort is a good thing in life; we all love feeling comfortable, but don’t let this comfort turn into apathy. You live life, you don’t watch it go by.",
    },
    "five of pentacles": {
        "title": "The Five of Pentacles is the fifth tarot card in the suit of Pentacles. A quick look at the illustration gives a quick overview of the card depicts two men in walking in front of stained glass window, both look seem to be facing adversity and it is not a wholly positive card. When it comes up in a reading, prepare yourself for news you hadn’t hoped for.",
        "normal": "The Five of Pentacles in romance is a mixed sign. Make sure you’re in a relationship (or single) for the right reasons and spend some time to think if either of you is draining the other. The sense of poverty in the Five of Pentacles suggests a potential breakup. With this in mind, don’t blow things out of proportion. There are issues you can work through that will seem mild at best when discussed.",
    },
    "six of pentacles": {
        "title": "The Six of Pentacles is the sixth tarot card in the suit of Pentacles. A more positive card than the most recent cards in the Pentacles suit; things are starting to look much more positive and also mature now. Expect to see things how they really are, and to understand how much of a positive change you can make in the world.",
        "normal": "The Six of Pentacles in romance is a mixed blessing. From the outside, your relationship appears like it’s going well, but under the layers we keep hidden there are some issues. The thing is, only one of you might be aware of them. Take care and discuss them like adults. Bring up things. They shouldn’t be your partner if you can’t discuss things important to you. Also, make sure it isn’t a one-sided relationship, emotionally or materially.",
    },
    "seven of pentacles": {
        "title": "The Seven of Pentacles is the seventh tarot card in the suit of Pentacles. A positive card from the minor arcana, you should expect good things to happen when you see it. The illustration shows a man growing crops (crops of Pentacles) and peacefully watching over them. He has put in the effort to nurture them to grow and is about to reap the reward of his prior hard work.",
        "normal": "The Seven of Pentacles in romance means that you are invested in some sort of strong relationship. This could be an established one, or even something like a long-term crush or possibly an obsession. It’s a big part of your life either way and its up to you what to do with it. In any circumstance, you should relax. The problems of today pale in the future, enough that we can even come to laugh about even the worst things.",
    },
    "eight of pentacles": {
        "title": "The Eight of Pentacles is the eighth tarot card in the suit of Pentacles. A positive card, you should expect good things to happen when you see it; especially aspects relating to a creative industry, or a project or part of your life that you have worked extremely hard on and dedicated yourself to. A good card to draw if you are intent on learning a skill or trade which you have a lot of passion for.",
        "normal": "The Eight of Pentacles in romance is a very good sign. A current relationship will greatly deepen; not through any event, but through continued understanding and shared experience. If you’re single and looking, you may have to work hard to understand why you are single, and what you really want. Working on yourself whether you are single or in a relationship is always a good aim; look after your body and mind.",
    },
    "nine of pentacles": {
        "title": "The Nine of Pentacles is the ninth tarot card in the suit of Pentacles. Similar in appearance to The Seven of Pentacles with the plant imagery, but with stark differences. The illustration in the Seven of Pentacles shows a man resting after work and enjoying what he started a while ago, whereas the Nine of Pentacles shows a woman casually enjoying a garden, with no signs of labour, though a Falcon rests on her left hand.",
        "normal": "The Nine of Pentacles in romance is a very good sign. Do you want to be single? Do you want a new level of relationship, or a new relationship altogether? Any choice is possible. Many things that happen in a relationship seem like a big deal at the time, but when you really think over it, it’s nothing. Don’t blow things out of proportion, you’re comfortable where you are now, and there’s no reason to change.",
    },
    "ten of pentacles": {
        "title": "The Ten of Pentacles is the tenth tarot card in the suit of Pentacles. It is a positive card in terms of material retention, don’t expect to be needy or in want of something you desire.",
        "normal": "The Ten of Pentacles tarot card in romance is a very good sign. Expect happiness and a general lack of stress. Are you looking for someone? It might be worth thinking about what your traditional ‘type’ of partner is if you have one. It’s likely to be a good time for you now, generally in life. If you want to spend this time alone, that’s fine too.",
    },
    "page of pentacles": {
        "title": "The Page of Pentacles is the eleventh card in the suit of Pentacles, and the first ‘face’ or ‘court’ card. A largely positive card, you should expect good things to happen when you see it, especially in any areas concerning long term goals or progression. The Page of Pentacles in tarot readings grounds us in the ‘real world’, so that we can manifest our dreams as tangible goals to achieve.",
        "normal": "The Page of Pentacles tarot card in romance isn’t a great sign. Things might feel stale. Do you want to be single? Do you want a new level of relationship, or a new relationship altogether? Any choice is possible, but you might need to put some effort in. You may even feel like you are trying more than your partner. Many things that happen in a relationship seem like a big deal at the time, but when you really think over it, it’s nothing. Don’t blow things out of proportion. If you are single, then again, you might need to put a lot of effort into yourself to find the right partner. It might be time to consider a new look or to look for new connections outside of your usual friend group.",
    },
    "knight of pentacles": {
        "title": "The Knight of Pentacles is the 12th tarot card in the suit of Pentacles. A  positive card, you should expect good things to happen when you see it, especially any news regarding a younger male you might know. As you may expect, the card embodies some knightly qualities; things many of us would do well to aspire to.",
        "normal": "The Knight of Pentacles in romance can signify ‘the Knight in shining armour’ that your partner or potential partner is looking for. You’re going to need to be responsible for yourself and your partner if you’re in a relationship, so don’t shirk away from taking a leading role. If you are single, then look to be willing to make a serious commitment to another person when the opportunity arises. You might need to go out of your way to meet somebody new, and this could mean doing something that is completely out of your comfort zone.",
    },
    "queen of pentacles": {
        "title": "The Queen of Pentacles is the 13th tarot card in the suit of Pentacles. Usually, the queen will represent somebody in your life, an older woman, who has a very comfortable life. Without even reading the meanings, you might already have an idea of who it may be. Many draw parallels between The Queen of Pentacles and the concept of Mother Earth; a nurturing feminine spirit that takes care of us if we take care of her.",
        "normal": "The Queen of Pentacles in romance is a very good sign, the strong feminine energy can represent someone (either you, your partner or someone you’re after) that enjoys spending time at home, helping others, maybe fixing things and other practical pursuits. This person will be a solid foundation for the relationship. This person does not like drama and is calm and delicate in all areas of life.",
    },
    "king of pentacles": {
        "title": "The King of Pentacles is the final tarot card in the suit of Pentacles. The King of Pentacles embodies much of the meaning of the entire suit and should be taken seriously when seen. Much like the Queen of Pentacles, The King can represent a strong male influence in your life; likely somebody who is well off in a material sense.",
        "normal": "The King of Pentacles tarot card in romance is a very good sign, and an especially good sign when it comes to finding love. If you’re available and looking, expect to find somebody who you’ll fall head over heels for. They’ll just seem ‘right’ for you. All in all, The King of Pentacles is a great sign for finding love. Expect a new level of maturity in any existing relationships, as a King, expect your other half to become a ‘Queen‘. It might be the right time to treat your partner to a gift or treat, even if there is no occasion.",
    },
}
