past_deck = {
    "the fool": {
        "title": "It might sound bad from the name, but The Fool tarot card is not a negative card at all! In fact, it’s associated with the number zero – the number of infinite potential. In the Major Arcana, The Fool represents you, the main character,  journeying through life. So, when The Fool shows up in your reading, get ready for major change and transformation! The Fool tarot card is all about living in the present moment and enjoying your life without worry. Just look at how happy the man in the card is in spite of his treacherous surroundings. Sometimes we need to take a little risk, even if we aren’t sure how things will turn out, because, if we never try, we will never know what could have been! The Fool reminds you to stay true to your heart and follow your dreams.",
        "normal": "Did you start a new job or career recently? Or maybe you moved to a new country or began a new romantic relationship? When upright, The Fool in the past position suggests that there was a new beginning that was set in motion a while ago, that will now be playing out in your life.",
        "reversed": "If the card lands in reverse in your spread, it might mean that you missed an opportunity or you were too reckless in some of your choices. But don’t worry, we can always make changes in life! The Fool makes his journey through the Major Arcana over and over, as do we every time we start a new chapter in our lives."
    },
    "the magician": {
        "title": "You’ve got what it takes to make it happen! That’s the general message of The Magician tarot card. With diligence and focus, you can create anything you desire, but you have to be deliberate in your actions and choices. Use your willpower and don’t underestimate your own abilities. Sometimes we don’t realize everything we have available to us. The Magician encourages us to have confidence and to be resourceful.",
        "normal": "You come from a place of great accomplishment, thanks to your own hard work and diligence. This was a time of flow and accomplishment, where success seemed to come naturally. Your willpower and drive have enabled you to lay a solid foundation for yourself and it is from this point that you now move forward in your life.",
        "reversed": "It looks like you haven’t reached your full potential yet. When The Magician appears in the reversed position in your reading, it indicates that you might be unaware of some of the skills, tools, or talents you have at your disposal. But don’t worry, we always have opportunities to create a better life for ourselves!"
    },

    "the high priestess": {
        "title": "The High Priestess is the guardian of your intuition, indicating that it can be a powerful indicator that you will need to trust your feelings when it comes to love and romance. Difficulties can develop when you ignore your intuition and follow only your conscious mind",
        "normal": "You recently put your intuition to good use when making a major decision, and this will serve you well moving forward. When the past position reveals The High Priestess, it confirms that you recently used your inner wisdom to solve a problem or initiate a major transformation in your life. Your patience and trust in the flow of the universe have put you on a good path. Keep listening to your inner voice as you move forward in your life.",
        "reversed": "Was your intuition trying to tell you something but you didn’t listen? Did you push forward with logic and reason without considering the messages from your subconscious? In the reversed position in the past, The High Priestess represents a time where were you were disconnected from your inner wisdom. Whatever choices you made at that time are influencing you today."
    },

    "the empress": {
        "title": "It’s time for you to stop and smell the roses! The Empress takes the time to enjoy and appreciate all of the finer things in life, and she’s appearing in your reading to remind you to do the same. She is Venus, the ruler of love, art, and beauty, and represents fertility of all kinds. Whether your reading is about romantic relationships or your career, the message of The Empress is to bring your creative ideas and pursuits into the physical world. But, if she’s showing up in the reverse, it might be that you’ve gone too far into luxury and enjoyment! A reversed card always means that the qualities of that archetype are too extreme. In reverse, The Empress suggests that too much of a good thing can lead to laziness and co-dependence.",
        "normal": "You come from a stable and fulfilling background, and your past was filled with plenty of love, luxury, and abundance. Even if wealth wasn’t excessive, you were loved, supported, and valued. In the upright position, The Empress is reminding you to stay connected to your gratitude and always remain appreciative of the abundance in your life.",
        "reversed": "In the reverse position, The Empress suggests that you might have lived a life of excess in the past, where you overspent on a lavish lifestyle, and this could be causing you some problems in the present. Or maybe you didn’t care for yourself enough so that The Empress in you wasn’t able to flourish. This card is asking you to assess the theme of abundance in your life so that you can bring it back into balance."
    },

    "the emperor": {
        "title": "The Emperor uses power and organization to accomplish his goals. He is wise and powerful in his ways, and in the upright, can act as a protector. This card in your reading can represent your current energy, or can also represent a boss, father figure, spouse, or system of authority that is prominent in your life. When he appears in the reverse, The Emperor is tyrannical. He is overly rigid, lacks empathy, and won’t think twice about using force to get what he wants, even at the expense of others. The energies of this Major Arcana card are a powerful influence for good or for bad.",
        "normal": "You grew up in a home that was very stable and structured, or perhaps you are recently coming from such a relationship. With The Emperor in the upright position, your home environment was organized and rules were clearly laid out, which created a sense of stability and security for you.",
        "reversed": "If your childhood was influenced by The Emperor in reverse, things probably looked a lot different! You likely had a domineering and controlling energy in your home, and rules were enforced by force or the threat of force. Rigidity and schedules were an underlying theme. Alternatively, The Emperor in reverse in the past position could indicate that you did not exercise enough discipline in your own life, and lacked the structure and organization you needed to gain mastery over your life."
    },

    "the hierophant": {
        "title": "Sometimes The Hierophant is referred to as The Pope of the priest of the Major Arcana. The Hierophant mirrors The High Priestess in the same way that The Emperor mirrors The Empress. This Major Arcana card is a masculine card representing structure and tradition but is focused on the spiritual realm. He is a card of religious doctrine, which values faithful devotion to traditional religious practices as a means of reaching spiritual fulfillment.",
        "normal": "You come from a traditional and perhaps religious family background, which has given you a true sense of belonging and shared values with others. Or it could be that religion and spirituality played an important part in your life in the recent past, whether through education or belonging to a religious institution. In the upright position, the Hierophant provides community and safety from a sense of belonging.",
        "reversed": "However, in the reversed position, this Major Arcana card can indicate dogma or closed-mindedness. If you recently moved away from a situation that was intolerant or judgemental, you discovered that you are your own teacher! You trust your own instincts and were brave enough to forge your own path."
    },
    "the lovers": {
        "title": "The Lovers card has landed in your tarot card spread to signify a beautiful relationship in your life! There is clear communication and an ability to be vulnerable with one another. This card often signifies a sexual relationship, though it doesn’t have to be. This Major Arcana card also represents choices. It seems that an important decision will be coming up in your life, so the surrounding cards of the reading will be very important!",
        "normal": "In your past, you enjoyed a supportive and loving relationship, which set the foundation for your current sense of groundedness and wellbeing. Whether you are single now or not, the benefits of this bond are still with you, and you should wear those stripes proudly.",
        "reversed": "If reversed, The Lovers in the past position indicates that you might have had some difficulties around relationships recently. Maybe you had to make a difficult decision which led you to where you are today."
    },
    "the chariot": {
        "title": "The Chariot represents overcoming obstacles after a long journey or hard-won battle. Depending on where this tarot card appears in your reading, the message is one of maintaining focus and confidence in the pursuit of your goals. The Chariot card suggests that your strength and commitment is being tested by the universe, so don’t give up or look for shortcuts. Are you pushing yourself ahead at break-neck speed to the point of obsession? This might be why The Chariot is showing up in the reversed position in your tarot card reading. If the pursuit of victory is becoming excessive, you might actually be standing in your own way. If you’re lacking direction and feel yourself floating aimlessly, a reversed Chariot card will also appear in your reading. Whether your willpower and focus is excessive or lacking, the goal is the same: bring these energies into a healthy state of balance.",
        "normal": "You overcame challenging times in the recent past, but because of your determination, you managed to succeed. Now you are stronger for it, and your confidence is apparent to everyone around you. Hard work pays off eventually, and you are evidence of that success.",
        "reversed": "If you gave up in the face of a challenge recently, then The Chariot will show up in the reversed position. Maybe you were lacking self-confidence, or you just weren’t sure which direction to take. Or maybe you pushed ahead without thoughtful consideration and wound up missing your target in the end. Either way, the positive energies represented by The Chariot didn’t manifest in a constructive way in your life."
    },
    "the justice": {
        "title": "You can expect a fair outcome to a challenging situation in your life! If you have acted with integrity toward others but you have been wronged or hurt, the Justice card assures you that karma will be brought back into balance. However, if you have made decisions that harmed others, the Justice card comes as a warning. Justice demands truth and honesty, so a reversed Justice card indicates gossip, misinformation, and lies. You may have behaved in ways that were morally questionable and you are failing to take responsibility for your choices. Be fair in your choices and be sure to seek out the facts before making any judgements or assumptions about others, and make an effort to right the wrongs you committed before Justice does it for you.",
        "normal": "It looks like you made a big decision in the recent past that is affecting your life today. In the past position, the Justice card usually indicates that you made a big change in your life. Maybe you were divorced, changed careers, or moved to a new city. Whatever it was, you made a major break from your past and that choice now forms the foundation of your current situation.",
        "reversed": "Did you just go through a rough time? Were you untreated fairly by others? Or maybe you didn’t take responsibility for something that you should have owned up to? This card in the reverse indicates that there was a significant situation in your recent past where justice was clearly lacking."
    },
    "the hermit": {
        "title": "The Hermit is the soul searcher and is here to encourage you to reflect on your deepest feelings and needs. The appearance of this Major Arcana card in your tarot card reading heralds a time for pause. There is often a major turning point around the corner. A new path may be opening to you that you have been unable to see because of the noise and distractions in the outside world. Sometimes life forces us into retreat and sometimes it’s by choice, but either way, it is from the darkness that we find the light. When the energies of The Hermit are out of balance, he will present in your reading in the reversed position. This can indicate escapism rather than self-reflection, or a resistance to looking within for answers.",
        "normal": "You recently experienced a period of solitude or even a “Dark Night of the Soul.” External or internal events led you to retreat from the world for a period of time so that you could reflect upon what is really important to you. In that quiet space, you discovered long-forgotten desires and unwanted beliefs and fears. In this quiet place, you released those unwanted energies and reconnected with your deepest inner truth.",
        "reversed": "When we resist the call to go within, The Hermit will present in the reverse. Losing touch with our inner voice leads to living an inauthentic life. When we avoid looking at our shadows out of fear, we forego any possibility of integrating them. This Major Arcana tarot card can also appear in the reverse when we have been abandoned or betrayed by loved ones. In this position, The Hermit suggests that you failed to learn the lessons of self-love and self-protection in the past."
    },
    "the wheel of fortune": {
        "title": "Fate and destiny are about to kick in so get ready for some major changes. This can apply to your romantic relationships, career, health, or any other subject you are delving into with your tarot card reading. Our lives are made up of a series of cycles, and The Wheel of Fortune makes an appearance when one cycle is about to end so that another one can begin. One thing we know for sure is that things always change. The Wheel of Fortune is generally associated with good luck, but if it appears in the reverse, it’s suggesting that you’re resisting change. Or maybe you’ve got yourself stuck in an endless cycle of repeating patterns. Sometimes even “bad luck” leads to positive change, we just can’t see it until afterward.",
        "normal": "You just went through a major change or shift in your life that set you on a new path or direction. In the past position, The Wheel of Fortune often indicated some kind of tumultuous change like a divorce, changing jobs, a major relocation or even a serious health issue. In any case, these major changes are still affecting you and have made a great impact on the person you are today.",
        "reversed": "It’s really important to consider the surrounding cards when you are interpreting The Wheel of Fortune. Major Arcana cards in particular, represent long term energetic influences because they directly deal with huge personal transformations. If this card shows up in the reverse position in the past, you may have been resisting change, which has now left you in a difficult situation."
    },
    "the strength": {
        "title": "The Strength card follows The Chariot in the Major Arcana series. After we learn to use our strengths externally to overcome the stumbling blocks on your path, we must also learn more compassionate and refined ways of achieving our goals. The lesson of the Strength card is that we do not need to control others in order to succeed. We can rely on stamina, patience, and understanding to maintain harmony and balance in our lives.",
        "normal": "The Strength card in your past position indicates that you have approached difficult situations with calm resolution. You refrained from aggressive confrontations even when times were tough. As they say, you catch more flies with honey, and this is true of most situations.",
        "reversed": "The Strength card represents having self-mastery of your base instincts such as rage, guilt, jealousy, or shame. So, The Strength card showing up in the reverse position in your past suggests that you weren’t able to handle a difficult situation with grace and calm. Alternatively, you might have lost touch with your inner power. Some traumas can leave us shaken, with a loss of self-confidence. This Major Arcana card in reverse is asking you to bring your inner power back to a state of equilibrium."
    },
    "the hanged man": {
        "title": "Are you trying to control things, but you’re not getting the results you want? It’s time to take the advice of The Hanged Man. This tarot card tells you to take a pause so you can gain a new perspective on your situation. This card is all about choosing to surrender to the flow of the universe. You received this card in your tarot card reading because there is some situation in your life that you need to respond to in a new way.",
        "normal": "You just went through a period of time where you released something major. Whether it was in romance, your career, or your spiritual path, you went through a period of pause and self-reflection because you knew that you were fighting an uphill battle. Sometimes the universe brings us obstacles to force us to look at something we might have been avoiding. You successfully left something behind that wasn’t serving you anymore, which has brought you to where you are today.",
        "reversed": "Did you make an impulsive decision in the recent past that led you into a difficult situation? This tarot card in reverse can indicate that you didn’t take the time to pause and reflect before rushing into something and you’re suffering the consequences today."
    },
    "the death card": {
        "title": "The Death card of the Major Arcana is symbolic of endings, allowing a chapter of your life to “die” so that a new one can begin. It’s not always easy to let things go. Accepting endings can be painful. But it is important to remember that what is in store for you is likely to be even better than what you are leaving behind. Everything in the world works in cycles, so embrace the endings so you can look forward to the new.",
        "normal": "You just came out of a major ending. It might have been painful, but it was necessary. The past position is the best place for you to get The Death card in your tarot card reading. It means you already did the work, and there is a new door open to you now. You may have left a relationship or had another major ending, but this has now cleared the path for you, and the worst is behind you.",
        "reversed": "Were you clinging to something that was hurting you? Were you staying in a toxic relationship dynamic for fear of letting go? The change still happened, as it always does, but maybe you made it more difficult for yourself by not accepting it. The Death card teaches you to accept the inevitable, even when we are afraid."
    },
    "the temperance": {
        "title": "On The Fool’s journey through the Major Arcana, The Temperance card comes up after the Death card. It’s often the painful things in life that become our greatest teachers. When life asks us to let go of something that is very important to us, we begin to learn non-attachment. Temperance has discovered that adaptability, trust in the universe, and moderation brings us the greatest peace. When we surrender to the flow of the universe, we can begin to live an enlightened existence.",
        "normal": "Your recent past has been harmonious and calm, thanks to your patience and understanding. You’ve been living a life of moderation and balance, and that is paying off for you now. If you recently went through a major trauma, The Temperance card acknowledges that you really grew from this experience in a positive way!",
        "reversed": "Because Temperance is in the reverse, you just experienced a time of imbalance and impatience. You may have gone through a tough period where you overreacted or behaved in an extreme way. Maybe you threw yourself into love too far too fast, spent way too much time at work at the expense of your relationships, or maybe you engaged in some reckless spending."
    },
    "the devil card": {
        "title": "It’s easy to lose sight of the fact that nobody else is responsible for our happiness and that no matter how hard we try, we can’t find happiness in the external world. This is how addictions and attachments develop. The Devil card exposes our tendency to shift responsibility, whether it’s by adopting the victim mentality or by numbing ourselves with carnal pleasures. Until we learn to generate happiness from within, we choose to remain chained, so to speak.",
        "normal": "Phew! It looks like you got out just in time! The Devil appearing in your past position indicates that you were surrounded by some toxic energy that was holding you back. Whether it was a domineering person in your life or some kind of addiction, it played a major role in your life.",
        "reversed": "You recently broke free from some major chains! It takes honest self-reflection and a good dose of strength and courage to accomplish that, so well done. You left your addictions behind you and freed yourself from self-destruction. The Devil in reverse indicates overcoming self-imprisonment and attachment."
    },
    "the tower": {
        "title": "In its essence, The Tower represents a groundbreaking change. It doesn’t always foretell chaos and destruction, though by the look of the card you might think so! Lighting strikes a stone tower and people are jumping from the windows to escape the flames. This card follows The Devil card in the Major Arcana, and the message is clear: do not resist change or the universe will force it upon you.",
        "normal": "You have some major upheaval or trauma in your recent past that is still affecting your life today. The good news is that it is now behind you! After the destruction of The Tower, new opportunities await you. The transformation could have been something physical, such as a divorce or death of a loved one, or it could be internal.",
        "reversed": "In the reversed position, The Tower indicates that you avoided a traumatic event in your recent past, or perhaps you delayed it. The message of The Tower is to accept change. The old ways must go in order for you to awaken to higher consciousness."
    },
    "the star": {
        "title": "You’re wishing upon a star when this Major Arcana card makes an appearance in your tarot card reading, and the good news is that your wishes are about to come true! Will it be new love, or taking your relationship to the next level? The energies of hope and faith surround you and are supporting you in a brand new path or direction. You have a lot to be optimistic about because the universe is blessing you at this time.",
        "normal": "You must have initiated a beautiful new idea recently for The Star to show up in your reading in the past position. Whatever inspired you, you acted on it and it brought you to the place you are at today! This card is also about self-healing and nurturing, so you might be coming out of a time of pampering yourself, heart and soul. If you are happy with where this has led you, then always remember that your dreams can turn into reality. If it didn’t quite develop into what you wanted, The Star card is here to remind you that we ought to follow our dreams, but we do need some practicality to back up our actions.",
        "reversed": "Did you lose hope recently? Did you give up on a dream? A reversed Star card asks you to take a moment to see if your loss of optimism might have prevented you from pursuing your dreams? Take some time to look at your current situation. When we give up on our dreams, we don’t end up where we want to be in life."
    },
    "the moon": {
        "title": "When times are uncertain, we often begin to feel afraid or anxious. The Moon card represents a time of the unknown where we might feel out of control. But rather than hiding or running from the shadows, take the time to listen to your intuition. Whatever is revealed to you will only serve you in the end. When we discover things that are hidden beneath the surface, we can take action to better our environment.",
        "normal": "Some big secrets were revealed recently that were not easy to deal with. You had to confront the realization that things were not as they seemed. There may have been painful emotions associated with this – perhaps a lover cheated on you or withheld important information. However this manifested, the truth came to light and brought you clarity about your life. This has enabled you to make choices that brought you to a new place of understanding and certainty.",
        "reversed": "Did you refuse to listen to what your heart was telling you? Maybe the signs were there but you didn’t want to see them? In the reverse, The Moon card indicates a refusal to listen to our intuition and a reluctance to face truths that are coming to the surface. Or perhaps you didn’t understand the messages. Regardless, this time is now behind you and you have learned from your experience."
    },
    "the sun": {
        "title": "Positive energy is all around you sending warmth and confidence to all that you do. Just like the sun in our sky makes the plants grow and gives us light and warmth, The Sun card of the tarot is also representative of the source. It comes toward the end of the Major Arcana after The Fool has made his journey through many obstacles and challenges. All of these trials have made the querent a better person because he now knows how to live in the light.",
        "normal": "You have a history of bringing joy to those around you because you brought happiness with you wherever you went. People were attracted to you because of this and it made you admired and respected by many. Your optimism and joy have brought you to the place you are today, so be sure to keep these qualities with you as you move forward in life!",
        "reversed": "Were you lacking in confidence in the past? Or maybe you were scolded for being too bold? The Sun in the reverse indicates that there was a time in your past where your confidence was out of whack. It might have caused you to miss some opportunities. Wherever you are in your life today, strive for a healthy and balanced level of positivity and vitality, and success will be yours."
    },
    "the judgement": {
        "title": "When we undergo a spiritual awakening we realize that the answers are always within us. Others who judge us are merely projecting their own fears and insecurities on us and the same is true when we judge other people. Judgements come from a place of fear and we erroneously think that if we reject what makes us feel uncomfortable we will somehow be safe from it. The Judgement card asks us to look within ourselves instead, so that we may be freed from past beliefs and choices and live our lives with grace.",
        "normal": "You recently made a major life-altering decision or experienced a spiritual awakening. Your choice is not being judged – it was made based on the beliefs you held at that time. It is clear, however, that this choice has led you to where you are today. The Judgement card in the past position indicates that you are now taking stock of the choices you made and how they influenced your current situation.",
        "reversed": "Are you beating yourself up for making a “wrong” decision? The Judgment card in the reverse indicates that you may need to forgive yourself for past missteps. Take responsibility for your choices and what they led to, but let go of any guilt or shame. We make the best decisions we can with the beliefs and knowledge we have at the time. The important thing is that we learn and don’t repeat mistakes."
    },
    "the world": {
        "title": "You feel like you’re on cloud nine right now because your life is in perfect alignment with your innermost dreams and desires. You successfully completed your journey through the 22 cards of the Major Arcana, each one of them carrying a profound lesson with accompanying challenges. All of these obstacles were your training ground and the final card, The World, marks your arrival! You learned to trust the universe as well as yourself, and you learned to surrender when needed. You learned to use your intuition and control your passions.",
        "normal": "You are a force to be reckoned with and you deserve the respect that you enjoy! Your current situation is founded on a deep sense of accomplishment and success in your past. It may have been recent or in childhood, but either way, it established a solid foundation for you that has supported you into the present.",
        "reversed": "If you experienced some kind of difficult blockage or frustration right before achieving something great, then The World card will present in the reverse. But it signifies that you succeeded to move ahead in spite of it, and that blockage is now a thing of the past."
    },
    "ace of cups": {
        "title": "The Ace of Cups is the first card in the suit of Cups. A largely positive card, you should expect good things to happen when you see it. Cups represent emotions, and so the Ace of Cups tarot card can represent a beginning of emotions, think new relationships, friendships and connections. Cups represent our feelings, over our logical thoughts.",
        "normal": "The Ace of Cups tarot card in the Past position can represent a past event where you were passionate and creative. It could have been a time when you experienced a good feeling of ‘flow‘. Do you need something like this now? Think back to that past time and try to remember how you felt to further motivate yourself. Thinking back to past good events can make us feel good now, and remembering the good times in our lives can help us get through the bad times. Life is never an uphill stroll, there are always pitfalls and obstacles, but it is how you deal with it which makes you grow as a person.",
    },
    "two of cups": {
        "title": "The Two of Cups is the second tarot card in the Cups suit. The Two of Cups shows a man and woman staring into each other’s eyes, gaze fixed over two large cups. The duality symbolism is clear; male and female on opposite ends of the card. The winged staff of the caduceus represents a mythic chimera; possibly something is amiss or unknown, although this does not signify deceit or lies.",
        "normal": "The Two of Cups tarot in the Past position highlights past relationships and how they have affected your life. Reflect on your past romantic relationships and long-lasting friendships to see if there are any lessons that need to be learned. It can be easy to make the same mistakes again and again, especially when relationships are concerned. We are animals, and we have instincts which can sometimes overpower our reasoning. This isn’t necessarily bad, it is just how we are. Learn as much as you can about what you want in life by examining what you have done in the past. What did you truly like and dislike?",
    },
    "three of cups": {
        "title": "The Three of Cups is the third tarot card in the Cups suit. The card shows three people meeting, celebrating with cups held to the sky. A bounty of fruit and vegetables are by their feet. The scene is representative of a harvest festival ritual celebration, and gives off a good feeling. The Three of Cups is a good card to draw in almost any position.",
        "normal": "The Three of Cups in the Past position could suggest a past period where you had everything you needed. This time of abundance is paying off now. Maybe you put a lot of work in and achieved something in your workplace which people admire you for. Perhaps you have helped a lot of people in the past who will soon appear to pay you back in kind. Maybe you took care of your body, and now you are in very good health.  Think back at the things you have achieved and how they are paying off now, but also, consider what you can start to do, today, that will pay off for you in future.",
    },
    "four of cups": {
        "title": "The Four of Cups is the fourth tarot card in the Cups suit. The image shows a man sitting under a tree, intently looking at three cups. An arm protruding from a cloud is offering him a fourth card, which he is either ignoring on purpose or just cannot see. Not a wholly positive card, but not bad either, the Four of Cups can represent a mind that is sometimes so focused that it misses the bigger picture.",
        "normal": "The Four of Cups in the Past position can mean that you are recovering from something that happened in the past that you didn’t like. Think to some event that didn’t play out how you wanted it. Are you still thinking about it? how long has it been now? Time heals all wounds but doesn’t feel like you have to pretend to be happy when you aren’t. Did you miss something that you should have seen? Analyse the past as a bigger picture.",
    },
    "five of cups": {
        "title": "The Five of Cups is the fifth tarot card of the Cups suit. Taking a darker outlook, the Five of Cups is one of the negative tarot cards. The central character, clad in black faces three overturned cups, representing failure. Behind him are two upright ones. There is a certain positive aspect, not all is lost, but right now he is failing to see it.",
        "normal": "The Five of Cups in the Past position can mean that you are still thinking over something bad that has happened, possibly a long time ago. We frequently reach forks in the road of life and you may be feeling that one specific one has taken you the wrong way. It’s a dangerous business, walking. You step onto the road, and if you don’t keep your feet, there’s no knowing where you might be swept off to. In life, we often make mistakes but fail to see the lessons we learn from them. Good and bad experiences have the same value. Bad experiences teach us lessons so they are not repeated. Good experiences reward us for our good choices.",
    },
    "six of cups": {
        "title": "The Six of Cups is the sixth card in the Cups suit. The children suggest it’s a look back to childhood. The cups are not being used for their intended purpose, but inventively being used as a vase for flowers. A pleasant positive card which brings back warm memories of the past.",
        "normal": "The Six of Cups in the Past position means that you have had a standard and loving upbringing. You may have many good experiences of the past, especially during childhood. It’s nice to think about good memories. Don’t get carried away or think your golden years were in the past. You might also be thinking about a time in the past when you were very creative, but to you it seemed normal, like there was no other way around it. Peers however, thought it was an extremely good idea and that only you could have thought of it.",
    },
    "seven of cups": {
        "title": "The Seven of Cups is the seventh tarot card in the suit of Cups. The card is all about choices. The character is having a vision of 7 cups offering 7 different gifts and is having trouble deciding. One of the choices is different from the others; an objected veiled in a cloth. We can interpret this as viewing the future and the clouded choices that we make based on appearance and assumption instead of fact.",
        "normal": "The Seven of Cups tarot in the Past position means you might have wasted a lot of time in your past being indecisive. Sometimes, when there are too many choices we can become overwhelmed. Use past lessons if you’re facing a similar situation now. Likewise, don’t think about the other choices you could have made. You can’t change it now. Do the best with what you have. You may need time to examine your feelings to make a decision, but try to actively do this instead of keeping it in the back of your mind.",
    },
    "eight of cups": {
        "title": "The Eight of Cups is the eighth card in the Cups suit. The illustration shows a man walking away from a river, on the other bank are some cups stacked irregularly, leaving a large visible gap. Heading away, the man is abandoning his cups, the structure they created left unfinished.",
        "normal": "The Eight of Cups in the Past position means that a previous aspect of your life hasn’t worked out and you’re currently looking for something new. It might have gotten some way through but for whatever reason, you gave up on it. It might not have felt right, or you could have thought there were better things. This can be many things; a creative project, a relationship, a course of study. You have to break negative ties you to your past.",
    },
    "nine of cups": {
        "title": "The Nine of Cups is the ninth tarot card in the Cups suit. A positive card generally, the illustration shows a character sitting in front of a collection of nine cups, proudly on display. His big grin and folded arms give us a sense of completion; he has achieved.",
        "normal": "The Nine of Cups tarot card in the Past position shows a past success; something you’re really proud of. It’s still affecting your life and thoughts. Achievements in life are what we all live for, whether it’s a new job or an exciting holiday or winning at a sport. Don’t stagnate on one thing and be known as the person who did ‘that’, you have to move onto bigger and better things. However, there is no harm in looking back at what you have achieved and knowing that now, you’re able to do much better.",
    },
    "ten of cups": {
        "title": "The Ten of Cups is the tenth tarot card in the Cups suit and is an extremely positive card. The illustration shows ten cups suspended in a rainbow with a couple, likely married, looking at it. Children play in the foreground and an idyllic village lays in the background. The Ten of Cups is all about happiness and being positive.",
        "normal": "The Ten of Cups in the Past position can mean a few things. A positive upbringing with loved ones or a good place to grow up that has set you up for the world. Peace or a relative lack of conflict have been prevalent in your life so far. It can also refer to the past few years, which would have been relatively free of negativity.",
    },
    "page of cups": {
        "title": "The Page of Cups is the eleventh tarot card in the Cups suit. The illustration shows a young man dressed in blue, holding a cup in his right hand. A fish is looking out of the cup at the man, and he is looking back. The card shows the innocence and curiosity of our inner child, as well as large imaginations unrestricted by logic or experience. Like many cards in the Cups suit, it’s a positive one. Fish emerging from water could be a symbol of knowledge being imparted, much like Oannes of Sumerian mythology",
        "normal": "The Page of Cups tarot card in the Past position can clearly state your childhood if that is of any importance. If you’re focusing on the recent past, it relates to a particular event where you experienced a sort of inner childlike curiosity or possibly naivety. For better or worse you might not have understood a situation and the whole thing went over your head. The Page of Cups may also relate to a time you started a creative project, likely something tied to your passions.",
    },
    "knight of cups": {
        "title": "The Knight of Cups tarot card is the twelfth card in the Cups suit. The Cups are a positive suit, and the Knight of Cups is no different. With slight romantic undertones (think of the traditional Knight saving the Princess), the Knight of Cups is all about good news, and positive change.",
        "normal": "The Knight of Cups tarot card in the past position can represent a past time of good activity, definitely a high point in your life where you were progressing as you wanted to. You were reaching new horizons that you’ve since travelled far beyond. The Knight of Cups can also represent a past relationship, possibly your first serious relationship. It’s likely that there are either lessons to learn from it, or that your partner from then will appear back in your life.",
    },
    "queen of cups": {
        "title": "The Queen of Cups is the thirteenth card in the Cups suit. Thirteen isn’t really an unlucky number when it comes to The Queen of Cups, like most other cards in the Cups suit, The Queen of Cups is a positive one. It also has many possible interpretations, from the straight obvious meaning of a female influence in your life to interpretations of maturity and intuition.",
        "normal": "The Queen of Cups in the past position can mean reminding you of an influential female in your life. Usually, for the better, this people has helped you on your way. It could have been a good teacher or another parental figure, but this person has instilled some good values. It can also represent you in the past; particularly an event where you had to be passionate, patient and understanding. Art, or some other creative pursuit, might have been big in your life in the past. maybe look to rekindle that passion now?",
    },
    "king of cups": {
        "title": "The King of Cups is the fourteenth card in the Cups suit. Initially, as a King, you’d think the King of Cups is a mainly masculine card, but overall as Cups deal with emotions, it is quite a balanced tarot card. The King sits in a throne surrounded by water, holding a cup and a scepter in his hands.",
        "normal": "The King of Cups tarot card in the past position can represent you in the recent past. You may have been the arbiter in a conflict or argument, or it could refer to someone close to you who was; usually a male in a position of power. These events are still affecting how your life is being played out. Perhaps a decision was made, and you are still following it. It could also represent a time in the near past where you were very emotionally mature, perhaps when you thought about a choice or situation and acted on your good sense, instead of impulse or on negative emotion.",
    },
    "ace of wands": {
        "title": "The Ace of Wands is the first tarot card in the suit of Wands. It’s a positive card, if you’re in any sort of creative field then take it as an extremely good sign. As it’s an Ace, expect new beginnings, especially relating to creativity and that first spark of inspiration to set an idea in motion.",
        "normal": "The Ace of Wands tarot in the Past position can represent a past event when you just ‘went for it’. It probably has some effect on your life now, and you’re seeing the benefits or possibly negative effects of taking that one chance. It could have been something like a quick career change, a new person you met, or spontaneously going to a new place. The Ace of Wands in the past can also represent something life changing having happened in the recent past. Perhaps you found a new spiritual path to follow, or found a new passion which is slowly taking over your life, for better or worse.",
    },
    "two of wands": {
        "title": "The Two of Wands is the second tarot card in the suit of Wands. Two is an important number in western esotericism, and regularly represents the duality of life. The Two of Wands refers to the potential of everybody for widening their own worldview, and that many limits are only self-imposed.",
        "normal": "The Two of Wands in the Past position can represent a past event where you left your comfort zone, specifically with somebody you know. This event can still be impacting your life, likely in a positive way. The past, and future are two aspects of our life that we have little to no control over. We can only change the present to suit our will. Look to the past for inspiration, and look to the future with ambition, not worry.",
    },
    "three of wands": {
        "title": "The Three of Wands is the third card in the suit of Wands. A great card to see in a reading if there’s something you’re aiming for. The Three of Wands usually means you will attain your goals, through prior preparation and good foresight.",
        "normal": "The Three of Wands in the Past position can represent a past event where you were cautious and forward thinking. It could have been a time when you didn’t rush into something but stayed back for a while and considered all options. You may have been extremely mature for your age and held more responsibility than average.",
    },
    "four of wands": {
        "title": "The Four of Wands is the fourth tarot card in the suit of Wands. A largely positive card, you should expect good things to happen when you see it, especially when relating to work and career or that project that you’re working on. It’s going to be a time to celebrate achievements, and relax now that the hard work is over.",
        "normal": "The Four of Wands in the Past position can represent a consistent effort on your part finally paying off. If you keep going as you have kept going, you will master the your chosen area of work or study. It can also represent the recent completion of a major part of your life. maybe you’ve just finished a series of exams, gotten a new job or found a good partner.",
    },
    "five of wands": {
        "title": "The Five of Wands is the fifth card of the Wands suit. The Five of Wands is not a pleasant card and deals with conflict and sometimes aggression. The illustration shows five men fighting with wands, the victor, main aggressor or victim are all unclear.",
        "normal": "The Five of Wands in the Past position can mean that you are still thinking over something bad that has happened, possibly a long time ago. This could end in an argument, or a falling out. You might not even remember why it happened now. It’s come back to haunt you somehow, so you’ll need to find a way to iron out the issues. You might have gotten into an argument or disagreement with somebody in the past which is still relevant today; maybe it’s something you need to fix with that person or group.",
    },
    "six of wands": {
        "title": "The Six of Wands is the sixth tarot card in the Wands suit. The card resonates success and is a positive omen.",
        "normal": "The Six of Wands in the Past position means that may have many good experiences of the past, especially during childhood. It’s nice to think about good memories. Don’t get carried away or think your golden years, try to make the present just as great. Try to think what triggered those good feelings and bring them into the now.",
    },
    "seven of wands": {
        "title": "The Seven of Wands is the seventh card in the suit of Wands. A positive card in some respects; especially relating to contests or competitions. The Seven of Wands is closely related to your willpower, and meanings will change based on how determined you are in life.",
        "normal": "The Seven of Wands tarot in the Past position could mean that you’ve spent a lot of time, hard work and energy getting to where you are now, and it’s time to reap the rewards. You’ve had to push past and exceed others to get where you are now. It’s good to think how well you’ve done to get here, if you feel down, just think about your past journey. You might have been used to being the ‘best’ when you were younger, maybe you were the favourite child. Remember that things change in life and we cannot rest on our past successes.",
    },
    "eight of wands": {
        "title": "The Eight of Wands is the eighth tarot card in the suit of Wands. A completely enigmatic illustration for the Eight of Wands lends little initial help into even a sensible guess at its meaning.",
        "normal": "The Eight of Wands in the Past position can represent a time in the past when you acted rashly and it may not have paid off. Impatience is a tricky subject to deal with, everyone tackles it differently. Sometimes we have a mentality that it’s better to do something, anything, than nothing at all, even when doing nothing is the best course of action. Impulse, however, can lead us on to experience things we otherwise would have missed, so be grateful for any experience you gained; positive or negative.",
    },
    "nine of wands": {
        "title": "The Nine of Wands is the ninth tarot card in the suit of Wands. The previous cards in the wands suit have been mainly positive with exceptions, but the Nine of Wands is where the meanings start to take a more cautious approach.",
        "normal": "The Nine of Wands in the Past position has represented a past period or event where you were required to put in a lot of effort. You came out with a few scrapes and bruises but the thing to keep in mind is that you conquered it, whatever it was. This especially signifies something that you were initially afraid of. We always have trials in our life, how many times have you done something initially difficult and realised it wasn’t a big deal in the end? Our fears are usually absolved once we deal with the issue at hand",
    },
    "ten of wands": {
        "title": "The Ten of Wands is the tenth tarot card in the suit of Wands. As seen in the Nine of Wands, it isn’t as positive as early cards in the suit. The illustration shows a man burdened by the weight of ten wands. he can see his destination but has a long way to travel.",
        "normal": "The Ten of Wands tarot card in the Past position can represent past period where you were tied down. You’re free now but it is affecting your life. Do you feel as free as you should be? You certainly are. Take some time to think about the burdens you’ve freed yourself from. The Ten of Wands can represent a childhood where you needed to be more mature than others your age. It’s possible something devastating happened which required you to step up and take the reins.",
    },
    "page of wands": {
        "title": "The Page of Wands is the eleventh card in the suit of Wands and the first face card. As it is a face card, it could represent a real-life person, even someone that you know; likely a younger male influence in your life. The illustration on the Rider-Waite deck shows the Page inspecting a wand, well dressed and standing in front of a barren desert landscape.",
        "normal": "The Page of Wands tarot card in the Past position can represent, specifically, a person in your past who has affected your life. Likely a male, he had an adventurous and energetic personality. Maybe this was something you were jealous of. It can also represent the recent completion of something you were proud of, that is opening new doors for you. As childhood goes, the Page of Wands can represent you, seemingly more mature than others your age, you might have given yourself a good jump start in life.",
    },
    "knight of wands": {
        "title": "The Knight of Wands is the eleventh card in the suit of Wands. The Knight of Wands, much like the Page of Wands, exists in a barren desert. He even dresses similarly, with a salamander motif, though unlike the Page, he is moving at speed. The Knight has decided his goal and is on his way.",
        "normal": "The Knight of Wands in the Past position can represent a past time where you were spontaneous and acted quickly, although not without forethought; you were aware of the potential outcomes. You may have been extremely mature for your age as a child, or during school and you probably held more responsibility than average. Looking to the past might be a good thing to do for you now, especially if you had a different personality when you were younger than now.",
    },
    "queen of wands": {
        "title": "The Queen of Wands is the thirteenth tarot card in the Wands tarot suit. It’s likely to signify a positive, mature female influence in your life; especially someone with a good career, who is independent and honest. Without even reading the meanings, you might already have an idea of who it may be. She should be the sort of person to whom you could go for advice on any number of topics in life. The black cat is a sign of luck.",
        "normal": "The Queen of Wands in the Past position can represent a warm loving upbringing and consistent support throughout your childhood. In addition,  it’s likely that your mother, or a mother figure, had a career, as well as providing for your upbringing. This has had an effect on your life, it’s possible that you’re more career driven because of this. The tarot card can also mean that your childhood influence was unorthodox, but not wildly. You were able to consider other alternative ways of living and learning.",
    },
    "king of wands": {
        "title": "The King of Wands tarot card is the final card in the suit of Wands. The King of Wands embodies much of the meaning of the entire suit and should be taken seriously when seen. Much like the Queen of Wands, The King can represent a strong male influence in your life, somebody who has succeeded and lived their dream. You might find them quite inspiring. This could also represent you, having achieved your goals, meaning you are ready to help others with theirs.",
        "normal": "The King of Wands tarot in the Past position can represent a past event where you were cautious and forward thinking and acted more on theory than practice. It could be that your ideas of the past are finally coming into being now that you have the skills to create them. In the past, you might have been a leader of sorts. Look to recreate this energy now by doing the same. You are likely a good leader, especially in regards to your knowledge and experience.",
    },
    "ace of swords": {
        "title": "The Ace of Swords is the first card in the suit of Swords. All aces can mean a new start. Like a sword, the actions that bring forth this new change can act quickly and without warning. Aces regularly represent a new beginning, coupled with Swords, this suggests a new personal goal or worldview. You may see yourself coming out of your shell soon.",
        "normal": "The Ace of Swords in the Past position can represent a past event when you planned ahead and acted quickly. It probably has some effect on your life now, and you’re seeing the effects of researching everything and acting when the time was right. For example, you may have noticed trends and acted at the right time. Following your instinct has led you to where you are now. Others may have thought you were quick on the ball to adapt to a new trend, and it’s worked in your favour.",
    },
    "two of swords": {
        "title": "The Two of Swords is the second tarot card in the suit of Swords. Two is a common number in esoteric study and understanding; balance, two halves of one whole, male and female, good and bad. This is a balanced card; not wholly about action itself, but more focusing on what to do with the information you have.",
        "normal": "The Two of Swords in the Past position can represent a period of your life where you felt stuck. Decisions could be made to help you out, but you kept putting it off. We have to be aware of our actions, inaction is sometimes even the right choice, but don’t let that become a way of life. You can’t avoid everything.",
    },
    "three of swords": {
        "title": "The Three of Swords is the third tarot card in the suit of Swords. As you may have deduced from the illustration, the Three Swords is not a wholly positive card, especially when it comes to love.",
        "normal": "The Three of Swords tarot card in the Past position can represent an intense period of depression that has affected your current life and mindset greatly. We can always learn from these experiences. It’s important to treat the past objectively. The reason bad experiences are ‘bad’ is so we can learn from it so that it doesn’t happen again.",
    },
    "four of swords": {
        "title": "The Four of Swords is the fourth tarot card in the suit of Swords. The illustration shows the tomb of a knight in prayer, three swords adorn the wall and one is engraved on his tomb.",
        "normal": "The Four of Swords in the Past position can represent a period of time in the past where you were focused or obsessed with one thing. This may have kept you from interacting with others or sharing, and it has truly affected your life now. You may also have dealt with something traumatic or shocking that changed you as a person, and you’re only just recovering from it; a breakup or a death, perhaps.",
    },
    "five of swords": {
        "title": "he Five of Swords is the fifth card in the suit of Swords. When you see the Five of Swords, you should prepare for some conflict to come into your life. It might not be something to be scared of, but life is about to get at least a little bit more difficult. Don’t worry, you can always see it through.",
        "normal": "The Five of Swords tarot in the Past position will represent a period in your life when you had no solid foundations to fall back on. You came out of it though, and now you’re here. We all see failure in our lives, but it’s only through learning from them that we grow. Great people aren’t just great. They have tried and failed and built up their own foundations.",
    },
    "six of swords": {
        "title": "The Six of Swords is the sixth tarot card in the suit of Swords. A more positive card than the most recent cards in the Swords suit; the worst is likely over and you’re ready for some change and growth in life.",
        "normal": "The Six of Swords in the Past position can represent a period of conflict in the past that you managed to overcome or escape from. It can also represent somebody who has ‘saved’ you from a period of your life when you felt like you were stuck in a rut. You’re out now, and life has improved since.",
    },
    "seven of swords": {
        "title": "The Seven of Swords is the seventh tarot card in the suit of Swords. The illustration is particularly apt here; your first thought is likely a good insight into what the card means. The cards usually symbolise the person receiving the reading, but in this case, it’s sensible to consider all possibilities. The important thing isn’t to jump to conclusions when you read the meanings below.",
        "normal": "The Seven of Swords card in the Past position could mean a past period of conflict, but more strongly signifies a time when somebody went behind your back to do something either to spite you, or otherwise through malice. It’s affected how you think and feel, but luckily you’re aware of it now. You’re learning to trust people again.",
    },
    "eight of swords": {
        "title": "The Eight of Swords is the eighth tarot card in the suit of Swords. The illustration is somewhat frightening; a blindfolded woman surrounded by swords. She doesn’t know what to do, but inaction also isn’t a good choice. There is a way out, but more likely than not it will be painful.",
        "normal": "You might feel trapped in the past but you’re away from that now and experiencing a new level of freedom. You remember the struggles it took to get you to where you are now, it was certainly painful. Recognise what led to that position and try to avoid it in future. This could relate to a job you just didn’t enjoy, a place you were living, people you didn’t like being around but are now free from.",
    },
    "nine of swords": {
        "title": "The Nine of Swords is the ninth tarot card in the suit of Swords. A largely negative card, the illustration shows a man awakening from a nightmare, filled with grief. Nine swords are suspended on the wall at his bedside. His blanket is a patchwork quilt of red roses and zodiacal symbols. The Nine of Swords is widely regarded as a ‘bad’ card to draw, but take your whole reading into account when you interpret it.",
        "normal": "Stress and worry are a large part of your recent past. Life may have gone through a shift that you’re just recovering from. It might have been extremely eventful and traumatic. Don’t assume that future interactions will have the same outcome as they have had in the past. Life isn’t set, but dynamic, and things changed over time.",
    },
    "ten of swords": {
        "title": "The Ten of Swords is the tenth tarot card in the suit of Swords. Running with the recent trend of the suit of swords; the Ten of Swords is not overly positive. The illustration somewhat backs this up; a man lying motionless on the ground with ten swords in his back. The Ten of Swords is regarded as the most destructive and grim card in the deck, but consider your entire reading when you interpret meanings.",
        "normal": "The Ten of Swords in the Past position can relate to a past event or time in your life where everything went wrong. You were at complete rock bottom. Despite this, here you are. You’ve grown from the experience, and while it was something you’ll remember for your life, it’s helped you grow as a person. Past lessons that led to it happening should be deeply ingrained in you so you don’t make the same mistakes again. Still, the echoes of the past can still come back to haunt you. Instead of being scared, use bad memories as lessons so they are not repeated.",
    },
    "page of swords": {
        "title": "The Page of Swords tarot card is the eleventh card in the suit of Swords, and the first ‘face’ card. Just coming from the Ten of Swords, the Page of Swords is a step up in terms of positive energy. Face cards can stand for a real person in our lives, in this case possibly someone younger than the receiver of the reading but could as well be the person receiving the reading.",
        "normal": "The Page of Swords in the Past position can represent a past event where you were a little too ambitious and focused. It could have been a time when you experienced a vision of what you wanted your life to turn out like, and it gave you great motivation. You went for it, but you may have alienated others that would have helped you. Are you an arrogant person? It might be time to reflect and learn lessons.",
    },
    "knight of swords": {
        "title": "The Knight of Swords is the 12th tarot card in the suit of Swords. A slightly more positive card, especially relative to the other cards in the swords suit so far. You should expect better things to happen when you see it, especially any news regarding a younger male you might know. Expect to receive good ideas if you’re stuck, or other good unexpected news.",
        "normal": "The Knight of Swords tarot in the Past position can represent a history of working to the numbers and being clear cut. You might have worked in an authoritative job or otherwise been in charge of people. If you’re still doing this, consider if it’s the right choice; you may have outstayed your welcome both for the people you work with and your own personal growth. As a child, or as your younger self, you may have had a clear direction in life. It’s likely you had a dream job as a child. Realize that if you’ve given up on this in the interim, it’s still possible to achieve something just as fulfilling now.",
    },
    "queen of swords": {
        "title": "The Queen of Swords is in the Minor Arcana and is the 13th tarot card in the suit of Swords. Usually, the queen will represent somebody in your life, most likely a mature woman who is quick to anger. Without even reading the meanings, you might already have an idea of who it may be.",
        "normal": "The Queen of Swords tarot card in the past position can represent you, or someone in your life in a position of authority. Commonly, this can be a female teacher or another female that had a great influence on you, very likely your mother. Use this person as an example when you’re having problems in life; it might sound silly, but what would they do in your situation? Sometimes getting another viewpoint can really change how we perceive situations. visualising somebody much older and wiser can make us feel like we can use their experience and wisdom.",
    },
    "king of swords": {
        "title": "The King of Swords is the final card in the suit of Swords. The King of Swords embodies much of the meaning of the entire suit and should be taken seriously when seen. Much like the Queen of Swords, The King can represent a strong male influence in your life, someone with authority and power.",
        "normal": "You may have been extremely mature for your age and held more responsibility than average. People considered you to have authority over a subject, you were the ‘go-to’ person for it. Life may or may not be the same now, but the lesson to learn is that you can always harness that sort of power if you dedicate yourself to it. The King of Swords could also represent your father, probably a strict man. You may have had a rigid upbringing, but be grateful, structure can help us create and achieve goals in life.",
    },
    "ace of pentacles": {
        "title": "The Ace of Pentacles is the first tarot card in the suit of Pentacles. A largely positive card, you should expect good things to happen when you see it. Pentacles represent material possessions and wealth. Pentacles in tarot are also sometimes called Coins. The pentacle itself is a well-known symbol with many meanings and interpretations in many faiths, notably Wicca. The Ace of Pentacles is well regarded as a favourable card to receive in a reading.",
        "normal": "The Ace of Pentacles tarot in the Past position can represent coming from a privileged background. A well cared for childhood, for example, or something more recent. Maybe you’ve set yourself up very well and prepared for what is coming. You could recently have started a new life, perhaps you have just moved somewhere. It has been a very positive move in any case, and you should see the benefits soon.",
    },
    "two of pentacles": {
        "title": "The Two of Pentacles is the second tarot card in the suit of Pentacles. Two is a common number in esoteric study and understanding; balance, two halves of one whole, male and female, ups and downs, good and bad. Generally, a positive card, the Two of Pentacles can remind us to respect the balance that our lives require.",
        "normal": "The Two of Pentacles in the Past position can represent a life of constant change and adaptation. You may have moved locations or changed greatly as a person. Think about the good aspects of each and keep them, try to get rid of the bad habits. In that recent past, you may have had to make a choice between two things, two major paths in life. You have chosen and are living with the consequences of that choice.",
    },
    "three of pentacles": {
        "title": "The Three of Pentacles is the third tarot card in the suit of Pentacles. A largely positive card, you should expect good things to happen when you see it, especially when relating to work and career.",
        "normal": "The Three of Pentacles in the Past position can represent an intense period of study that is going to pay off. It can also mean that you’ve worked hard to get where you are now. If you keep going as you have kept going, you will master the subject you are studying. In the past, you may have been a bit of a mentor, and that may or may not be the case now. It was a good time to look back on, but remember that the path forward isn’t always an easy climb. We jump over obstacles and sometimes fall, so if the past looks brighter than the present, remember that despite the differences, you have grown as a person and are all the better for it.",
    },
    "four of pentacles": {
        "title": "The Four of Pentacles is the fourth tarot card in the suit of Pentacles. A somewhat positive card, you should expect some good things to happen when you see it. Watch out though, it has specific meanings that you might want to be careful with.",
        "normal": "The Four of Pentacles tarot card in the Past position can mean that you’ve set yourself up for the current position you’re in, most likely by hanging on to something in a material sense. Letting go of the past and breaking bonds is a natural way to move on, and sometimes a good way. It may seem difficult to even consider it, but thinking about it won’t hurt. It can also mean you may reconnect with something from your past; a childhood toy, or another lost item. Expect good memories to flood back.",
    },
    "five of pentacles": {
        "title": "The Five of Pentacles is the fifth tarot card in the suit of Pentacles. A quick look at the illustration gives a quick overview of the card depicts two men in walking in front of stained glass window, both look seem to be facing adversity and it is not a wholly positive card. When it comes up in a reading, prepare yourself for news you hadn’t hoped for.",
        "normal": "The Five of Pentacles in the Past position can represent a past time when you were poor or missing out in a way. Maybe you couldn’t go somewhere or do something you wanted for reasons out of your control. If you stopped yourself doing something, it’ll be helpful to think about why maybe you’ve set up self-imposed emotional barriers. growing up in poverty and lacking can make us more grateful, which is a quality everybody loves to see in others.",
    },
    "six of pentacles": {
        "title": "The Six of Pentacles is the sixth tarot card in the suit of Pentacles. A more positive card than the most recent cards in the Pentacles suit; things are starting to look much more positive and also mature now. Expect to see things how they really are, and to understand how much of a positive change you can make in the world.",
        "normal": "The Six of Pentacles in the Past position can represent past generosity, from you or somebody else. Someone may have given you a great opportunity, although it’s more about things playing through the motions than you going out of your way to get it. You were following a path and reached the goal, which is where you currently stand. To give an example; it could mean that you’ve gone through a period of education and ended up somewhere you wanted initially, but now you’re unsure.",
    },
    "seven of pentacles": {
        "title": "The Seven of Pentacles is the seventh tarot card in the suit of Pentacles. A positive card from the minor arcana, you should expect good things to happen when you see it. The illustration shows a man growing crops (crops of Pentacles) and peacefully watching over them. He has put in the effort to nurture them to grow and is about to reap the reward of his prior hard work.",
        "normal": "The Seven of Pentacles card in the Past position could mean that you’ve spent a lot of time, hard work and energy getting to where you are now, and it’s time to reap the rewards. You may have excellent knowledge that you can help others with, especially people who are starting out in the world.",
    },
    "eight of pentacles": {
        "title": "The Eight of Pentacles is the eighth tarot card in the suit of Pentacles. A positive card, you should expect good things to happen when you see it; especially aspects relating to a creative industry, or a project or part of your life that you have worked extremely hard on and dedicated yourself to. A good card to draw if you are intent on learning a skill or trade which you have a lot of passion for.",
        "normal": "The Eight of Pentacles tarot card in the Past position can represent a path you are currently on, which you’re putting effort into. You might need to think clearly, or maybe it will be obvious. What are you truly exerting yourself on? Are you really putting in the hours at work, are you extremely dedicated to your family or partner? Be aware that this dedication will pay off in future. it can also represent an ambition or hobby you had as a child, which you were extremely dedicated to. If you’re looking for inspiration, childhood is always a good place to find it.",
    },
    "nine of pentacles": {
        "title": "The Nine of Pentacles is the ninth tarot card in the suit of Pentacles. Similar in appearance to The Seven of Pentacles with the plant imagery, but with stark differences. The illustration in the Seven of Pentacles shows a man resting after work and enjoying what he started a while ago, whereas the Nine of Pentacles shows a woman casually enjoying a garden, with no signs of labour, though a Falcon rests on her left hand.",
        "normal": " The Nine of Pentacles in the Past position has a few interpretations, and it’ll depend on what you had in mind when you dealt with the spread. Did you have a spoiled childhood where everything was taken care of for you? Did you have well-off parents? It might be affecting you now, and you may be finding it harder to relate to those less privileged. Having a good foundation for life can benefit us in many ways, so be grateful for where you have come from.",
    },
    "ten of pentacles": {
        "title": "The Ten of Pentacles is the tenth tarot card in the suit of Pentacles. It is a positive card in terms of material retention, don’t expect to be needy or in want of something you desire.",
        "normal": " This tarot card in the Past position can represent a good financial foundation in your life. You may never have had to worry about money, or at least nowhere near to the degree that your peers do. Similar to The Nine of Pentacles, The Ten of Pentacles suggests that you might not have earned this foundation at all. Although this might sound like a bad thing, you aren’t arrogant or ignorant because of it , so you’ve gained the best of both worlds.",
    },
    "page of pentacles": {
        "title": "The Page of Pentacles is the eleventh card in the suit of Pentacles, and the first ‘face’ or ‘court’ card. A largely positive card, you should expect good things to happen when you see it, especially in any areas concerning long term goals or progression. The Page of Pentacles in tarot readings grounds us in the ‘real world’, so that we can manifest our dreams as tangible goals to achieve.",
        "normal": "The Page of Pentacles tarot card in the Past position can represent a past event where you were ambitious and concentrated. It could have been a time when you experienced a vision of what you wanted your life to turn out like, and it gave you great motivation. Do you need something like this now? Think back to that past time and try to remember how you felt to further motivate yourself and keep the dream fresh.",
    },
    "knight of pentacles": {
        "title": "The Knight of Pentacles is the 12th tarot card in the suit of Pentacles. A  positive card, you should expect good things to happen when you see it, especially any news regarding a younger male you might know. As you may expect, the card embodies some knightly qualities; things many of us would do well to aspire to.",
        "normal": "The Knight of Pentacles in the Past position can represent a past event where you were dedicated, loyal or responsible. It could have been a time when you were in charge of something. Do you need something like this now? If you’re struggling now, think back to that past time and try to remember how you felt to further motivate yourself. You might need to put things into perspective and work by priority.",
    },
    "queen of pentacles": {
        "title": "The Queen of Pentacles is the 13th tarot card in the suit of Pentacles. Usually, the queen will represent somebody in your life, an older woman, who has a very comfortable life. Without even reading the meanings, you might already have an idea of who it may be. Many draw parallels between The Queen of Pentacles and the concept of Mother Earth; a nurturing feminine spirit that takes care of us if we take care of her.",
        "normal": "The Queen of Pentacles tarot card in the Past position can represent a warm loving upbringing and consistent support throughout your childhood. You probably had a very stable and loving family, probably more so than others you’ve known. The Queen of Pentacles can also mean that you’ve learned all the lessons in your childhood to grow into a well rounded and solid individual. You don’t want to make the mistakes your parents made and you want to grow to be a good foundation for others.",
    },
    "king of pentacles": {
        "title": "The King of Pentacles is the final tarot card in the suit of Pentacles. The King of Pentacles embodies much of the meaning of the entire suit and should be taken seriously when seen. Much like the Queen of Pentacles, The King can represent a strong male influence in your life; likely somebody who is well off in a material sense.",
        "normal": "The King of Pentacles tarot in the Past position can represent a past event where you were cautious and forward thinking. It could have been a time when you didn’t rush into something but stayed back for a while and considered all options. You may have been extremely mature for your age and help more responsibility than average.",
    },
}
