present_deck = {
    "the fool": {
        "title": "It might sound bad from the name, but The Fool tarot card is not a negative card at all! In fact, it’s associated with the number zero – the number of infinite potential. In the Major Arcana, The Fool represents you, the main character,  journeying through life. So, when The Fool shows up in your reading, get ready for major change and transformation! The Fool tarot card is all about living in the present moment and enjoying your life without worry. Just look at how happy the man in the card is in spite of his treacherous surroundings. Sometimes we need to take a little risk, even if we aren’t sure how things will turn out, because, if we never try, we will never know what could have been! The Fool reminds you to stay true to your heart and follow your dreams.",
        "normal": "When The Fool shows up in the present position of your tarot spread, he is encouraging you to go for it! Is there an exciting possibility ahead that you’re feeling a little nervous or unsure about? The message here is to seize the day! Don’t be afraid to be spontaneous! Go ahead and follow your heart. The Fool tarot card in the present position is a very powerful card. Take a chance and enjoy a fresh start if your heart is calling you to do so. Let your inner child play and try not to let responsibilities and commitments dictate your life.",
        "reversed": "Take a moment to make sure you’re not acting recklessly when this card appears in the reverse. Keep your wits about you and don’t lose your head! You don’t want The Fool’s childish innocence to lead you right off of a cliff! However, if you’re missing a great opportunity because you’re too afraid to take a risk, then this reversal is asking you to trust in the universe and jump in!"
    },
    "the magician": {
        "title": "You’ve got what it takes to make it happen! That’s the general message of The Magician tarot card. With diligence and focus, you can create anything you desire, but you have to be deliberate in your actions and choices. Use your willpower and don’t underestimate your own abilities. Sometimes we don’t realize everything we have available to us. The Magician encourages us to have confidence and to be resourceful.",
        "normal": "You’ve arrived at a place in your life where you have everything you need to manifest your dreams and ambitions, but the time is now! Everything that you want is easily at your disposal, you just need to engage your determination and willpower to make it manifest. The Magician is a powerful card to receive, especially in the present position! Whether you are looking for love or a career change, this tarot card encourages you to dream big and go for it!",
        "reversed": "It’s time to take action to make your dreams come true, but you seem to be resisting. A reversed Magician indicated untapped potential. Additionally, it can indicate manipulation, so whether it’s indicative of someone in your life, or of your own behavior, take action to correct it."
    },

    "the high priestess": {
        "title": "The High Priestess is the guardian of your intuition, indicating that it can be a powerful indicator that you will need to trust your feelings when it comes to love and romance. Difficulties can develop when you ignore your intuition and follow only your conscious mind",
        "normal": "Can you tell the difference between your thoughts and your intuition? When the High Priestess emerges in your reading, she is guiding you to a place of quiet self-reflection. This tarot card represents sacred knowledge and wisdom, so getting it in the present position advises you to look for answers within. When you stop the mental chatter and listen to your heart, do you already know what the “right” answer is? Try to clear the mind of fears and worries and listen to what feels right to you. Pay attention to your feelings and your dreams, and everything else that is being revealed to you beneath the surface.",
        "reversed": "Whatever situation is unfolding in your life right now, it’s a good idea to pause and take some time for introspection. Don’t force your will or try to rationalize solutions. We always need to use our minds to solve problems, but without listening to our inner voice, we often end up with solutions that don’t work for us in the end. The High Priestess in reverse in the present position is telling you that your intuition is very important at this current moment."
    },

    "the empress": {
        "title": "It’s time for you to stop and smell the roses! The Empress takes the time to enjoy and appreciate all of the finer things in life, and she’s appearing in your reading to remind you to do the same. She is Venus, the ruler of love, art, and beauty, and represents fertility of all kinds. Whether your reading is about romantic relationships or your career, the message of The Empress is to bring your creative ideas and pursuits into the physical world. But, if she’s showing up in the reverse, it might be that you’ve gone too far into luxury and enjoyment! A reversed card always means that the qualities of that archetype are too extreme. In reverse, The Empress suggests that too much of a good thing can lead to laziness and co-dependence.",
        "normal": "You are in a wonderful place in your life right now. You feel secure and know that love and abundance are available to you. If you’ve recently started a creative project, you are seeing it flourish and grow. Stay connected to your gratitude and express your appreciation as often as you can. Abundance begets abundance in all forms.",
        "reversed": "The Empress has appeared in the reversed position, which means that the energies of her archetype are out of balance. Either you are neglecting yourself and not nurturing yourself the way you should, or you’ve fallen into laziness and codependency. Take a look at how you are spending your time and energy and try to find a healthy balance as you move forward."
    },

    "the emperor": {
        "title": "The Emperor uses power and organization to accomplish his goals. He is wise and powerful in his ways, and in the upright, can act as a protector. This card in your reading can represent your current energy, or can also represent a boss, father figure, spouse, or system of authority that is prominent in your life. When he appears in the reverse, The Emperor is tyrannical. He is overly rigid, lacks empathy, and won’t think twice about using force to get what he wants, even at the expense of others. The energies of this Major Arcana card are a powerful influence for good or for bad.",
        "normal": "It looks like your life is pretty well under control and you have found a way to create an organized and structured environment for yourself. Whether it’s your home life, your community or your workplace, the rules are predictable and life is relatively stable. There may be an authority figure in your life who is guiding you. In the upright position, The Emperor reminds you that authority is on your side.",
        "reversed": "Be careful of someone who might be wanting to take over in your life, at home, at work, or in your social circles. When The Emperor shows up in the reverse, it puts you on notice to stand your ground and hold your boundaries firm. Don’t allow yourself to be swayed or walked all over by anyone, especially those in positions of power! Alternatively, this Major Arcana card could represent your energy, in which case you might need to self-reflect to see if you have become too overbearing or controlling with others in your life."
    },

    "the hierophant": {
        "title": "Sometimes The Hierophant is referred to as The Pope of the priest of the Major Arcana. The Hierophant mirrors The High Priestess in the same way that The Emperor mirrors The Empress. This Major Arcana card is a masculine card representing structure and tradition but is focused on the spiritual realm. He is a card of religious doctrine, which values faithful devotion to traditional religious practices as a means of reaching spiritual fulfillment.",
        "normal": "Are you exploring a new spiritual group or community? Although you might be leaving behind some individuality, this new sense of belonging will open up new doors for you. Through regular spiritual practice, the mysteries of the universe will gradually be revealed to you.",
        "reversed": "The Hierophant in reverse could be warning you that you’re currently involved with a spiritual community that is tending toward dogma and intolerance. Although we can learn a lot from tradition and society, we must never lose our individuality. Always use your own judgement, and if something feels wrong, listen to your intuition and maintain your values."
    },
    "the lovers": {
        "title": "The Lovers card has landed in your tarot card spread to signify a beautiful relationship in your life! There is clear communication and an ability to be vulnerable with one another. This card often signifies a sexual relationship, though it doesn’t have to be. This Major Arcana card also represents choices. It seems that an important decision will be coming up in your life, so the surrounding cards of the reading will be very important!",
        "normal": "If love hasn’t captured your heart yet, it’s about to! In the present position, The Lovers tarot card indicated that love is right around the corner. And if you are already in a relationship, it’s about to evolve to a new level. Because this card also represents choices, you may need to make a decision about your level of commitment, whether to another person or your career or family. Some sacrifice might be called for if you want to commit fully.",
        "reversed": "There is a significant imbalance in your relationship when The Lovers card pops up in the reverse. Communication may have broken down, or maybe the partnership has become cold and detached. It’s important to be honest with yourself and your partner and communicate your fears and desires clearly."
    },
    "the chariot": {
        "title": "The Chariot represents overcoming obstacles after a long journey or hard-won battle. Depending on where this tarot card appears in your reading, the message is one of maintaining focus and confidence in the pursuit of your goals. The Chariot card suggests that your strength and commitment is being tested by the universe, so don’t give up or look for shortcuts. Are you pushing yourself ahead at break-neck speed to the point of obsession? This might be why The Chariot is showing up in the reversed position in your tarot card reading. If the pursuit of victory is becoming excessive, you might actually be standing in your own way. If you’re lacking direction and feel yourself floating aimlessly, a reversed Chariot card will also appear in your reading. Whether your willpower and focus is excessive or lacking, the goal is the same: bring these energies into a healthy state of balance.",
        "normal": "Success is at hand and your hard work is paying off! The Chariot is bringing you to the finish line of your race, and you’ve arrived in first place. This Major Arcana card also represents duality, because the charioteer has to manage the two sphinxes pulling his chariot. They can pull in opposing directions, so you must remain focused.",
        "reversed": "Are you feeling like you’ll never succeed? Are you running out of steam because it seems like your struggles go on and on? The Chariot card in the reverse suggests that you’re low on focus and determination. Stay focused on your direction and don’t allow turns and detours to dissuade you. With continued dedication you will arrive victoriously. Keep going!"
    },
    "the justice": {
        "title": "You can expect a fair outcome to a challenging situation in your life! If you have acted with integrity toward others but you have been wronged or hurt, the Justice card assures you that karma will be brought back into balance. However, if you have made decisions that harmed others, the Justice card comes as a warning. Justice demands truth and honesty, so a reversed Justice card indicates gossip, misinformation, and lies. You may have behaved in ways that were morally questionable and you are failing to take responsibility for your choices. Be fair in your choices and be sure to seek out the facts before making any judgements or assumptions about others, and make an effort to right the wrongs you committed before Justice does it for you.",
        "normal": "Karma is about to be served in your favor! The truth is coming out and those who harmed you are going to be forced to take responsibility. A big decision is at hand, and the outcome will be guided by fairness and accountability. If you are involved in a legal battle, it will be decided in your favor.",
        "reversed": "Justice in the reverse is warning you that you are involved in a corrupt or dishonest situation. Someone may be seeking retribution or is avoiding taking responsibility for something they did. If you have been engaging in dishonest behavior, you are being advised to take responsibility and to correct the situation right away."
    },
    "the hermit": {
        "title": "The Hermit is the soul searcher and is here to encourage you to reflect on your deepest feelings and needs. The appearance of this Major Arcana card in your tarot card reading heralds a time for pause. There is often a major turning point around the corner. A new path may be opening to you that you have been unable to see because of the noise and distractions in the outside world. Sometimes life forces us into retreat and sometimes it’s by choice, but either way, it is from the darkness that we find the light. When the energies of The Hermit are out of balance, he will present in your reading in the reversed position. This can indicate escapism rather than self-reflection, or a resistance to looking within for answers.",
        "normal": "You are currently in a period of retreat and withdrawal. You are reflecting on your life path and what truly matters to you. Have you been discarded by a loved one recently? Are you feeling lonely and isolated? Are you withdrawing from the world to avoid something negative or is your retreat nourishing your soul? The Hermit asks you to look within to discover how you got to this place. If something painful happened to you, what can you do to prevent this from happening again in the future? Sometimes we trust the wrong people or fail to set firm boundaries. A time of introspection can guide you toward greater self-love and lift you up into a higher vibration.",
        "reversed": "Are you feeling lonely, isolated, or abandoned? Or are you maybe hiding away from society in order to avoid dealing with difficult situations? The Hermit in reverse indicates that the introspective qualities of this card are out of balance. Don’t resist honest self-reflection and don’t hide away from the world either! Give yourself the space to hear your inner voice and then take action based on what you discover."
    },
    "the wheel of fortune": {
        "title": "Fate and destiny are about to kick in so get ready for some major changes. This can apply to your romantic relationships, career, health, or any other subject you are delving into with your tarot card reading. Our lives are made up of a series of cycles, and The Wheel of Fortune makes an appearance when one cycle is about to end so that another one can begin. One thing we know for sure is that things always change. The Wheel of Fortune is generally associated with good luck, but if it appears in the reverse, it’s suggesting that you’re resisting change. Or maybe you’ve got yourself stuck in an endless cycle of repeating patterns. Sometimes even “bad luck” leads to positive change, we just can’t see it until afterward.",
        "normal": "It’s time to celebrate! The Wheel of Fortune in the present position means luck is on your side! You are about to have a wonderful stroke of luck or swift resolution to your problems. Because this card deals with karma, these changes often deal with long term challenges within relationships or personal struggles and challenges. And if your life has been smooth sailing, The Wheel of Fortune doesn’t predict disaster, but rather asks you to appreciate what you have.",
        "reversed": "You never know where on the wheel you will land – on the top or on the bottom – so be sure to express gratitude when fortune is on your side. If The Wheel of Fortune appears in the reverse, it’s asking you to surrender to change. Resistance will only cause more problems because the cycles of life and change are something we can never control"
    },
    "the strength": {
        "title": "The Strength card follows The Chariot in the Major Arcana series. After we learn to use our strengths externally to overcome the stumbling blocks on your path, we must also learn more compassionate and refined ways of achieving our goals. The lesson of the Strength card is that we do not need to control others in order to succeed. We can rely on stamina, patience, and understanding to maintain harmony and balance in our lives.",
        "normal": "Kudos to you for maintaining your composure through challenging times! Your non-confrontational nature is allowing you to handle difficult situations gracefully. The Strength card making an appearance in the present position of your tarot card reading is an excellent indicator of collaborative relationships and working with others in a cooperative way.",
        "reversed": "If reversed, take a breath and find your center! Although our base emotions are natural, they do not necessarily help us to achieve the best possible outcome. Try to release your negative feelings in a safe way and then look to reconnect to your compassion and patience. Inner strength and serenity will guide you through rough times."
    },
    "the hanged man": {
        "title": "Are you trying to control things, but you’re not getting the results you want? It’s time to take the advice of The Hanged Man. This tarot card tells you to take a pause so you can gain a new perspective on your situation. This card is all about choosing to surrender to the flow of the universe. You received this card in your tarot card reading because there is some situation in your life that you need to respond to in a new way.",
        "normal": "Take a breath and walk away from conflict! The Hanged Man in the present position is telling you not to fall into the trap of engaging in conflicts with other people. If you are in a toxic relationship, try to just recognize it for what it is, and take the steps to remove yourself from it. When we say surrender, we don’t mean give up and give in, it means surrendering to the notion that the situation is what it is. We cannot control other people’s behavior, only our own choices, so rather than trying to fix the situation, you should take steps to protect yourself.",
        "reversed": "Are you keeping yourself super busy in order to avoid addressing a difficult situation? Or conversely, you might be procrastinating! Try to find equilibrium when it comes to any challenges you might be facing at this time. Look at your choices and actions honestly and try to remain open-minded. If you have been stuck for quite some time, this card in the reverse might indicate that the waiting period is finally coming to an end."
    },
    "the death card": {
        "title": "The Death card of the Major Arcana is symbolic of endings, allowing a chapter of your life to “die” so that a new one can begin. It’s not always easy to let things go. Accepting endings can be painful. But it is important to remember that what is in store for you is likely to be even better than what you are leaving behind. Everything in the world works in cycles, so embrace the endings so you can look forward to the new.",
        "normal": "You’re in a challenging situation right now and you know that you have to let something go. The change that is upon you right now can’t be stopped. If you can accept that this is the way things need to be, you will soon discover something new and beautiful on the other side. Change can hurt, and the emotions around that are normal. But if you can surrender to the universe and understand that you are opening the door to blessings, even if you can’t see how things will unfold, your transition will be easier for you.",
        "reversed": "Don’t resist the change that is upon you right now. The Death card in the reverse shows that you are trying to prevent an inevitable change from happening. But we cannot control or prevent change, in fact, it will only make things more difficult for you in the long run. A deep inner purging might be indicated."
    },
    "the temperance": {
        "title": "On The Fool’s journey through the Major Arcana, The Temperance card comes up after the Death card. It’s often the painful things in life that become our greatest teachers. When life asks us to let go of something that is very important to us, we begin to learn non-attachment. Temperance has discovered that adaptability, trust in the universe, and moderation brings us the greatest peace. When we surrender to the flow of the universe, we can begin to live an enlightened existence.",
        "normal": "Temperance has presented in your tarot card reading as a reminder to remain calm and patient in the face of any adversity. Are you dealing with a tough situation or relationship? Hang onto your grace and composure and all will be well.",
        "reversed": "Are you falling into some extreme tendencies? Maybe you’re sinking into some negative thought patterns, or overindulging in something while neglecting your responsibilities. Temperance in reverse asks you to strive to bring some balance back into your life."
    },
    "the devil card": {
        "title": "It’s easy to lose sight of the fact that nobody else is responsible for our happiness and that no matter how hard we try, we can’t find happiness in the external world. This is how addictions and attachments develop. The Devil card exposes our tendency to shift responsibility, whether it’s by adopting the victim mentality or by numbing ourselves with carnal pleasures. Until we learn to generate happiness from within, we choose to remain chained, so to speak.",
        "normal": "When The Devil card makes an appearance in your present position it’s a warning to do some honest soul searching. Are you running from your problems? Are you numbing the pain instead of dealing with the situation head-on? The Devil card indicates that we have chosen to become slaves to something. Maybe it’s work, maybe it’s too much exercise, maybe it’s drugs or relationships that fill a hole but don’t really mean anything to you on a deeper level.",
        "reversed": "In the reverse, The Devil card indicates a time of honest self-reflection and responsibility taking. You probably already know which areas of your life have become toxic. Now is the time to face them head-on and make the change. The time of codependency and attachment can be a thing of your past."
    },
    "the tower": {
        "title": "In its essence, The Tower represents a groundbreaking change. It doesn’t always foretell chaos and destruction, though by the look of the card you might think so! Lighting strikes a stone tower and people are jumping from the windows to escape the flames. This card follows The Devil card in the Major Arcana, and the message is clear: do not resist change or the universe will force it upon you.",
        "normal": "When the world is falling apart around you there is no sense in sitting around and going down in flames. Jump to your freedom while you still can. There is a great upheaval in your life when the Tower card appears in the present position. There is no stopping this change because the faulty foundations have been exposed. However, this can really be seen as a blessing, because the illusions and lies will also go down in flames!",
        "reversed": "You may have just narrowly missed a traumatic situation. Phew! The Tower in reverse indicates that a major upheaval was either delayed or avoided. If you are aware of negative or false influences in your life that need to go, make the move now. Otherwise, the Tower will crop up again later to finish cleaning house."
    },
    "the star": {
        "title": "You’re wishing upon a star when this Major Arcana card makes an appearance in your tarot card reading, and the good news is that your wishes are about to come true! Will it be new love, or taking your relationship to the next level? The energies of hope and faith surround you and are supporting you in a brand new path or direction. You have a lot to be optimistic about because the universe is blessing you at this time.",
        "normal": "Are you falling in love with someone new or a new idea? You’re surrounded by hope and inspiration right now. The Star card in your present position is a symbol of your innermost wishes and dreams and you are about to begin a new journey! But because this Major Arcana card also represents purity and vulnerability, do be sure that you aren’t seeing things through rose-colored glasses. We want to stay connected to our purset desires, but also keep one foot on the ground.",
        "reversed": "You need to go outside tonight and look at the stars and remember that wishes can come true! The Star in reverse is telling you that you’ve lost hope in your own dreams. But our dreams can’t come true if we don’t believe in them! Even if you’re going through a really tough time right now, you can control the energy you bring into your life. Surround yourself with things that bring joy and faith into your life, and soon your life will begin to reflect the same."
    },
    "the moon": {
        "title": "When times are uncertain, we often begin to feel afraid or anxious. The Moon card represents a time of the unknown where we might feel out of control. But rather than hiding or running from the shadows, take the time to listen to your intuition. Whatever is revealed to you will only serve you in the end. When we discover things that are hidden beneath the surface, we can take action to better our environment.",
        "normal": "There’s more going on than meets the eye right now, and you need to do a little digging to get to the bottom of things. Beneath the surface, there is information that needs to be revealed. The Moon card in the present position encourages you to take some time to explore the messages your heart is sending you. Don’t dismiss worries or fears because they may be messengers, but don’t run wild with them either! There is a difference between exploring shadows and letting negative emotions take over.",
        "reversed": "You are falling into a negative spiral of anxiety and fear around a situation where you feel out of control. The Moon in reverse indicates the most negative aspects of this card. Someone may be trying to deceive you, or you may be deceiving yourself. Alternately, a period of confusion is finally coming to an end and clarity is returning. Look to the surrounding cards and choose the path that resonates with your current situation."
    },
    "the sun": {
        "title": "Positive energy is all around you sending warmth and confidence to all that you do. Just like the sun in our sky makes the plants grow and gives us light and warmth, The Sun card of the tarot is also representative of the source. It comes toward the end of the Major Arcana after The Fool has made his journey through many obstacles and challenges. All of these trials have made the querent a better person because he now knows how to live in the light.",
        "normal": "You are shining like the sun right now and success is following you in whatever you do! Your relationships are joyful, your career is fulfilling, and you’re enjoying recognition. Whatever aspect The Sun card represents in your reading, it will be positive and abundant. You’re full of energy and optimism right now and the world is your oyster. This tarot card indicates that you are at your most powerful right now but in a healthy way.",
        "reversed": "You’re probably feeling sad or low on energy since The Sun card has presented in the reversed position. Conversely, if you’re treating people disrespectfully or giving yourself too much credit, this card will also present in the reverse. The Sun card represents healthy confidence, vitality, and power, which means that it is deserved and not at anyone else’s expense. Bring your confidence back to an honest place."
    },
    "the judgement": {
        "title": "When we undergo a spiritual awakening we realize that the answers are always within us. Others who judge us are merely projecting their own fears and insecurities on us and the same is true when we judge other people. Judgements come from a place of fear and we erroneously think that if we reject what makes us feel uncomfortable we will somehow be safe from it. The Judgement card asks us to look within ourselves instead, so that we may be freed from past beliefs and choices and live our lives with grace.",
        "normal": "You are at the precipice of a major decision that will impact your life in a profound way. Gather all of your life’s lessons and trust your heart. Have the courage to make the right decision based on what honors you and your truth. Let go of any past wounds, shame, or guilt, and face this challenge with truth and integrity. You will need both your intuition and your intellect to take advantage of this life-changing transformation and respond to your inner calling.",
        "reversed": "It creeps up on you quietly in the back of your mind. You know in your heart that it resonates but you push it away. When the Judgement card appears in the reverse, it suggests that you hear the call but are choosing to ignore it. Whether it’s out of fear or disbelief, you must have confidence in your ability to handle the situation. When you arrive at these crossroads you must choose one way or the other. You cannot stay in the same spot forever."
    },
    "the world": {
        "title": "You feel like you’re on cloud nine right now because your life is in perfect alignment with your innermost dreams and desires. You successfully completed your journey through the 22 cards of the Major Arcana, each one of them carrying a profound lesson with accompanying challenges. All of these obstacles were your training ground and the final card, The World, marks your arrival! You learned to trust the universe as well as yourself, and you learned to surrender when needed. You learned to use your intuition and control your passions.",
        "normal": "Are you wondering if things are too good to be true? Are you worried that the blessings that are coming your way right now are not real? It’s not every day that people see their dreams actually manifest in real life, but that is exactly what is happening to you right now. Whether you’re marrying the love of your life or starting your first day of work at your dream job, The World card represents arriving at everything you have been working toward.",
        "reversed": "Don’t despair that The World card showed up in the reverse this time! It doesn’t mean that your dreams are unattainable, just that you still have another hurdle to overcome before you get there. The problem could be that someone else is standing in between you and your goals or that you are in your own way. Sometimes we self-sabotage out of anxiety without even realizing it. You are just experiencing a delay. Find the reason and fix it so you can make it to the finish line."
    },
    "ace of cups": {
        "title": "The Ace of Cups is the first card in the suit of Cups. A largely positive card, you should expect good things to happen when you see it. Cups represent emotions, and so the Ace of Cups tarot card can represent a beginning of emotions, think new relationships, friendships and connections. Cups represent our feelings, over our logical thoughts.",
        "normal": "The Ace of Cups in the present position means life is fine and well. Things are going to go well for the foreseeable near future. Don’t panic or worry if anything bad has just happened, treat it as a learning experience. You’re turning over a new leaf. Expect something new to happen, this tarot card symbolises something new, anywhere from meeting a new friend, to starting an entirely new chapter of your life. Look to help others, if you can help by listening to their issues then you will make such a great impact.",
    },
    "two of cups": {
        "title": "The Two of Cups is the second tarot card in the Cups suit. The Two of Cups shows a man and woman staring into each other’s eyes, gaze fixed over two large cups. The duality symbolism is clear; male and female on opposite ends of the card. The winged staff of the caduceus represents a mythic chimera; possibly something is amiss or unknown, although this does not signify deceit or lies.",
        "normal": "The Two of Cups in the present position means a new, good relationship may start. Look at ‘Romance’ and ‘Friends’ below. You never know what a relationship or friendship is going to be like when it starts. Now is a good time for you to look out for that perfect partner. Try not to settle for less. You might have to put in quite a bit of effort, emotionally, to be able to find the right person. Look to see if our life is somehow unbalanced and try to correct it if so, especially in any of your relationships, both romantic and friendly.",
    },
    "three of cups": {
        "title": "The Three of Cups is the third tarot card in the Cups suit. The card shows three people meeting, celebrating with cups held to the sky. A bounty of fruit and vegetables are by their feet. The scene is representative of a harvest festival ritual celebration, and gives off a good feeling. The Three of Cups is a good card to draw in almost any position.",
        "normal": "The Three of Cups tarot card in the present position can mean that you’ve just finished something great. A personal project has been completed, or something that has had a lot of time put into it is over. Consider the illustration. They have worked all year to raise the harvest and it’s finally over. This should be you. As the past definition implies, look to start something which you can work on, which will pay off in future. The farmer sows seeds hoping for a bountiful harvest. Look to where you can sow seeds in your life; work, school, friends, adventures, experiences, charities, helping others.",
    },
    "four of cups": {
        "title": "The Four of Cups is the fourth tarot card in the Cups suit. The image shows a man sitting under a tree, intently looking at three cups. An arm protruding from a cloud is offering him a fourth card, which he is either ignoring on purpose or just cannot see. Not a wholly positive card, but not bad either, the Four of Cups can represent a mind that is sometimes so focused that it misses the bigger picture.",
        "normal": "The Four of Cups tarot in the present position means that you should start thinking outside the constraints that you have set on yourself. You might have been hurt in the past, but you don’t want that to continue on for much longer. We all need time to get over things so don’t rush yourself. But be aware that it’s up to you to try to help yourself and see from a different and new perspective. Again, there may be something you’re missing, so try to see the bigger picture of what is going on. Try to explore all avenues.",
    },
    "five of cups": {
        "title": "The Five of Cups is the fifth tarot card of the Cups suit. Taking a darker outlook, the Five of Cups is one of the negative tarot cards. The central character, clad in black faces three overturned cups, representing failure. Behind him are two upright ones. There is a certain positive aspect, not all is lost, but right now he is failing to see it.",
        "normal": "The Five of Cups in the present position means you may currently be going through a stressful period of your life. There might be some highly charged emotions being thrown around and you’re focusing on the negative or worst possible outcome. Think of the hidden benefits that are currently being overshadowed by events. Every cloud has a silver lining, no matter how dark or stormy it might seem. Bad things happen to us all, but they end, and we know this. This isn’t to say you should be flippant with how you react, learn, live and grow.",
    },
    "six of cups": {
        "title": "The Six of Cups is the sixth card in the Cups suit. The children suggest it’s a look back to childhood. The cups are not being used for their intended purpose, but inventively being used as a vase for flowers. A pleasant positive card which brings back warm memories of the past.",
        "normal": "The Six of Cups in the present position means you might be spending a bit too much time thinking about what you consider to be the best part of your life. Usually there isn’t much harm in thinking about the past but don’t dwell on it. You can have better experiences now if you want, nothing is stopping you. We do not experience a ‘golden age’, and when the future comes, you can be nostalgic for the most mundane things. Take pleasure in life now, and do your best.",
    },
    "seven of cups": {
        "title": "The Seven of Cups is the seventh tarot card in the suit of Cups. The card is all about choices. The character is having a vision of 7 cups offering 7 different gifts and is having trouble deciding. One of the choices is different from the others; an objected veiled in a cloth. We can interpret this as viewing the future and the clouded choices that we make based on appearance and assumption instead of fact.",
        "normal": "The The Seven of Cups in the present position means you might currently be overwhelmed with an abundance of choice. it might be too much, and each one may seem just as promising as the other. You have to cut down your options and choose which is best. There may even be no bad choice, but the key is to remember that you will have to make a decision; you can’t have it all. It’s frequent in our lives that one choice may negate the option to choose another; choose one job over the other, choosing a partner eliminates other choices. Sometimes we don’t even go with the correct decision but remember if you do not make a decision, then more often than not, a decision is made for you.",
    },
    "eight of cups": {
        "title": "The Eight of Cups is the eighth card in the Cups suit. The illustration shows a man walking away from a river, on the other bank are some cups stacked irregularly, leaving a large visible gap. Heading away, the man is abandoning his cups, the structure they created left unfinished.",
        "normal": "The Eight of Cups in the present position means you’re going to experience something new, and it will be completely different. You need to break out of your shell. What’s keeping you tied up and constrained? You can’t be like this forever. Move towards what you want to do. The Eight of Cups is quite a negative card, so expect something bad to happen. The days following a bad experience are crucial to your recovery. Sometimes, after a traumatic event like a breakup, we can cower in our shell and not want to experience the world. Honestly, just take each day as it comes, deal with things one day at a time.",
    },
    "nine of cups": {
        "title": "The Nine of Cups is the ninth tarot card in the Cups suit. A positive card generally, the illustration shows a character sitting in front of a collection of nine cups, proudly on display. His big grin and folded arms give us a sense of completion; he has achieved.",
        "normal": "The Nine of Cups in the present position means that it’s all going to work out. You might currently be struggling but remember if you don’t give up, you can only succeed. Keep going. You’ll have something to be really proud of. A great card to read if you’re in the middle of a project at work, or an important piece of work at school or college.",
    },
    "ten of cups": {
        "title": "The Ten of Cups is the tenth tarot card in the Cups suit and is an extremely positive card. The illustration shows ten cups suspended in a rainbow with a couple, likely married, looking at it. Children play in the foreground and an idyllic village lays in the background. The Ten of Cups is all about happiness and being positive.",
        "normal": "The Ten of Cups tarot in the present position means things are going well. In a way, you might have escaped the thought patterns of needing to get better and improve at something. You’ve achieved what you set out to achieve. Look to a new adventure, or stay where you are for a while longer, there is nothing wrong with enjoying what you have accomplished, after all, that is what we set out to do when we begin anything.",
    },
    "page of cups": {
        "title": "The Page of Cups is the eleventh tarot card in the Cups suit. The illustration shows a young man dressed in blue, holding a cup in his right hand. A fish is looking out of the cup at the man, and he is looking back. The card shows the innocence and curiosity of our inner child, as well as large imaginations unrestricted by logic or experience. Like many cards in the Cups suit, it’s a positive one. Fish emerging from water could be a symbol of knowledge being imparted, much like Oannes of Sumerian mythology",
        "normal": "The Page of Cups in the present position has a few interpretations. If you have children, expect a significant upcoming event. Maybe they’re starting to walk or talk, it’ll be memorable. If you don’t, expect to get acquainted with somebody younger than you. They might be able to show you a new perspective on life or help you refocus on something you’re concentrating on completing. You might be able to give advice to those looking for guidance. Expect something sudden to happen in any case.",
    },
    "knight of cups": {
        "title": "The Knight of Cups tarot card is the twelfth card in the Cups suit. The Cups are a positive suit, and the Knight of Cups is no different. With slight romantic undertones (think of the traditional Knight saving the Princess), the Knight of Cups is all about good news, and positive change.",
        "normal": "The Knight of Cups in the present position can mean you’re currently on a plateau as far as life is concerned. You might be thinking about your next adventure and looking for new goals. It could be that you feel stuck where you are now, and you’re waiting for a way out, usually a favour someone owes you or a task that only you are able to complete. If you’re in a relationship, you may be expected to make a choice between what your heart tells you, and what your head is saying.",
    },
    "queen of cups": {
        "title": "The Queen of Cups is the thirteenth card in the Cups suit. Thirteen isn’t really an unlucky number when it comes to The Queen of Cups, like most other cards in the Cups suit, The Queen of Cups is a positive one. It also has many possible interpretations, from the straight obvious meaning of a female influence in your life to interpretations of maturity and intuition.",
        "normal": "The Queen of Cups in the present position can mean that you’re currently going through a period in your life that requires you to be more patient and mature than normal. You may have just been put in charge of children, or people less mature than you who you need to keep your eye on. It shouldn’t be too much to worry about. Try to put your own good values in the people you meet and inspire them. Actively look to help others around you, they may be too shy to ask you.",
    },
    "king of cups": {
        "title": "The King of Cups is the fourteenth card in the Cups suit. Initially, as a King, you’d think the King of Cups is a mainly masculine card, but overall as Cups deal with emotions, it is quite a balanced tarot card. The King sits in a throne surrounded by water, holding a cup and a scepter in his hands.",
        "normal": "The King of Cups in the present position has a few meanings. Firstly, you may have to make a tough decision. It’s best to think it over and take the more ‘adult’ choice, rather than just jump in and choose what seems to be the most energetic and spontaneous. Secondly, it could mean that you’re about to come into contact with somebody who is able to help you greatly. You should really listen to what they are going to say. In life right now, you might be doing well, and feeling as though you are in control. Your plans should come to fruition without external influence.",
    },
    "ace of wands": {
        "title": "The Ace of Wands is the first tarot card in the suit of Wands. It’s a positive card, if you’re in any sort of creative field then take it as an extremely good sign. As it’s an Ace, expect new beginnings, especially relating to creativity and that first spark of inspiration to set an idea in motion.",
        "normal": "The Ace of Wands in the present position can be interpreted from its past position. You’re going to be faced with a choice that could dramatically affect your life. Be extremely open to new business ideas, even more so if they’re regarding art or a creative field. if you’re looking for a job, it might be a good idea to expand your horizons to these industries, you might have skills that are in demand! Just keep open for new opportunities. If you are really after a change, then just make it happen. There is no need to listen out for signs and symbols, impart your will on the world and get to work.",
    },
    "two of wands": {
        "title": "The Two of Wands is the second tarot card in the suit of Wands. Two is an important number in western esotericism, and regularly represents the duality of life. The Two of Wands refers to the potential of everybody for widening their own worldview, and that many limits are only self-imposed.",
        "normal": "The Two of Wands tarot in the present position is related to the Ace of Wands. Imagine the Ace of Wands has triggered your path, and the Two of Wands is you moving along it. If you need help with whatever it is you’re working on, now is the time to look to someone. As with any ‘two’, there’s going to be some decision making soon, so be prepared for it, especially if you know what your choices are.",
    },
    "three of wands": {
        "title": "The Three of Wands is the third card in the suit of Wands. A great card to see in a reading if there’s something you’re aiming for. The Three of Wands usually means you will attain your goals, through prior preparation and good foresight.",
        "normal": "The Three of Wands tarot in the present position can mean you’re about to start a new aspect of your life. It’s important not to rush into whatever this is, but if you devote yourself to it fully, you’ll see results. This is especially relevant if you or someone close to you is going for a job with prospects for advancement.",
    },
    "four of wands": {
        "title": "The Four of Wands is the fourth tarot card in the suit of Wands. A largely positive card, you should expect good things to happen when you see it, especially when relating to work and career or that project that you’re working on. It’s going to be a time to celebrate achievements, and relax now that the hard work is over.",
        "normal": "The Four of Wands tarot card in the present position means that you have to spend some time to know more and more about your chosen subject. if you’re working on something, ask for an outsiders opinion. People without knowledge of the area can give you a no-nonsense suggestion that you might not have considered.",
    },
    "five of wands": {
        "title": "The Five of Wands is the fifth card of the Wands suit. The Five of Wands is not a pleasant card and deals with conflict and sometimes aggression. The illustration shows five men fighting with wands, the victor, main aggressor or victim are all unclear.",
        "normal": "The Five of Wands in the present position means you may currently being going through a stressful period of your life. There might be some highly charged emotions being thrown around and you’re focusing on the negative or worst possible outcome. Don’t let your emotions get the best of you and lash out at the first opportunity. Now is a good time to avoid conflict in all forms. If you feel it is unavoidable, take control of your emotions and don’t let yourself go overboard and overreact too much.",
    },
    "six of wands": {
        "title": "The Six of Wands is the sixth tarot card in the Wands suit. The card resonates success and is a positive omen.",
        "normal": "The Six of Wands in the present position means there might be some good news coming. If you’ve been working hard, then expect it to pay off soon. Sometimes you need to let your hair down, especially if you’ve been focusing for a long time. Expect success in the short term,but this doesn’t mean you should slack off and rest on what you have already done. Continue working hard if you want to see true results. Success only comes from the effort you put in.",
    },
    "seven of wands": {
        "title": "The Seven of Wands is the seventh card in the suit of Wands. A positive card in some respects; especially relating to contests or competitions. The Seven of Wands is closely related to your willpower, and meanings will change based on how determined you are in life.",
        "normal": "This tarot card in the present position can mean there’s an upcoming period of competition or conflict. You can come out on top if you apply yourself and actually want to succeed. The Seven of Wands is especially good news if you’re applying for a job or place at a college; you’re likely to beat the competition there.",
    },
    "eight of wands": {
        "title": "The Eight of Wands is the eighth tarot card in the suit of Wands. A completely enigmatic illustration for the Eight of Wands lends little initial help into even a sensible guess at its meaning.",
        "normal": "The Eight of Wands tarot card in the present position has a mixed meaning. You could feel like you’re on a plateau in your life. Not much is going on and you want to make something of yourself. It’s best to try to avoid rushing into something, especially if this ‘thing’ is going to be taking up a large portion of your life. Do, however, try to jump into something trivial, and break up your schedule. Start a new after-hours class or group hobby. Sometimes, despite all advice, jumping into something unprepared can help us grow. We learn along the way, and we learn best by doing.",
    },
    "nine of wands": {
        "title": "The Nine of Wands is the ninth tarot card in the suit of Wands. The previous cards in the wands suit have been mainly positive with exceptions, but the Nine of Wands is where the meanings start to take a more cautious approach.",
        "normal": "The Nine of Wands tarot in the present position means life is going steady now, despite previous hardships. There might still be one last challenge ahead of you which needs tackling, so recover while you can, if you need to. It’s time to enjoy things that you’ve worked for, because you truly deserve them now.  If you’re feeling spontaneous, now is the time to just pack up some things and go explore. You might feel scared of the big wide world but the fear only comes from the unknown.",
    },
    "ten of wands": {
        "title": "The Ten of Wands is the tenth tarot card in the suit of Wands. As seen in the Nine of Wands, it isn’t as positive as early cards in the suit. The illustration shows a man burdened by the weight of ten wands. he can see his destination but has a long way to travel.",
        "normal": "The Ten of Wands in the present position can mean that you currently feel stuck. There is always a way out, but it will be a challenge. Life is a series of challenges, not obstacles. Don’t feel like there is only one way forward, especially if it all feels very linear right now.",
    },
    "page of wands": {
        "title": "The Page of Wands is the eleventh card in the suit of Wands and the first face card. As it is a face card, it could represent a real-life person, even someone that you know; likely a younger male influence in your life. The illustration on the Rider-Waite deck shows the Page inspecting a wand, well dressed and standing in front of a barren desert landscape.",
        "normal": "The Page of Wands in the present position is a good sign, that good news is coming. Are you looking to do something completely new? If so, you’re likely to do something memorable very soon. You might find that life changes very soon, whereas before you were on a path, you might have just reached the destination now. Instead of feeling aimless, you should follow wherever your passions take you.",
    },
    "knight of wands": {
        "title": "The Knight of Wands is the eleventh card in the suit of Wands. The Knight of Wands, much like the Page of Wands, exists in a barren desert. He even dresses similarly, with a salamander motif, though unlike the Page, he is moving at speed. The Knight has decided his goal and is on his way.",
        "normal": " The Knight of Wands tarot card in the present position can signify upcoming challenges; possibly one great challenge. You may be searching for meaning and may be longing for a journey. If you’re planning to get away, then just do it, especially if you’re feeling at a loose end; a short trip soon could change your worldview for the better. If you haven’t got any plans, try to experience something completely new, such as an foreign country you’ve never been to. It’s likely you’ll hear good news soon, especially related to work or your career.",
    },
    "queen of wands": {
        "title": "The Queen of Wands is the thirteenth tarot card in the Wands tarot suit. It’s likely to signify a positive, mature female influence in your life; especially someone with a good career, who is independent and honest. Without even reading the meanings, you might already have an idea of who it may be. She should be the sort of person to whom you could go for advice on any number of topics in life. The black cat is a sign of luck.",
        "normal": "The Queen of Wands in the present position has a few meanings. You might be in a career that you’re enjoying and working hard in, and the Queen of Wands can reassure you that you’re going to have the time, energy and money to work how you want to; comfortably and free of stress. It can also represent a feminine influence in your life, usually somebody you can go to for advice, but also someone who will need your input soon. When you go to somebody for advice, you should also be open to them coming back to you. Both of you can play the role of the caregiver.",
    },
    "king of wands": {
        "title": "The King of Wands tarot card is the final card in the suit of Wands. The King of Wands embodies much of the meaning of the entire suit and should be taken seriously when seen. Much like the Queen of Wands, The King can represent a strong male influence in your life, somebody who has succeeded and lived their dream. You might find them quite inspiring. This could also represent you, having achieved your goals, meaning you are ready to help others with theirs.",
        "normal": "The King of Wands tarot card in the present position can mean that if you work hard in the area that you wish to succeed in, you will succeed. If you don’t give up, nothing can stop you. It may take time if you aren’t used to it, but keep going, as you can only improve. Work with others of similar skill, and don’t feel like you’ve been left behind. Help yourself.",
    },
    "ace of swords": {
        "title": "The Ace of Swords is the first card in the suit of Swords. All aces can mean a new start. Like a sword, the actions that bring forth this new change can act quickly and without warning. Aces regularly represent a new beginning, coupled with Swords, this suggests a new personal goal or worldview. You may see yourself coming out of your shell soon.",
        "normal": "The Ace of Swords in the present position can be interpreted from it’s past position. You’re currently in a period of change, or you’re just about to head into a sudden, unexpected change which will affect you personally. It may possibly be violent, but if you’re the one causing the violence or stress, you need to calm down. Acting rashly isn’t always a bad thing, but make sure it’s you who is controlling your actions, and not your emotions. Think things through and then act. You don’t go off to war without preparing.",
    },
    "two of swords": {
        "title": "The Two of Swords is the second tarot card in the suit of Swords. Two is a common number in esoteric study and understanding; balance, two halves of one whole, male and female, good and bad. This is a balanced card; not wholly about action itself, but more focusing on what to do with the information you have.",
        "normal": " The Two of Swords in the present position means you should stop putting it off. Just do it. You can weigh the options up for eternity but more often than not you will regret not doing it rather than doing it and failing. Balance is that; good experiences and bad experiences are experiences. Would you rather experience things, or would you rather shy away from life?",
    },
    "three of swords": {
        "title": "The Three of Swords is the third tarot card in the suit of Swords. As you may have deduced from the illustration, the Three Swords is not a wholly positive card, especially when it comes to love.",
        "normal": "The Three of Swords doesn’t bode well for your current situation. If you aren’t happy, you need to start identifying ways out. If you’re staying sad for attention, then stop immediately. It’s hard to admit that you like sympathy, but some of us do it because we’re too afraid to try and fail. A failure is a victory if you learn from it. That’s a time old adage that loses meaning because it’s repeated so much, but it’s true. Learn from your mistakes, make more mistakes, and learn from them.",
    },
    "four of swords": {
        "title": "The Four of Swords is the fourth tarot card in the suit of Swords. The illustration shows the tomb of a knight in prayer, three swords adorn the wall and one is engraved on his tomb.",
        "normal": " The Four of Swords tarot card in the present position can mean that you’re currently feeling like you don’t want to interact or socialise. You just need some space to yourself. This isn’t a bad thing! To be ‘on’, we must have ‘off’ periods. Treat yourself to some ‘you’ time. If you’re currently working in a group and you feel it isn’t going right, look into taking it solo, it might be the best choice you can make right now.",
    },
    "five of swords": {
        "title": "he Five of Swords is the fifth card in the suit of Swords. When you see the Five of Swords, you should prepare for some conflict to come into your life. It might not be something to be scared of, but life is about to get at least a little bit more difficult. Don’t worry, you can always see it through.",
        "normal": "The Five of Swords in the present position means life is tough right now. Someone specifically may be antagonising you. You need to walk away from anything that isn’t productive. If you’re getting bullied, for example at work or at school, tell somebody and sort it out. Get a third party involved if you are experiencing any discomfort in life. Don’t suffer in silence. Sometimes all it takes is for somebody to listen to our thoughts.",
    },
    "six of swords": {
        "title": "The Six of Swords is the sixth tarot card in the suit of Swords. A more positive card than the most recent cards in the Swords suit; the worst is likely over and you’re ready for some change and growth in life.",
        "normal": "The Six of Swords tarot card in the present position can suggest that your life is on the up. Present burdens will soon be gone. You won’t be running away from your problems, but merely understanding that they no longer need to affect your life. You’re going to grow and you’ll realise later how far you have come.",
    },
    "seven of swords": {
        "title": "The Seven of Swords is the seventh tarot card in the suit of Swords. The illustration is particularly apt here; your first thought is likely a good insight into what the card means. The cards usually symbolise the person receiving the reading, but in this case, it’s sensible to consider all possibilities. The important thing isn’t to jump to conclusions when you read the meanings below.",
        "normal": "The Seven of Swords in the present position can mean that somebody is working on a scheme that will affect you negatively. They may even be pestering you or goading you into doing something which you’ll regret. You’ll have to be the bigger person in this case and either ignore it or take productive steps to stop this happening. If you’ve drawn the Seven of Swords in the present position, make sure to check the ‘Life issues’ below for further information.",
    },
    "eight of swords": {
        "title": "The Eight of Swords is the eighth tarot card in the suit of Swords. The illustration is somewhat frightening; a blindfolded woman surrounded by swords. She doesn’t know what to do, but inaction also isn’t a good choice. There is a way out, but more likely than not it will be painful.",
        "normal": "Life isn’t at all without struggle or pain. Bad experiences help you learn and grow so we cannot avoid them at all. Life might seem tough right now but just remember that it’s only a transitional period and the pain will go. Everything may seem impossible or too much to cope with, but remember, all you have to do is persevere and you’ll eventually break free. The problem comes with giving up. Your willpower is more than you think it is.",
    },
    "nine of swords": {
        "title": "The Nine of Swords is the ninth tarot card in the suit of Swords. A largely negative card, the illustration shows a man awakening from a nightmare, filled with grief. Nine swords are suspended on the wall at his bedside. His blanket is a patchwork quilt of red roses and zodiacal symbols. The Nine of Swords is widely regarded as a ‘bad’ card to draw, but take your whole reading into account when you interpret it.",
        "normal": "The Nine of Swords in the present position is not a good sign. If you’re not already suffering, expect something seemingly bad to happen. You’ll feel simultaneously under pressure and out of control. Prepare yourself and you’ll be able to weaken the blow. Life is always full of trials, however, and you can make it through, even if it keeps you up all night. Be aware that you’ll eventually overcome your issues.",
    },
    "ten of swords": {
        "title": "The Ten of Swords is the tenth tarot card in the suit of Swords. Running with the recent trend of the suit of swords; the Ten of Swords is not overly positive. The illustration somewhat backs this up; a man lying motionless on the ground with ten swords in his back. The Ten of Swords is regarded as the most destructive and grim card in the deck, but consider your entire reading when you interpret meanings.",
        "normal": "The Ten of Swords in the present position means that something important to you is about to finish or end. It will change your life, and it’s likely something you do not want to see happen. Prepare for the worst, but remember once it happens, thing can get no worse, you can only go up. It’s never good to hear, but life is not always an easy linear path. Catastrophic events can appear in your life suddenly, without warning and your only option is to be mentally strong enough to deal with them.",
    },
    "page of swords": {
        "title": "The Page of Swords tarot card is the eleventh card in the suit of Swords, and the first ‘face’ card. Just coming from the Ten of Swords, the Page of Swords is a step up in terms of positive energy. Face cards can stand for a real person in our lives, in this case possibly someone younger than the receiver of the reading but could as well be the person receiving the reading.",
        "normal": "The Page of Swords tarot in the present position should make you reassess your personal relationships with others. Do you have a strong or overbearing personality? You should tone it down a little. Try not to think you’re better than others, because they might value different things in their life to how you do. Not everybody is minimalist, nor materialistic, some value wealth and others do not. There is not one way to live life.",
    },
    "knight of swords": {
        "title": "The Knight of Swords is the 12th tarot card in the suit of Swords. A slightly more positive card, especially relative to the other cards in the swords suit so far. You should expect better things to happen when you see it, especially any news regarding a younger male you might know. Expect to receive good ideas if you’re stuck, or other good unexpected news.",
        "normal": "The Knight of Swords in the present position means you’ll soon be offered a chance to change your life. The key is that the actual offer might seem small, but the reward will be greater than the current imagination. It is suggested that you take the offer, no matter how small. Life opens up to us when we say yes to things, but doors close when we say no.",
    },
    "queen of swords": {
        "title": "The Queen of Swords is in the Minor Arcana and is the 13th tarot card in the suit of Swords. Usually, the queen will represent somebody in your life, most likely a mature woman who is quick to anger. Without even reading the meanings, you might already have an idea of who it may be.",
        "normal": "The Queen of Swords tarot in the present position can represent a strong current female influence in your life; you may also think about her romantically even though nothing of the sort could ever happen. Take their advice on board. It may not fit in exactly with your world-view but certain points will be useful. If there is nobody like this in your life, expect someone matching this description to make an appearance soon.",
    },
    "king of swords": {
        "title": "The King of Swords is the final card in the suit of Swords. The King of Swords embodies much of the meaning of the entire suit and should be taken seriously when seen. Much like the Queen of Swords, The King can represent a strong male influence in your life, someone with authority and power.",
        "normal": "The King of Swords tarot in the present position, similar to the past position would suggest a ‘father-figure’ currently present in your life. This could be your father or a strong leader at work or school. You should take what they say seriously, even if they haven’t followed what they believe in. They may have the best advice, but just because they haven’t followed it doesn’t make them any less right. Look for someone with a lot of experience who is truly interested in helping you for your sake and not their own. Personally, you may feel you are better than others at a certain subject. Make your personality more than this. Expertise is something that many of us aim for, but we need to have interests outside of our focus.",
    },
    "ace of pentacles": {
        "title": "The Ace of Pentacles is the first tarot card in the suit of Pentacles. A largely positive card, you should expect good things to happen when you see it. Pentacles represent material possessions and wealth. Pentacles in tarot are also sometimes called Coins. The pentacle itself is a well-known symbol with many meanings and interpretations in many faiths, notably Wicca. The Ace of Pentacles is well regarded as a favourable card to receive in a reading.",
        "normal": "The tarot card in the present position means life is fine and well in a material sense. You are not wanting for more possessions. Things are going to go well for the foreseeable near future. Don’t panic or worry if anything bad has just happened, treat it as a learning experience. The Ace of Pentacles presents our life on a plateau. You should be looking to where you can help others, as at the moment, you’re entering a high point of your life.",
    },
    "two of pentacles": {
        "title": "The Two of Pentacles is the second tarot card in the suit of Pentacles. Two is a common number in esoteric study and understanding; balance, two halves of one whole, male and female, ups and downs, good and bad. Generally, a positive card, the Two of Pentacles can remind us to respect the balance that our lives require.",
        "normal": "The Two of Pentacles in the present position has a few meanings. You could be balancing two aspects of your life; work and play, certain family and friends. This can be both good and bad, but as long as the balance is retained and you are comfortable, then things should continue to go well. Try not to get stuck living your life for other people. Sometimes we have to be selfish. As the past definition suggests, look out for a choice between two paths soon. It may be something which changes your life forever, and there will be many aspects of each choice to consider. Neither choice is good or bad, they are just different.",
    },
    "three of pentacles": {
        "title": "The Three of Pentacles is the third tarot card in the suit of Pentacles. A largely positive card, you should expect good things to happen when you see it, especially when relating to work and career.",
        "normal": "he Three of Pentacles tarot in the present position means that you have to spend some time to know more and more about your chosen subject. This could mean sending a bit more time mastering something at work to get ahead, or understanding a concept or possibly even starting a hobby you’ve previously pushed away. Now is the time! Generally, in life, you seem to be on the right track or at least improving. Try to act as a role model for other people. If you have qualities you’d like to see in others, display them in yourself first. This can be as simple as smiling and greeting more people than you usually do. Reaching out to others in any way often has a positive effect on the world and your own life.",
    },
    "four of pentacles": {
        "title": "The Four of Pentacles is the fourth tarot card in the suit of Pentacles. A somewhat positive card, you should expect some good things to happen when you see it. Watch out though, it has specific meanings that you might want to be careful with.",
        "normal": "The Four of Pentacles in the present position can mean that you’re holding on to things that you deem important. In the long run, remember that you can’t take them with you. Nobody, on their death bed, wanted to spend more time in the office making money. Understand what is most important to you. Material possessions, like everything, are transient. They will always come and go. Realise that whatever you have now can change, and we are always living in a state of flux.",
    },
    "five of pentacles": {
        "title": "The Five of Pentacles is the fifth tarot card in the suit of Pentacles. A quick look at the illustration gives a quick overview of the card depicts two men in walking in front of stained glass window, both look seem to be facing adversity and it is not a wholly positive card. When it comes up in a reading, prepare yourself for news you hadn’t hoped for.",
        "normal": "The Five of Pentacles tarot card in the present position means life is tough and doesn’t feel like it’s improving. You might have been through worse, you may not have. It could only be affecting some aspects of your life. If you are suffering, look to people to reach out to. You might think they can’t help you, but just telling someone will take the weight off. There is always help but we often shy away from it, and some prefer to suffer in silence. Try to reach out to others, and realise that eventually, you will start to see the bigger picture and place yourself within it.",
    },
    "six of pentacles": {
        "title": "The Six of Pentacles is the sixth tarot card in the suit of Pentacles. A more positive card than the most recent cards in the Pentacles suit; things are starting to look much more positive and also mature now. Expect to see things how they really are, and to understand how much of a positive change you can make in the world.",
        "normal": "The Six of Pentacles tarot card in the present position can in a way speak of current uncertainties. You may be blessed with someone and you’re unsure how to use it. Traditional techniques come to mind but it’s likely you need to get off autopilot and start a new approach. You might be engaging with others who have a completely different world-view to you; so in order to integrate, you’re going to need to adapt to their lifestyle, not the other way around.",
    },
    "seven of pentacles": {
        "title": "The Seven of Pentacles is the seventh tarot card in the suit of Pentacles. A positive card from the minor arcana, you should expect good things to happen when you see it. The illustration shows a man growing crops (crops of Pentacles) and peacefully watching over them. He has put in the effort to nurture them to grow and is about to reap the reward of his prior hard work.",
        "normal": " The Seven of Pentacles in the present position means life is slow and steady, you are reaping rewards of past sensible thinking and planning ahead for the future. Remember to be safe with whatever you are doing, take precaution. You might feel ‘stuck’ where you are now, and the Seven of Pentacles being drawn might mean you’re going to be here for a little while longer. You can make the most of it by doing your best in your current paradigm and eventually overcoming your boundaries.",
    },
    "eight of pentacles": {
        "title": "The Eight of Pentacles is the eighth tarot card in the suit of Pentacles. A positive card, you should expect good things to happen when you see it; especially aspects relating to a creative industry, or a project or part of your life that you have worked extremely hard on and dedicated yourself to. A good card to draw if you are intent on learning a skill or trade which you have a lot of passion for.",
        "normal": "The Eight of Pentacles in the present position has a mixed meaning. Here, the Eight of Pentacles represents a future path you could choose. Do you want to put the effort in and be rewarded? You might have a much easier option available to you. Don’t treat it is ‘it’s easy so it must be the wrong choice’. Instead, carefully weigh up the options. if you have a passion, now might be the time to throw caution to the wind and embrace it as a larger part of your life.",
    },
    "nine of pentacles": {
        "title": "The Nine of Pentacles is the ninth tarot card in the suit of Pentacles. Similar in appearance to The Seven of Pentacles with the plant imagery, but with stark differences. The illustration in the Seven of Pentacles shows a man resting after work and enjoying what he started a while ago, whereas the Nine of Pentacles shows a woman casually enjoying a garden, with no signs of labour, though a Falcon rests on her left hand.",
        "normal": "The Nine of Pentacles tarot in the present position means life is going steady. It’s time to enjoy things that you’ve worked for, or obtained through other means. Pentacles are all about materialism and objects. You might find the things you have lacklustre and want to keep moving on and moving on. Be careful not to get into a cycle of buying newer versions and buying into new trends simply because you’re bored. Understand that it’s all a cycle of buying, using, and stopping. Once you understand it’s a full circle, you’ll be better off without. If you’re feeling spontaneous, now is the time to just pack up some things and go explore.",
    },
    "ten of pentacles": {
        "title": "The Ten of Pentacles is the tenth tarot card in the suit of Pentacles. It is a positive card in terms of material retention, don’t expect to be needy or in want of something you desire.",
        "normal": "The Ten of Pentacles in the present position means life is fine and well. Things are going to go well for the foreseeable near future. Don’t panic or worry if anything bad has just happened, treat it as a learning experience. Think about your own skills are merits and how you can apply yourself in the world. You have the skills but might need a kickstart, so look for someone to motivate you.",
    },
    "page of pentacles": {
        "title": "The Page of Pentacles is the eleventh card in the suit of Pentacles, and the first ‘face’ or ‘court’ card. A largely positive card, you should expect good things to happen when you see it, especially in any areas concerning long term goals or progression. The Page of Pentacles in tarot readings grounds us in the ‘real world’, so that we can manifest our dreams as tangible goals to achieve.",
        "normal": "The Page of Pentacles in the present position means life is fine and well and that things are going to change for the better in the near future. Don’t panic or worry if anything bad has just happened, treat it as a learning experience. You’re turning over a new leaf and there are loftier goals. it’s very likely that currently, you’re relatively happy with certain aspects of your life.",
    },
    "knight of pentacles": {
        "title": "The Knight of Pentacles is the 12th tarot card in the suit of Pentacles. A  positive card, you should expect good things to happen when you see it, especially any news regarding a younger male you might know. As you may expect, the card embodies some knightly qualities; things many of us would do well to aspire to.",
        "normal": "The Knight of Pentacles tarot card in the present position means you’ll be motivated and possibly inspired by somebody younger than you, especially if you’re currently bored with life. This could possibly mean someone physically younger, but can also mean somebody new to an activity that you’re a part of. Don’t be put out if they start doing better than you did when you were in their position.",
    },
    "queen of pentacles": {
        "title": "The Queen of Pentacles is the 13th tarot card in the suit of Pentacles. Usually, the queen will represent somebody in your life, an older woman, who has a very comfortable life. Without even reading the meanings, you might already have an idea of who it may be. Many draw parallels between The Queen of Pentacles and the concept of Mother Earth; a nurturing feminine spirit that takes care of us if we take care of her.",
        "normal": "The Queen of Pentacles in the present position has a few meanings. You might just be settling down, and the Queen of Pentacles can reassure you that you’re going to have the time, energy and money to live how you want to; comfortably and free of stress. It can also represent a feminine influence in your life, usually somebody you can go to for advice. You might need them soon, and they will be more than happy to help.",
    },
    "king of pentacles": {
        "title": "The King of Pentacles is the final tarot card in the suit of Pentacles. The King of Pentacles embodies much of the meaning of the entire suit and should be taken seriously when seen. Much like the Queen of Pentacles, The King can represent a strong male influence in your life; likely somebody who is well off in a material sense.",
        "normal": "The King of Pentacles represents in the present position can mean you’re going to have to look to someone in your life for advice. A ‘father-figure’ is the obvious port of call here, and you should take what they say seriously, even if they haven’t followed what they believe in. They may have the best advice, but just because they haven’t followed it doesn’t make them any less right. It can also represent you. Do not keep your wisdom to yourself, but be there to answer questions for those seeking help.",
    },
}